.github/dependabot.yml, .github/pull_request_template.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, LICENSE, README.md, docs/README.md, infrastructure/README.md, src/README.md
- Adding basic project structure
=> Adding basic project structure

src/backend/TrafficCourtsApi/DisputeApi.Web.Test/Features/Tickets/Configuration/TicketServiceConfigurationTest.cs, src/backend/TrafficCourtsApi/DisputeApi.Web.Test/Features/Tickets/Models/TicketModelTest.cs, src/backend/TrafficCourtsApi/DisputeApi.Web.Test/Features/Tickets/Services/TicketServiceTest.cs, src/backend/TrafficCourtsApi/DisputeApi.Web/Features/Tickets/Configuration/TicketServiceConfigurationExtension.cs, src/backend/TrafficCourtsApi/DisputeApi.Web/Startup.cs
TCVP-54
- remove unused using
- refactor Ticket Model unit test
- converted to service collection to extension for ticket service injection
=> optimize project setup - dispute api

src/frontend/citizen-portal/package-lock.json, src/frontend/citizen-portal/package.json, src/frontend/citizen-portal/src/app/app-routing.module.ts, src/frontend/citizen-portal/src/app/app.module.ts, src/frontend/citizen-portal/src/app/modules/auth/landing/landing.component.html, src/frontend/citizen-portal/src/app/modules/survey-js/home/home.component.html, src/frontend/citizen-portal/src/app/modules/survey-js/home/home.component.spec.ts, src/frontend/citizen-portal/src/app/modules/survey-js/home/home.component.ts, src/frontend/citizen-portal/src/app/modules/survey-js/survey-js-routing.module.ts, src/frontend/citizen-portal/src/app/modules/survey-js/survey-js.module.ts, src/frontend/citizen-portal/src/app/modules/survey-js/survey-js.routes.ts, src/frontend/citizen-portal/src/app/modules/survey-js/survey-page/survey-page.component.html, src/frontend/citizen-portal/src/app/modules/survey-js/survey-page/survey-page.component.spec.ts, src/frontend/citizen-portal/src/app/modules/survey-js/survey-page/survey-page.component.ts, src/frontend/citizen-portal/src/scss/app.scss, src/frontend/citizen-portal/src/scss/vendors/_survey-js.scss, src/frontend/citizen-portal/src/scss/vendors/_vendors.scss, src/frontend/citizen-portal/tsconfig.json
- TCVP-52 - added surveyJS example
=> Add SurveyJS example

src/frontend/citizen-portal/src/app/modules/auth/landing/landing.component.html, src/frontend/citizen-portal/src/app/modules/dispute/components/dispute-dashboard/dispute-dashboard.component.ts, src/frontend/citizen-portal/src/app/modules/dispute/components/home/home.component.html, src/frontend/citizen-portal/src/app/modules/dispute/components/home/home.component.ts, src/frontend/citizen-portal/src/app/modules/dispute/components/part-a/part-a.component.html, src/frontend/citizen-portal/src/app/modules/dispute/components/part-a/part-a.component.ts, src/frontend/citizen-portal/src/app/modules/dispute/components/part-b/part-b.component.html, src/frontend/citizen-portal/src/app/modules/dispute/components/part-b/part-b.component.ts, src/frontend/citizen-portal/src/app/modules/dispute/components/part-c/part-c.component.html, src/frontend/citizen-portal/src/app/modules/dispute/components/part-c/part-c.component.ts, src/frontend/citizen-portal/src/app/modules/dispute/components/part-d/part-d.component.html, src/frontend/citizen-portal/src/app/modules/dispute/components/part-d/part-d.component.ts, src/frontend/citizen-portal/src/app/modules/dispute/components/start/start.component.html, src/frontend/citizen-portal/src/app/modules/dispute/components/start/start.component.spec.ts, src/frontend/citizen-portal/src/app/modules/dispute/components/start/start.component.ts, src/frontend/citizen-portal/src/app/modules/dispute/dispute-routing.module.ts, src/frontend/citizen-portal/src/app/modules/dispute/dispute.module.ts, src/frontend/citizen-portal/src/app/modules/dispute/dispute.routes.ts, src/frontend/citizen-portal/src/app/shared/components/page-footer/page-footer.component.ts
-TCVP-60 : Citizen Portal: Add Angular Stepper
=> add angular stepper to citizen portal

src/frontend/citizen-portal/angular.json, src/frontend/citizen-portal/src/app/app.module.ts, src/frontend/citizen-portal/src/app/config/config-code.pipe.spec.ts, src/frontend/citizen-portal/src/app/config/config-code.pipe.ts, src/frontend/citizen-portal/src/app/config/config.model.ts, src/frontend/citizen-portal/src/app/config/config.module.ts, src/frontend/citizen-portal/src/app/config/config.service.spec.ts, src/frontend/citizen-portal/src/app/config/config.service.ts, src/frontend/citizen-portal/src/app/core/interceptors/backend-http.interceptor.ts, src/frontend/citizen-portal/src/app/core/keycloak/keycloak.module.ts, src/frontend/citizen-portal/src/app/core/services/viewport.service.spec.ts, src/frontend/citizen-portal/src/app/shared/shared.module.ts, src/frontend/citizen-portal/src/tests/mocks/mock-config.service.ts, src/frontend/citizen-portal/src/tests/mocks/mock-config.ts, src/frontend/citizen-portal/src/tests/mocks/mock-keycloak.service.ts, src/frontend/citizen-portal/tsconfig.json
- Add support of mock code tables
- [x ] I have performed a self-review of my own code
=> Mock code table support

.github/workflows/code-climate-coverage-aggregation.yml, src/backend/TrafficCourtsApi/DisputeApi.Web.Test/DisputeApi.Web.Test.csproj
- TCVP-85: Set Up Code Climate Coverage for Backend .NET
Unit Tests ran successfully. Coverage reports generated and aggregated successfully.
=> TCVP-85: Configure Code Climate Coverage for Backend APIs

docker-compose.yml
- Getting container builds working for OpenShift
=> Naming containers

.github/workflows/push-dispute-api.yml
Tested in pipeline, verified it pushes to our repo.
=> Getting Dispute API to build and push to OpenShift

tests/src/test/java/stepDefinitions/frontendstepdefinitions/Steps.java, tests/src/test/resources/frontend/frontendTest.feature
- Removing frontend tests for demo requirements.
=> Removing frontend tests until requirements are finalized

.github/workflows/cucumber-tests.yml, .github/workflows/push-dispute-api.yml, docker-compose.yml, src/backend/TrafficCourtsApi/Dockerfile, tests/src/test/java/stepDefinitions/backendstepdefinitions/Steps.java
Built locally, pushed to OpenShift.
=> Changing to RHEL .NET containers

src/backend/TrafficCourtsApi/DisputeApi.Web.Test/DisputeApi.Web.Test.csproj, src/backend/TrafficCourtsApi/DisputeApi.Web/DisputeApi.Web.csproj, src/backend/TrafficCourtsApi/TrafficCourts.Common.Test/TrafficCourts.Common.Test.csproj
Update all out of date nuget packages
Packages were updated. Only minor package updates, no code changes required.
=> Nuget package update

tests/src/test/java/stepDefinitions/backendstepdefinitions/Steps.java
=> Remove Cucumber API tests

.github/workflows/push-frontend.yml
=> Github actions don't like linefeeds

src/frontend/citizen-portal/angular.json, src/frontend/citizen-portal/src/app/core/guards/auth.guard.spec.ts, src/frontend/citizen-portal/src/app/modules/auth/services/auth.service.ts, src/frontend/citizen-portal/src/app/modules/dashboard/components/dashboard-header/dashboard-header.component.spec.ts, src/frontend/citizen-portal/src/app/modules/dashboard/components/dashboard-header/dashboard-header.component.ts, src/frontend/citizen-portal/src/environments/environment.ts
- turn off source map
- minor update to dashboard so that user info is not retrieved if they are not logged in
=> Update SourceMap settings

src/backend/TrafficCourtsApi/DisputeApi.Web.Test/Features/Tickets/Configuration/TicketServiceConfigurationTest.cs, src/backend/TrafficCourtsApi/DisputeApi.Web.Test/Features/Tickets/Models/TicketModelTest.cs, src/backend/TrafficCourtsApi/DisputeApi.Web.Test/Features/Tickets/TicketServiceTest.cs, src/backend/TrafficCourtsApi/DisputeApi.Web.Test/Features/Tickets/TicketsControllerTest.cs, src/backend/TrafficCourtsApi/DisputeApi.Web.Test/StartUpTest.cs, src/backend/TrafficCourtsApi/DisputeApi.Web/Features/Tickets/Configuration/TicketServiceConfigurationExtension.cs, src/backend/TrafficCourtsApi/DisputeApi.Web/Features/Tickets/TicketsController.cs, src/backend/TrafficCourtsApi/DisputeApi.Web/Features/Tickets/TicketsService.cs, src/backend/TrafficCourtsApi/DisputeApi.Web/Startup.cs
- Change the name of feature TicketService to Tickets
=> Change feature TicketService to Tickets

docker-compose.yml
- Disable keycloak in build for now
=> Remove keycloak for now

.github/workflows/main-deploy.yml, .github/workflows/prod-deploy.yml, .github/workflows/test-deploy.yml
=> Fixing pipeline

docker-compose.yml
Update docker compose to use mock services
- [x ] Yes
=> Update the frontend to use mock services

src/frontend/citizen-portal/proxy.conf.json, src/frontend/citizen-portal/src/app/core/interceptors/backend-http.interceptor.ts, src/frontend/citizen-portal/src/app/core/resources/abstract-resource.ts, src/frontend/citizen-portal/src/app/modules/dashboard/components/dashboard-header/dashboard-header.component.ts, src/frontend/citizen-portal/src/app/modules/dispute/components/display-ticket/display-ticket.component.html, src/frontend/citizen-portal/src/app/modules/dispute/components/display-ticket/display-ticket.component.scss, src/frontend/citizen-portal/src/app/modules/dispute/components/display-ticket/display-ticket.component.spec.ts, src/frontend/citizen-portal/src/app/modules/dispute/components/display-ticket/display-ticket.component.ts, src/frontend/citizen-portal/src/app/modules/dispute/components/dispute-list/dispute-list.component.html, src/frontend/citizen-portal/src/app/modules/dispute/components/dispute-list/dispute-list.component.spec.ts, src/frontend/citizen-portal/src/app/modules/dispute/components/find-ticket/find-ticket.component.html, src/frontend/citizen-portal/src/app/modules/dispute/components/find-ticket/find-ticket.component.spec.ts, src/frontend/citizen-portal/src/app/modules/dispute/components/find-ticket/find-ticket.component.ts, src/frontend/citizen-portal/src/app/modules/dispute/dispute-routing.module.ts, src/frontend/citizen-portal/src/app/modules/dispute/dispute.module.ts, src/frontend/citizen-portal/src/app/modules/dispute/dispute.routes.ts, src/frontend/citizen-portal/src/app/modules/dispute/services/dispute-resource.service.ts, src/frontend/citizen-portal/src/environments/environment.ts
TCVP-169 - Call the RSI endpoint
- [x ] No
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] New and existing unit tests pass locally with my changes
=> TCVP-169 - Call the RSI endpoint

src/backend/TrafficCourtsApi/DisputeApi.Web/Startup.cs
- automatically lower cases the api routes
=> Use lower case urls for the api

src/frontend/citizen-portal/src/app/core/interceptors/backend-http.interceptor.ts, src/frontend/citizen-portal/src/app/modules/dispute/components/dispute-list/dispute-list.component.ts, src/frontend/citizen-portal/src/app/modules/dispute/components/find-ticket/find-ticket.component.html, src/frontend/citizen-portal/src/app/modules/dispute/services/dispute-resource.service.ts
Rename tickets endpoint
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [x ] New and existing unit tests pass locally with my changes
=> Rename tickets api endpoint

.github/workflows/main-code-climate-coverage-aggregation.yml, .github/workflows/main-cucumber-tests.yml, .github/workflows/main-deploy.yml, .github/workflows/prod-code-climate-coverage-aggregation.yml, .github/workflows/prod-cucumber-tests.yml, .github/workflows/prod-deploy.yml, .github/workflows/test-code-climate-coverage-aggregation.yml, .github/workflows/test-cucumber-tests.yml, .github/workflows/test-deploy.yml
=> Organized the pipeline namesin github actions

src/frontend/citizen-portal/src/app/core/interceptors/backend-http.interceptor.ts, src/frontend/citizen-portal/src/app/modules/auth/landing/landing.component.html, src/frontend/citizen-portal/src/app/modules/dispute/components/dispute-page/dispute-page.component.html, src/frontend/citizen-portal/src/app/modules/dispute/components/dispute-submit/dispute-submit.component.html, src/frontend/citizen-portal/src/app/modules/dispute/components/find-ticket/find-ticket.component.html, src/frontend/citizen-portal/src/app/modules/dispute/components/find-ticket/find-ticket.component.ts, src/frontend/citizen-portal/src/app/modules/dispute/components/step-count/step-count.component.html, src/frontend/citizen-portal/src/app/modules/dispute/components/step-overview/step-overview.component.html, src/frontend/citizen-portal/src/app/modules/dispute/components/step-review-ticket/step-review-ticket.component.html, src/frontend/citizen-portal/src/app/modules/dispute/components/step-review-ticket/step-review-ticket.component.scss, src/frontend/citizen-portal/src/app/modules/dispute/components/step-review-ticket/step-review-ticket.component.ts, src/frontend/citizen-portal/src/app/modules/dispute/components/stepper/stepper.component.html, src/frontend/citizen-portal/src/app/modules/dispute/components/stepper/stepper.component.spec.ts, src/frontend/citizen-portal/src/app/modules/dispute/components/stepper/stepper.component.ts, src/frontend/citizen-portal/src/app/modules/dispute/dispute.module.ts, src/frontend/citizen-portal/src/app/shared/models/dispute.model.ts, src/frontend/citizen-portal/src/tests/mocks/mock-dispute.service.ts
Demo update changes as specified by Simon. 
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [x ] New and existing unit tests pass locally with my changes
=> Demo Updates

src/frontend/citizen-portal/src/app/modules/dispute/components/dispute-list/dispute-list.component.html, src/frontend/citizen-portal/src/app/modules/dispute/components/dispute-submit/dispute-submit.component.html, src/frontend/citizen-portal/src/app/modules/dispute/components/dispute-summary/dispute-summary.component.html, src/frontend/citizen-portal/src/app/modules/dispute/components/dispute-summary/dispute-summary.component.scss, src/frontend/citizen-portal/src/app/modules/dispute/components/dispute-summary/dispute-summary.component.spec.ts, src/frontend/citizen-portal/src/app/modules/dispute/components/dispute-summary/dispute-summary.component.ts, src/frontend/citizen-portal/src/app/modules/dispute/components/find-ticket/find-ticket.component.html, src/frontend/citizen-portal/src/app/modules/dispute/components/find-ticket/find-ticket.component.ts, src/frontend/citizen-portal/src/app/modules/dispute/dispute-routing.module.ts, src/frontend/citizen-portal/src/app/modules/dispute/dispute.module.ts, src/frontend/citizen-portal/src/app/modules/dispute/dispute.routes.ts, src/frontend/citizen-portal/src/app/shared/dialogs/confirm-dialog/confirm-dialog.component.html, src/frontend/citizen-portal/src/app/shared/models/dispute.model.ts, src/frontend/citizen-portal/src/app/shared/models/ticket.model.ts, src/frontend/citizen-portal/src/scss/vendors/_survey-js.scss, src/frontend/citizen-portal/src/tests/mocks/mock-dispute.service.ts
TCVP-185 - Add Ticket/Dispute Summary Page
- [ x] New feature (non-breaking change which adds functionality)
=> TCVP-185 - Add Ticket/Dispute Summary Page

src/frontend/citizen-portal/src/app/modules/dispute/components/find-ticket/find-ticket.component.ts
Fix bug setting route queryparams
- [ x] Bug fix (non-breaking change which fixes an issue)
=> Fix bug setting route queryparams

.github/workflows/main-code-climate-coverage-aggregation.yml
=> TCVP-192: Resolving Frontend Code Coverage

src/frontend/citizen-portal/src/app/modules/dispute/components/display-ticket/display-ticket.component.html
- Fix display of RSI Ticket information (based on Peggy's backend changes)
=> Fix display of RSI Ticket

src/frontend/citizen-portal/src/app/modules/dispute/components/display-ticket/display-ticket.component.html, src/frontend/citizen-portal/src/app/modules/dispute/components/display-ticket/display-ticket.component.spec.ts, src/frontend/citizen-portal/src/app/modules/dispute/components/display-ticket/display-ticket.component.ts, src/frontend/citizen-portal/src/app/modules/dispute/components/dispute-list/dispute-list.component.ts, src/frontend/citizen-portal/src/app/modules/dispute/components/dispute-summary/dispute-summary.component.ts, src/frontend/citizen-portal/src/app/modules/dispute/components/find-ticket/find-ticket.component.ts, src/frontend/citizen-portal/src/app/modules/dispute/components/stepper/stepper.component.ts, src/frontend/citizen-portal/src/app/shared/models/ticket.model.ts, src/frontend/citizen-portal/src/tests/mocks/mock-dispute.service.ts
=> Move RSI query inside component

src/frontend/citizen-portal/src/app/core/interceptors/backend-http.interceptor.ts, src/frontend/citizen-portal/src/app/core/services/toast.service.ts, src/frontend/citizen-portal/src/app/core/validators/form-control.validators.ts, src/frontend/citizen-portal/src/app/modules/dispute/components/dispute-summary/dispute-summary.component.html, src/frontend/citizen-portal/src/app/modules/dispute/components/dispute-summary/dispute-summary.component.scss, src/frontend/citizen-portal/src/app/modules/dispute/components/dispute-summary/dispute-summary.component.ts, src/frontend/citizen-portal/src/app/modules/dispute/components/step-count/step-count.component.html, src/frontend/citizen-portal/src/app/modules/dispute/components/step-count/step-count.component.ts, src/frontend/citizen-portal/src/app/modules/dispute/components/step-court/step-court.component.html, src/frontend/citizen-portal/src/app/modules/dispute/components/step-overview/step-overview.component.html, src/frontend/citizen-portal/src/app/modules/dispute/components/step-overview/step-overview.component.ts, src/frontend/citizen-portal/src/app/modules/dispute/components/step-review-ticket/step-review-ticket.component.html, src/frontend/citizen-portal/src/app/modules/dispute/components/stepper/stepper.component.html, src/frontend/citizen-portal/src/app/modules/dispute/components/stepper/stepper.component.spec.ts, src/frontend/citizen-portal/src/app/modules/dispute/components/stepper/stepper.component.ts, src/frontend/citizen-portal/src/app/modules/dispute/services/dispute-form-state.service.ts, src/frontend/citizen-portal/src/app/modules/dispute/services/dispute-resource.service.ts, src/frontend/citizen-portal/src/app/modules/dispute/services/dispute.service.ts, src/frontend/citizen-portal/src/app/shared/components/page-header/page-header.component.html, src/frontend/citizen-portal/src/app/shared/components/tco-page-header/tco-page-header.component.html, src/frontend/citizen-portal/src/app/shared/models/dispute.model.ts, src/frontend/citizen-portal/src/app/shared/models/offence.model.ts, src/frontend/citizen-portal/src/app/shared/models/ticket-dispute.model.ts, src/frontend/citizen-portal/src/app/shared/models/ticket.model.ts, src/frontend/citizen-portal/src/scss/material/_material.scss, src/frontend/citizen-portal/src/scss/material/components/_mat-snackbar.scss, src/frontend/citizen-portal/src/tests/mocks/mock-dispute.service.ts
- TCVP-170 - call endpoint to save dispute
- UI tweeks as suggested by Simon
- Stepper update to remove dynamic step "list"
- [x ] No
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] New and existing unit tests pass locally with my changes
=> Frontend Save Dispute

src/frontend/citizen-portal/src/app/modules/dispute/components/dispute-submit/dispute-submit.component.ts, src/frontend/citizen-portal/src/app/modules/dispute/components/dispute-summary/dispute-summary.component.html, src/frontend/citizen-portal/src/app/modules/dispute/components/step-count/step-count.component.html, src/frontend/citizen-portal/src/app/modules/dispute/components/step-count/step-count.component.ts, src/frontend/citizen-portal/src/app/modules/dispute/components/step-overview/step-overview.component.html, src/frontend/citizen-portal/src/app/modules/dispute/components/step-overview/step-overview.component.ts, src/frontend/citizen-portal/src/app/modules/dispute/components/stepper/stepper.component.ts, src/frontend/citizen-portal/src/app/modules/dispute/services/dispute-form-state.service.ts, src/frontend/citizen-portal/src/app/modules/dispute/services/dispute.service.ts, src/frontend/citizen-portal/src/app/shared/models/dispute.model.ts, src/frontend/citizen-portal/src/tests/mocks/mock-dispute.service.ts
- Fix integration with the backend
=> Fix integration issues

.env.template, README.md, docker-compose.yml
- Add redis and rabbitmq to docker compose for local development (TCVP-205,TCVP-84)
=> Add redis and rabbitmq to docker

src/backend/TrafficCourtsApi/DisputeApi.Web.Test/Features/TicketLookup/TicketDisputeFromRsiServiceTest.cs, src/backend/TrafficCourtsApi/DisputeApi.Web/Auth/TokenService.cs, src/backend/TrafficCourtsApi/DisputeApi.Web/Features/TicketLookup/IRSIRestApi.cs, src/backend/TrafficCourtsApi/DisputeApi.Web/Keys.cs, src/backend/TrafficCourtsApi/DisputeApi.Web/Models/TicketDispute.cs, src/backend/TrafficCourtsApi/DisputeApi.Web/Properties/launchSettings.json, src/backend/TrafficCourtsApi/DisputeApi.Web/Startup.cs
-     TCVP-264    [backend] RSI Information update.
Tested locally and unit tests
=> update rsi info

src/frontend/citizen-portal/src/app/modules/dispute/components/dispute-summary/dispute-summary.component.html, src/frontend/citizen-portal/src/app/modules/dispute/components/step-count/step-count.component.html, src/frontend/citizen-portal/src/app/modules/dispute/components/step-overview/step-overview.component.html, src/frontend/citizen-portal/src/app/modules/dispute/components/step-review-ticket/step-review-ticket.component.html, src/frontend/citizen-portal/src/app/modules/dispute/services/dispute-resource.service.ts, src/frontend/citizen-portal/src/app/shared/models/dispute.model.ts, src/frontend/citizen-portal/src/app/shared/models/offence.model.ts, src/frontend/citizen-portal/src/tests/mocks/mock-dispute.service.ts
- Update the Models to match the RSI changes
=> Update the Models to match the RSI changes

src/backend/TrafficCourtsApi/DisputeApi.Web/Features/Disputes/Commands/CreateOffenceDisputeCommandHandler.cs, src/backend/TrafficCourtsApi/DisputeApi.Web/Features/Disputes/DBModel/Dispute.cs, src/backend/TrafficCourtsApi/DisputeApi.Web/Features/Disputes/DisputesController.cs, src/backend/TrafficCourtsApi/DisputeApi.Web/Features/Disputes/Mapping/MappingProfile.cs, src/backend/TrafficCourtsApi/DisputeApi.Web/Models/TicketDispute.cs, src/backend/TrafficCourtsApi/TrafficCourts.Common/Contract/DisputeContract.cs
- TCVP-304: additional message, Lawyer required and witness present should be bool.
- 
Tested locally
=> fix bool issue

.github/workflows/prod-cucumber-tests.yml, .github/workflows/prod-deploy.yml, .github/workflows/test-cucumber-tests.yml, .github/workflows/test-deploy.yml, README.md, src/backend/TrafficCourtsApi/Dockerfile, src/frontend/citizen-portal/Dockerfile, tools/build-tools.yml, tools/github-actor/Dockerfile
- Change registry.redhat.io to registry.access.redhat.com so we do not require authentication
=> Change registry.redhat.io to registry.access.redhat.com

docker-compose.yml
- Adds postgres to docker-compose
=> Added postgres to docker compose

src/frontend/citizen-portal/.devcontainer/Dockerfile, src/frontend/citizen-portal/.devcontainer/devcontainer.json, src/frontend/citizen-portal/.devcontainer/post-create.sh
- This PR includes changes to support for [Remote - Containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) to support front end development
Using Visual Studio Code opening the `src/frontend/citizen-portal` folder in "container" and tested the build
=> Add devcontainer configuration for development

docker-compose.yml, infrastructure/keycloak/Dockerfile
- Adds service dependencies to docker-compose file
- Re-adds required keycloak config docker file
=> Added dependencies to ensure startup order, add back keycloak dockerfile

.github/workflows/main-deploy.yml, .github/workflows/pr-frontend.yml
- Adjusts the build process to ensure the images are built with docker and not docker compose, removed 
=> Adjust github actions

.github/workflows/pr-label.yml
- Doesn't try to label if the secret is not available
=> Only label if required secret available

.github/workflows/pr-label.yml
- Builds were failing with `Unrecognized named-value: 'secrets'`
=> Remove if condition that was failing build

infrastructure/openshift/README.md, infrastructure/openshift/tickets-test.gov.bc.ca-route.yaml, infrastructure/openshift/tickets.gov.bc.ca-route.yaml, infrastructure/openshift/traffic-courts-online-app.yml
- Cleans up the OpenShift template to include only those services we need to deploy in the short term.
=> Clean up openshift templates getting ready for production

src/backend/TrafficCourtsApi/DisputeApi.Web.Test/Auth/OAuthClientTest.cs, src/backend/TrafficCourtsApi/DisputeApi.Web.Test/Auth/OAuthHandlerTest.cs, src/backend/TrafficCourtsApi/DisputeApi.Web.Test/Features/Disputes/Configuration/DisputeServiceConfigurationTest.cs, src/backend/TrafficCourtsApi/DisputeApi.Web.Test/Features/Disputes/DisputeControllerTest.cs, src/backend/TrafficCourtsApi/DisputeApi.Web.Test/Features/Disputes/DisputeServiceTest.cs, src/backend/TrafficCourtsApi/DisputeApi.Web.Test/Features/Disputes/Models/DisputeModelTest.cs, src/backend/TrafficCourtsApi/DisputeApi.Web.Test/Features/TicketLookup/TicketDisputeFromRsiServiceTest.cs, src/backend/TrafficCourtsApi/DisputeApi.Web.Test/Features/Tickets/Configuration/TicketServiceConfigurationTest.cs, src/backend/TrafficCourtsApi/DisputeApi.Web.Test/Features/Tickets/Models/TicketModelTest.cs, src/backend/TrafficCourtsApi/DisputeApi.Web.Test/Features/Tickets/TicketServiceTest.cs, src/backend/TrafficCourtsApi/DisputeApi.Web.Test/Features/Tickets/TicketsControllerTest.cs, src/backend/TrafficCourtsApi/DisputeApi.Web.Test/Health/DisputeApiHealthCheckTest.cs, src/backend/TrafficCourtsApi/DisputeApi.Web.Test/StartUpTest.cs, src/backend/TrafficCourtsApi/DisputeWorker/DisputeRequestedConsumer.cs, src/backend/TrafficCourtsApi/DisputeWorker/DisputeUpdatedConsumer.cs
- Addresses the build warnings in the dotnet components
=> Adjust source to remove build warnings

infrastructure/openshift/tickets-test.gov.bc.ca-route.yaml, infrastructure/openshift/tickets.gov.bc.ca-route.yaml
This PR creates dev,test and prod folders for openshift artifacts.
=> create environment specific folders for deployment to openshift

infrastructure/openshift/traffic-courts-online-app.yml, src/frontend/citizen-portal/nginx.conf
- add livenessProbe, readinessProbe and enable nginx_status
=> Add livenessProbe, readinessProbe and enable nginx_status

infrastructure/openshift/sysdigteam.yaml
- Adds sysdigteam resource for the tools namespace to grant access to sysdig monitoring.
=> Add sysdig configuration for TCO

infrastructure/openshift/README.md, infrastructure/openshift/traffic-courts-online-app.yml
- Only mount app.config.json and do not overwrite other files in the assets directory
=> merge app config configmap changes

infrastructure/openshift/prod/citizen-web-configuration-configmap.yaml, infrastructure/openshift/traffic-courts-online-app.yml
- add prod config map, change rollout strategy to rolling
=> Add prod config map, change rollout strategy to rolling

src/frontend/citizen-portal/src/app/components/landing/landing.component.html
See if this fixes snowplow for the time being
=> Remove href bindings

src/frontend/citizen-portal/src/app/app.component.spec.ts, src/frontend/citizen-portal/src/app/app.component.ts, src/frontend/citizen-portal/src/app/app.module.ts, src/frontend/citizen-portal/src/app/components/landing/landing.component.html, src/frontend/citizen-portal/src/app/components/landing/landing.component.spec.ts, src/frontend/citizen-portal/src/app/components/landing/landing.component.ts, src/frontend/citizen-portal/src/app/snowplow.service.spec.ts, src/frontend/citizen-portal/src/app/snowplow.service.ts, src/frontend/citizen-portal/src/app/window-ref.spec.ts, src/frontend/citizen-portal/src/app/window-ref.ts, src/frontend/citizen-portal/src/snowplow.js
- Create snowplow service
- Call snowplow to refresh links when landing page urls updated
Tested by running locally and viewing activity in snowplow inspector plugin for Chrome
=> Create snowplow service and refresh links when landing page urls updated

src/frontend/citizen-portal/src/app/app-routing.module.ts, src/frontend/citizen-portal/src/app/app.module.ts, src/frontend/citizen-portal/src/app/components/dispute-summary/dispute-summary.component.html, src/frontend/citizen-portal/src/app/components/find-ticket/find-ticket.component.html, src/frontend/citizen-portal/src/app/components/landing/landing.component.html, src/frontend/citizen-portal/src/app/components/landing/landing.component.ts, src/frontend/citizen-portal/src/app/core/guards/feature-flag.guard.spec.ts, src/frontend/citizen-portal/src/app/core/guards/feature-flag.guard.ts, src/frontend/citizen-portal/src/app/services/app-config.service.ts, src/frontend/citizen-portal/src/app/shared/components/tco-page-header/tco-page-header.component.html, src/frontend/citizen-portal/src/app/shared/directives/feature-flag.directive.spec.ts, src/frontend/citizen-portal/src/app/shared/directives/feature-flag.directive.ts, src/frontend/citizen-portal/src/app/shared/shared.module.ts, src/frontend/citizen-portal/src/assets/app.config.json
TCVP-501
Add ability to turn features off/on
=> Add ability to turn features off/on

.github/workflows/main-deploy.yml
- change main-deploy to tag image with short sha commit
=> change main-deploy to tag image with short sha commit

.github/labeler.yml, .github/workflows/main-deploy.yml, .github/workflows/peggy-test.yml, docker-compose.yml, gitops/components/apps/citizen-api/base/citizen-api-deployment-config.yaml, gitops/components/apps/citizen-api/base/citizen-api-service.yaml, gitops/components/apps/citizen-api/base/kustomization.yaml, gitops/components/apps/ticket-search/base/kustomization.yaml, gitops/components/apps/ticket-search/base/ticket-search-deployment-config.yaml, gitops/components/apps/ticket-search/base/ticket-search-service.yaml
- Jira 511
Tested with openshift DEV
=> ticket-search deployment config, and gitops structure

src/frontend/citizen-portal/nginx.conf
- TCVP-617(add config for front-end connect to backend)
=> connect to backend

README.md
- TCVP-678
Update ReadMe files
- [ x] Refactoring / Documentation
- [ x] No
- [ x] New and existing unit tests pass locally with my changes
=> Add information regarding ticket-search api

src/frontend/citizen-portal/README.md
=> Add command for installing angular cli

src/backend/TrafficCourtsApi/citizen-api/README.md
TCVP-678
- [x ] Refactoring / Documentation
- [ x] No
- [ x] New and existing unit tests pass locally with my changes
=> Update CitizenAPI ReadMe

docker-compose.yml, src/backend/TrafficCourtsApi/Dockerfile, src/frontend/citizen-portal/src/assets/app.config.json, src/ticket-search/Dockerfile
- fix the exception for rabbitmq in citizenApi when run app from docker-compose
=> make docker rabbitmq working

.github/workflows/imageUploadTesting.yml, src/backend/TrafficCourtsApi/citizen-api/Features/Disputes/DBModel/Dispute.cs, src/backend/TrafficCourtsApi/citizen-api/Features/Disputes/Mapping/MappingProfile.cs, src/backend/TrafficCourtsApi/citizen-api/Features/Tickets/Queries/TicketSearchQueryHandler.cs, src/backend/TrafficCourtsApi/citizen-api/Features/Tickets/TicketsController.cs, src/backend/TrafficCourtsApi/citizen-api/Models/TicketDispute.cs, src/backend/TrafficCourtsApi/citizen-api/Startup.cs
- TCVP-748(Integration support with front end)
- 
Tested in dev env
=> for frontend change

src/backend/TrafficCourtsApi/TrafficCourts.Common/Contract/NotificationContract.cs, src/backend/TrafficCourtsApi/TrafficCourts.Common/Contract/TicketDispute.cs, src/backend/TrafficCourtsApi/TrafficCourts.Common/Util/RandomGenerator.cs, src/backend/TrafficCourtsApi/citizen-api-test/Features/Disputes/Commands/CreateDisputeCommandHandlerTest.cs, src/backend/TrafficCourtsApi/citizen-api/Features/Disputes/Commands/CreateDisputeCommandHandler.cs, src/backend/TrafficCourtsApi/citizen-api/Features/Disputes/DBModel/Dispute.cs, src/backend/TrafficCourtsApi/citizen-api/Features/Disputes/Mapping/MappingProfile.cs, src/backend/TrafficCourtsApi/ticket-worker/Features/Notifications/NotificationRequestedConsumer.cs
- NotificationContract data model
Note: the confirmation letter is in draft status, so, this code will be changed once the letter content is finalized.
Tested locally
=> NotificationContract data model

gitops/components/apps/citizen-web/base/citizen-web-route.yaml, gitops/components/apps/citizen-web/base/citizen-web-route2.yaml
- https://justice.gov.bc.ca/jira/browse/TCVP-810
Tested locally
=> add balancer algorithm and disable cookie

src/backend/TrafficCourtsApi/ticket-worker-test/Features/Emails/DefaultEmailFilterTest.cs, src/backend/TrafficCourtsApi/ticket-worker-test/Features/Emails/EmailFilterTest.cs, src/backend/TrafficCourtsApi/ticket-worker-test/Features/Emails/NotFilteredEmailFilterTest.cs, src/backend/TrafficCourtsApi/ticket-worker-test/Features/Emails/TestData.cs, src/backend/TrafficCourtsApi/ticket-worker-test/Features/Emails/Validation_IsValidEmailTest.cs, src/backend/TrafficCourtsApi/ticket-worker/Features/Emails/DefaultEmailFilter.cs, src/backend/TrafficCourtsApi/ticket-worker/Features/Emails/EmailFilter.cs, src/backend/TrafficCourtsApi/ticket-worker/Features/Emails/IEmailFilter.cs, src/backend/TrafficCourtsApi/ticket-worker/Features/Emails/NotFilteredEmailFilter.cs, src/backend/TrafficCourtsApi/ticket-worker/Features/Emails/Validation.cs
This PR includes the classes to validate and supply an IEmailFilter service to filter emails.
Unit tests have been added with 95.08% code coverage. 
=> Add email filter classes and tests

src/frontend/citizen-portal/src/app/components/stepper/step-additional/step-additional.component.html, src/frontend/citizen-portal/src/app/components/stepper/step-additional/step-additional.component.ts, src/frontend/citizen-portal/src/app/services/dispute-form-state.service.ts, src/frontend/citizen-portal/src/assets/i18n/en.json, src/frontend/citizen-portal/src/scss/app.scss
- Removes verbiage on witness limit of 5
- Removes disputant notification box
- Show witness notification if disputant chooses to add witnesses
- Adds custom option for selecting more than 5 witnesses, a number input appears
=> update # of witnesses form field workflow to add number input

src/frontend/citizen-portal/src/app/components/dispute-submit-success/dispute-submit-success.component.html, src/frontend/citizen-portal/src/app/components/dispute-submit-success/dispute-submit-success.component.scss, src/frontend/citizen-portal/src/app/components/stepper/step-additional/step-additional.component.html, src/frontend/citizen-portal/src/app/components/ticket-payment-complete/ticket-payment-complete.component.html, src/frontend/citizen-portal/src/app/components/ticket-payment-complete/ticket-payment-complete.component.scss, src/frontend/citizen-portal/src/app/components/ticket-payment-complete/ticket-payment-complete.component.ts, src/frontend/citizen-portal/src/tests/mocks/mock-dispute.service.ts
- Adds Initiate Resolution button to payment complete page
- Fixes copy text colour & styling
- Aligns print button to the right
- Adds print button to the payment complete page
- Updates mockService for local testing, prior to testing with DEV data
Manual testing, and reviewing with UX designer.
=> adds button to resume resolution, print ticket, and fixed verbiage

src/backend/TrafficCourtsApi/ticket-worker-test/Features/Emails/EmailSenderTest.cs, src/backend/TrafficCourtsApi/ticket-worker/Features/Emails/EmailSender.cs, src/backend/TrafficCourtsApi/ticket-worker/Models/DisputeEmail.cs, src/backend/TrafficCourtsApi/ticket-worker/Program.cs, src/backend/TrafficCourtsApi/ticket-worker/appsettings.Development.json
=> Use EmailFilter in Email Sender

src/backend/TrafficCourtsApi/ticket-worker/appsettings.Development.json
- SMTP configuration for sending emails
=> Add SMTP configuration in app settings

src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.html, src/frontend/citizen-portal/src/app/components/stepper/step-count/step-count.component.html, src/frontend/citizen-portal/src/app/components/stepper/step-count/step-count.component.ts
- hides do nothing option if there is only one offence to action
This has been tested manually with tickets with 1, 2, and 3 counts.
=> hide do nothing option if there is only one offence to action

.github/workflows/imageUploadTesting.yml, gitops/components/apps/citizen-api/base/citizen-api-deployment-config.yaml, gitops/components/apps/ticket-search/base/ticket-search-deployment-config.yaml, gitops/components/apps/ticket-worker/base/ticket-worker-deployment-config.yaml, gitops/components/secrets/splunk-config.yaml, splunk-dash-board/operational-support.html, src/backend/TrafficCourtsApi/TrafficCourts.Common/Configuration/SplunkEventCollector.cs, src/backend/TrafficCourtsApi/citizen-api/Features/Tickets/TicketsController.cs, src/backend/TrafficCourtsApi/citizen-api/Properties/launchSettings.json, src/backend/TrafficCourtsApi/ticket-worker/Program.cs, src/backend/TrafficCourtsApi/ticket-worker/Properties/launchSettings.json, src/backend/TrafficCourtsApi/ticket-worker/Worker.cs, src/ticket-search/ticket-search/Controllers/TicketsController.cs, src/ticket-search/ticket-search/Program.cs
-Create initial splunk setup
Tested in dev
=> splunk log and first dashboard

src/frontend/citizen-portal/src/scss/app.scss
- updates styling of stepper titles to bold face when active
Reviewed stepper to see active step has a bold face title
=> updates styling of stepper titles to bold face when active

.github/workflows/main-deploy-workflow.yml
Included new github actions workflow which doesn't impact existing flows and contains the functionality to handle automatic version tagging during each deployment and can be triggered to deploy to any environment. 
- Included new Github actions workflow file.
Tested in local openshift sandbox env. This requires further review in-line with actual openshift set-up.
=> GitHub Actions POC 

.github/workflows/openshift-imagetagging.yml
- Added new workflow for image retagging, pod labelling to trigger deployment to test & prod env.
Tested in Openshift sandbox env.
=> Added new workflow for image retagging and pod labelling

src/frontend/citizen-portal/src/app/components/dispute-ticket-summary/dispute-ticket-summary.component.html, src/frontend/citizen-portal/src/scss/overrides/typography.scss
=>  Fix issue of Additional details header being shown in first page

src/backend/TrafficCourtsApi/citizen-api-test/Features/ApiResponseTest.cs
=> skip failing test for now

src/frontend/citizen-portal/Dockerfile
- This PR updates the nginx version form 1.18 to 1.20. 
=> Update nginx from 1.18 to 1.20

src/frontend/citizen-portal/Dockerfile
- move yarn config command up
- changed node from 14.17 to 14.18
=> move yarn config cmd and bump node to 14.18

src/frontend/citizen-portal/Dockerfile
- increase node memory limit to avoid error 137 OOM
=> increase node memory limit to 4GB

src/backend/TrafficCourts/Citizen.Service/Configuration/FormRecognizerConfigurationOptions.cs, src/backend/TrafficCourts/Citizen.Service/Controllers/TicketsController.cs, src/backend/TrafficCourts/Citizen.Service/Features/Tickets/Analyse.cs, src/backend/TrafficCourts/Citizen.Service/Models/ViolationTicket.cs, src/backend/TrafficCourts/Citizen.Service/Program.cs, src/backend/TrafficCourts/Citizen.Service/TrafficCourts.Citizen.Service.csproj, src/backend/TrafficCourts/Citizen.Service/appsettings.Development.json, src/backend/TrafficCourts/Citizen.Service/appsettings.json
[TCVP-945](https://justice.gov.bc.ca/jira/browse/TCVP-945)
Added an /analyse endpoint that accepts an image file, submits the image to Azure FormRecognizer, and returns a JSON object of the extracted text.
`curl --location --request POST 'https://localhost:7005/analyse' --form 'image=@"/C:/ticket_2022-01-05_122353.png"'`
`{
"violationTicket": {
"confidence": 0.919,
"fields": [
{
"name": "Address",
"value": "1234 CROQUET AVE",
"confidence": 0.95,
"type": "String",
"boundingBoxes": [
{
"points": [
{
"x": 137,
"y": 512
},
{
"x": 671,
"y": 512
},
{
"x": 671,
"y": 565
},
{
"x": 137,
"y": 565
}
]
}
]
},
...`
Please describe the tests that you ran to verify your …
=> Added /analyse endpoint for FormRecognizer OCR

src/backend/TrafficCourts/Citizen.Service/TrafficCourts.Citizen.Service.csproj
- add missing nuget packages that got dropped in merge conflict
=> Add missing package references lost in merge conflict

src/backend/TrafficCourts/Citizen.Service/Configuration/CitizenServiceConfiguration.cs, src/backend/TrafficCourts/Citizen.Service/Configuration/ConfigurationExtensions.cs, src/backend/TrafficCourts/Citizen.Service/Configuration/EnvironmentVariablesConfigurationProvider.cs, src/backend/TrafficCourts/Citizen.Service/Configuration/EnvironmentVariablesConfigurationSource.cs, src/backend/TrafficCourts/Citizen.Service/Configuration/FormRecognizerConfigurationOptions.cs, src/backend/TrafficCourts/Citizen.Service/Configuration/ITicketSearchServiceConfiguration.cs, src/backend/TrafficCourts/Citizen.Service/Configuration/TicketSearchServiceConfigurationProperties.cs, src/backend/TrafficCourts/Citizen.Service/Controllers/DisputeController.cs, src/backend/TrafficCourts/Citizen.Service/Controllers/TicketsController.cs, src/backend/TrafficCourts/Citizen.Service/Features/Tickets/Search.cs, src/backend/TrafficCourts/Citizen.Service/Models/Search/TicketSearchResult.cs, src/backend/TrafficCourts/Citizen.Service/Program.cs, src/backend/TrafficCourts/Citizen.Service/TrafficCourts.Citizen.Service.csproj, src/backend/TrafficCourts/Messaging/Configuration/IMassTransitConfiguration.cs, src/backend/TrafficCourts/Messaging/Configuration/IRabbitMQConfiguration.cs
- Add configuration validation, simplify app configuration
=> Update configuration and application setup

src/backend/TrafficCourts/TrafficCourts.Ticket.Search.Service/Program.cs, src/backend/TrafficCourts/TrafficCourts.Ticket.Search.Service/Startup.cs
- Add call to configure logging in ticket search service.
=> Add configuring logging and splunk

src/backend/TrafficCourts/Citizen.Service/Configuration/TicketSearchServiceConfigurationProperties.cs, src/backend/TrafficCourts/Citizen.Service/Program.cs, src/backend/TrafficCourts/Citizen.Service/Startup.cs, src/backend/TrafficCourts/Citizen.Service/appsettings.Development.json
- Add ability to enabled a secure channel
- 
=> Add support for configurable ticket search credentials

src/backend/TrafficCourts/TrafficCourts.Ticket.Search.Service/Dockerfile.rhel8
=> fix working directory

src/frontend/citizen-portal/package.json, src/frontend/citizen-portal/src/app/app.module.ts, src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.ts, src/frontend/citizen-portal/src/app/components/dispute-submit-success/dispute-submit-success.component.html, src/frontend/citizen-portal/src/app/components/dispute-submit-success/dispute-submit-success.component.ts, src/frontend/citizen-portal/src/app/components/dispute-summary/dispute-summary.component.html, src/frontend/citizen-portal/src/app/components/dispute-ticket-summary/dispute-ticket-summary.component.html, src/frontend/citizen-portal/src/app/components/dispute-ticket-summary/dispute-ticket-summary.component.scss, src/frontend/citizen-portal/src/app/components/find-ticket/find-ticket.component.html, src/frontend/citizen-portal/src/app/components/find-ticket/find-ticket.component.scss, src/frontend/citizen-portal/src/app/components/find-ticket/find-ticket.component.spec.ts, src/frontend/citizen-portal/src/app/components/stepper/step-additional/step-additional.component.html, src/frontend/citizen-portal/src/app/components/stepper/step-additional/step-additional.component.ts, src/frontend/citizen-portal/src/app/components/stepper/step-count/step-count.component.html, src/frontend/citizen-portal/src/app/shared/models/ticketDisputeView.model.ts
=> added 24 timer and disable upload ticket button

src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.html, src/frontend/citizen-portal/src/app/components/dispute-summary/dispute-summary.component.html, src/frontend/citizen-portal/src/app/components/find-ticket/find-ticket.component.html, src/frontend/citizen-portal/src/app/components/stepper/step-additional/step-additional.component.html, src/frontend/citizen-portal/src/app/components/stepper/step-count/step-count.component.html, src/frontend/citizen-portal/src/app/components/stepper/step-disputant/step-disputant.component.html, src/frontend/citizen-portal/src/app/services/dispute-resource.service.ts, src/frontend/citizen-portal/src/app/shared/enums/ticket-type.enum.ts
- TCVP-976 
- TCVP-967 
- TCVP-969
=> updated text changes according to wireframes

src/backend/TrafficCourts/Citizen.Service/Controllers/DisputeController.cs, src/backend/TrafficCourts/Citizen.Service/Controllers/TicketsController.cs, src/backend/TrafficCourts/Citizen.Service/Features/Tickets/Search.cs, src/backend/TrafficCourts/Citizen.Service/Models/Deprecated/Deprecated.cs, src/backend/TrafficCourts/Citizen.Service/Models/Search/TicketSearchResult.cs, src/backend/TrafficCourts/Citizen.Service/Program.cs, src/backend/TrafficCourts/Citizen.Service/Startup.cs, src/backend/TrafficCourts/Citizen.Service/TrafficCourts.Citizen.Service.csproj, src/backend/TrafficCourts/Protos/ticket-service.proto, src/backend/TrafficCourts/Test/Citizen.Service/Validators/Rules/FieldMatchesRegexRuleTest.cs
Add depreciated apis for backward compatibility temporarily.
=> Add deprecated apis

src/backend/TrafficCourts/Citizen.Service/Models/Tickets/OcrViolationTicket.cs, src/backend/TrafficCourts/Citizen.Service/Validators/FormRecognizerValidator.cs, src/backend/TrafficCourts/Citizen.Service/Validators/Rules/OnlyMCAIsSelectedRule.cs, src/backend/TrafficCourts/Citizen.Service/Validators/Rules/ViolationDateLT30Rule.cs, src/backend/TrafficCourts/Citizen.Service/Validators/ValidationMessages.cs, src/backend/TrafficCourts/Test/Citizen.Service/Validators/Rules/OnlyMCAIsSelectedRuleTest.cs, src/backend/TrafficCourts/Test/Citizen.Service/Validators/Rules/ViolationDateLT30RuleTest.cs
[TCVP-933](https://justice.gov.bc.ca/jira/browse/TCVP-933)
Added 4th validation rule (Violation Date must be valid and not greater than 30 days ago)
Added xUnit tests
dotnet test
=> TCVP-933 Added ViolationDateLT30Rulevalidation rule

src/backend/TrafficCourts/Citizen.Service/Models/Tickets/OcrViolationTicket.cs, src/backend/TrafficCourts/Citizen.Service/Services/FormRecognizerService.cs
[TCVP-945](https://justice.gov.bc.ca/jira/browse/TCVP-945) Added Hearing Location to extracted results
dotnet test
=> TCVP-945 Added Hearing Location to extracted results

src/backend/TrafficCourts/Citizen.Service/Controllers/TicketsController.cs, src/backend/TrafficCourts/Citizen.Service/Features/Tickets/AnalyseHandler.cs, src/backend/TrafficCourts/Citizen.Service/Models/Tickets/OcrViolationTicket.cs, src/backend/TrafficCourts/Citizen.Service/Services/FormRecognizerService.cs, src/backend/TrafficCourts/Test/Citizen.Service/Controllers/TicketsControllerTests.cs, src/backend/TrafficCourts/Test/Citizen.Service/Validators/Rules/ViolationDateLT30RuleTest.cs
Omnisharp code smell fixes.
Added omnisharp.json to project so code analyzers are consistent across developers.
dotnet test
=> Omnisharp code smell fixes

src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.ts, src/frontend/citizen-portal/src/app/components/stepper/step-additional/step-additional.component.html, src/frontend/citizen-portal/src/app/components/stepper/step-count/step-count.component.html, src/frontend/citizen-portal/src/app/components/stepper/step-count/step-count.component.scss, src/frontend/citizen-portal/src/app/components/stepper/step-count/step-count.component.ts, src/frontend/citizen-portal/src/app/components/stepper/step-disputant/step-disputant.component.html, src/frontend/citizen-portal/src/app/services/dispute-form-state.service.ts
=> updated count review with new toggle

src/frontend/citizen-portal/src/app/components/find-ticket/find-ticket.component.html, src/frontend/citizen-portal/src/app/components/find-ticket/find-ticket.component.scss, src/frontend/citizen-portal/src/app/services/dispute-resource.service.ts, src/frontend/citizen-portal/src/app/shared/components/resolution-header/resolution-header.component.html
=> updated landing page and rearranged items

src/frontend/citizen-portal/nginx.conf.template, src/frontend/citizen-portal/src/app/components/find-ticket/find-ticket.component.ts
Fixed nginx.conf to allow larger file upload sizes.
docker-compose up -d --build
I can now upload a sample ticket image via the UI and have OCR API return successfully.
=> Fixed nginx max file upload size

src/backend/TrafficCourts/Citizen.Service/Models/Tickets/OcrViolationTicket.cs, src/backend/TrafficCourts/Citizen.Service/Validators/FormRecognizerValidator.cs, src/backend/TrafficCourts/Citizen.Service/Validators/Rules/DriversLicenceValidRule.cs, src/backend/TrafficCourts/Citizen.Service/Validators/Rules/FieldIsRequiredRule.cs, src/backend/TrafficCourts/Citizen.Service/Validators/Rules/FieldMatchesRegexRule.cs, src/backend/TrafficCourts/Citizen.Service/Validators/Rules/OnlyMVAIsSelectedRule.cs, src/backend/TrafficCourts/Citizen.Service/Validators/Rules/TicketAmountValidRule.cs, src/backend/TrafficCourts/Citizen.Service/Validators/Rules/ViolationDateLT30Rule.cs, src/backend/TrafficCourts/Citizen.Service/Validators/ValidationMessages.cs, src/backend/TrafficCourts/Test/Citizen.Service/Validators/Rules/DriversLicenceValidRuleTest.cs, src/backend/TrafficCourts/Test/Citizen.Service/Validators/Rules/FieldMatchesRegexRuleTest.cs, src/backend/TrafficCourts/Test/Citizen.Service/Validators/Rules/TicketAmountValidRuleTest.cs
[TCVP-963](https://justice.gov.bc.ca/jira/browse/TCVP-963)
Added validation rules to ensure the Ticket Amount is a float, produces a validation message on the individual field otherwise.
Added xUnit tests
dotnet test
=> TCVP-963 added currency validation rules

src/backend/TrafficCourts/Citizen.Service/Controllers/TicketsController.cs
Set the size limit of the uploaded ticket image/file to scan.  The free tier of MS Azure Form Recognizer only permits 6MB, but the full version permits sizes up to 50MB.
TCO, however, limits the upload size to 10MB, this is **1024** x **1024** x **10** = **10485760** bytes.
=> Set upload size limit to 10MB

src/backend/dotnet-counters/Dockerfile, src/backend/dotnet-counters/Dockerfile.rhel8, src/backend/dotnet-counters/README.md
- add docker files for dotnet-counter side car (future monitoring). Does not impact anything in our app.
=> add docker file specs for creating dotnet-counter images

src/frontend/citizen-portal/angular.json, src/frontend/citizen-portal/proxy.conf.json
=> Fixed proxy.conf.json to reference the API running in docker

src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.ts, src/frontend/citizen-portal/src/app/components/dispute-ticket-summary/dispute-ticket-summary.component.html, src/frontend/citizen-portal/src/app/components/shell-ticket/shell-ticket.component.html, src/frontend/citizen-portal/src/app/components/shell-ticket/shell-ticket.component.ts, src/frontend/citizen-portal/src/app/components/stepper/step-additional/step-additional.component.html, src/frontend/citizen-portal/src/app/components/stepper/step-additional/step-additional.component.ts, src/frontend/citizen-portal/src/app/components/stepper/step-count/step-count.component.html
=> updated count review and additional information components

src/backend/TrafficCourts/TrafficCourts.Ticket.Search.Service/Authentication/AuthenticationClient.cs
- Failure trying to call ticket service. Getting 500 error due to wrong authentication header format
=> fix rsi authentication, remove Bearer before token

src/backend/TrafficCourts/TrafficCourts.Ticket.Search.Service/Authentication/AuthenticationClient.cs, src/backend/TrafficCourts/TrafficCourts.Ticket.Search.Service/Services/AccessTokenUpdateWorker.cs, src/backend/TrafficCourts/TrafficCourts.Ticket.Search.Service/Startup.cs
- update ticket search token refresh
- update ticket search access to token logging
=> Add token refresh background service, improve logging

src/backend/TrafficCourts/Citizen.Service/appsettings.json, src/backend/TrafficCourts/TrafficCourts.Ticket.Search.Service/Dockerfile.rhel8, src/backend/TrafficCourts/TrafficCourts.Ticket.Search.Service/appsettings.json
- fixes the runtime image for the ticket search service
- reduces the default logging level for framework code
=> Fix docker and default logging levels

.github/labeler.yml
- removes ticket search from labeller due to old code removal
=> remove ticket search

src/backend/TrafficCourts/Citizen.Service/Validators/FormRecognizerValidator.cs
Refactored a couple of variables to align with the current `.editorconfig` settings.
dotnet test
=> Refactored variable names per new .editorConfig settings

tools/ticket-generator/Dockerfile
Updated Dockerfile so it doesn't run as root
=> Updated ticket-gen Dockerfile to not run as root

src/frontend/citizen-portal/src/app/components/count-item-summary/count-item-summary.component.html, src/frontend/citizen-portal/src/app/components/find-ticket/find-ticket.component.html, src/frontend/citizen-portal/src/app/components/shell-ticket/shell-ticket.component.ts, src/frontend/citizen-portal/src/app/components/stepper/step-count/step-count.component.html, src/frontend/citizen-portal/src/app/components/stepper/step-disputant/step-disputant.component.html, src/frontend/citizen-portal/src/app/components/stepper/step-disputant/step-disputant.component.ts, src/frontend/citizen-portal/src/app/shared/components/resolution-footer/resolution-footer.component.html
=> worked on bugs

src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.html, src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.ts, src/frontend/citizen-portal/src/app/components/dispute-summary/dispute-summary.component.ts, src/frontend/citizen-portal/src/app/components/find-ticket/find-ticket.component.scss, src/frontend/citizen-portal/src/app/components/shell-ticket/shell-ticket.component.html, src/frontend/citizen-portal/src/app/components/shell-ticket/shell-ticket.component.ts, src/frontend/citizen-portal/src/app/components/stepper/step-count/step-count.component.html, src/frontend/citizen-portal/src/app/components/stepper/step-count/step-count.component.ts, src/frontend/citizen-portal/src/app/services/dispute-resource.service.ts, src/frontend/citizen-portal/src/app/services/dispute.service.ts, src/frontend/citizen-portal/src/app/shared/models/ticketDisputeView.model.ts
=> worked on hand written create ticket

src/frontend/citizen-portal/src/app/components/count-item-dispute-summary/count-item-dispute-summary.component.html, src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.ts, src/frontend/citizen-portal/src/app/components/dispute-ticket-summary/dispute-ticket-summary.component.html, src/frontend/citizen-portal/src/app/components/shell-ticket/shell-ticket.component.html, src/frontend/citizen-portal/src/app/components/shell-ticket/shell-ticket.component.ts, src/frontend/citizen-portal/src/app/components/stepper/step-additional/step-additional.component.html, src/frontend/citizen-portal/src/app/components/stepper/step-additional/step-additional.component.ts, src/frontend/citizen-portal/src/app/components/stepper/step-count/step-count.component.html, src/frontend/citizen-portal/src/app/components/stepper/step-count/step-count.component.scss
=> worked on court notification

src/frontend/staff-portal/Dockerfile, src/frontend/staff-portal/e2e/src/app.e2e-spec.ts, src/frontend/staff-portal/karma.conf.js, src/frontend/staff-portal/package.json
Fixed some copy n' paste errors in staff-portal
=> Update staff-portal Dockerfile, fixed some copy n' paste errors

docker-compose.yml, src/backend/README.md, src/backend/oracle-data-interface/Dockerfile, src/backend/oracle-data-interface/pom.xml, src/backend/oracle-data-interface/src/main/resources/logback-spring.xml
Added Splunk to docker-compose.
Tested by bringing up all apps in docker-compose, hitting the oraface container and seeing logging appear in the new splunk container.
=> Added Splunk to docker-compose

src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/Services/ArcFileService.cs
- ARC expects line endings to be unix line endings, '\n'. this forces the output to always use unix line endings regardless of runtime environment.
=> Ensure files are created with unix line endings

src/backend/TrafficCourts/Citizen.Service/TrafficCourts.Citizen.Service.csproj, src/backend/TrafficCourts/Test/TrafficCourts.Test.csproj, src/backend/TrafficCourts/TrafficCourts.Ticket.Search.Service/TrafficCourts.Ticket.Search.Service.csproj
- Updates some of the nuget packages
=> Package updates

src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.ts, src/frontend/citizen-portal/src/app/components/dispute-ticket-summary/dispute-ticket-summary.component.html, src/frontend/citizen-portal/src/app/components/find-ticket/find-ticket.component.html, src/frontend/citizen-portal/src/app/components/find-ticket/find-ticket.component.scss, src/frontend/citizen-portal/src/app/components/find-ticket/find-ticket.component.spec.ts, src/frontend/citizen-portal/src/app/components/find-ticket/find-ticket.component.ts, src/frontend/citizen-portal/src/app/services/dispute-form-state.service.ts, src/frontend/citizen-portal/src/app/shared/components/resolution-footer/resolution-footer.component.html
=> worked on landing page validations

src/backend/TrafficCourts/Citizen.Service/Startup.cs, src/backend/TrafficCourts/TrafficCourts.Common.Test/Features/FilePersistence/MinioFilePersistenceServiceTest.cs, src/backend/TrafficCourts/TrafficCourts.Ticket.Search.Service/Features/Search/Mock/EmbeddedMockDataProvider.cs, src/backend/TrafficCourts/TrafficCourts.Ticket.Search.Service/Features/Search/Mock/FileMockDataProvider.cs, src/backend/TrafficCourts/TrafficCourts.Ticket.Search.Service/Features/Search/Mock/MockTicketSearchService.cs, src/backend/TrafficCourts/TrafficCourts.Ticket.Search.Service/Features/Search/Rsi/RoadSafetyTicketSearchService.cs, src/backend/TrafficCourts/TrafficCourts.Ticket.Search.Service/Services/AccessTokenUpdateWorker.cs, src/backend/TrafficCourts/TrafficCourts.Ticket.Search.Service/Services/TicketSearchService.cs, src/backend/TrafficCourts/TrafficCourts.Ticket.Search.Service/Startup.cs
- Adds telemetry calls to ticket search service
=> Add telemetry points in ticket search

src/backend/TrafficCourts/Common/Configuration/RedisConfigurationProperties.cs, src/backend/TrafficCourts/Common/Configuration/TrafficCourtsConfiguration.cs, src/backend/TrafficCourts/Common/Diagnostics/MeterExtension.cs, src/backend/TrafficCourts/Common/Features/FilePersistence/FilePersistenceService.cs, src/backend/TrafficCourts/Common/RecyclableMemoryStreamManager.cs, src/backend/TrafficCourts/TrafficCourts.Common.Test/BaseAddressTest.cs, src/backend/TrafficCourts/TrafficCourts.Common.Test/ClockExtensionsTest.cs, src/backend/TrafficCourts/TrafficCourts.Common.Test/Configuration/ConfigurationTest.cs, src/backend/TrafficCourts/TrafficCourts.Common.Test/DependencyInjectionTest.cs, src/backend/TrafficCourts/TrafficCourts.Common.Test/Diagnostics/MeterExtensionTest.cs, src/backend/TrafficCourts/TrafficCourts.Common.Test/Features/FilePersistence/ExtensionsTest.cs, src/backend/TrafficCourts/TrafficCourts.Common.Test/Features/FilePersistence/MinioFilePersistenceServiceTest.cs, src/backend/TrafficCourts/TrafficCourts.Common.Test/RecyclableMemoryStreamManagerTest.cs, src/backend/TrafficCourts/TrafficCourts.Common.Test/TrafficCourts.Common.Test.csproj, src/backend/TrafficCourts/TrafficCourts.Ticket.Search.Service/Startup.cs
- Adds additional unit tests for common library functions
=> Add unit tests for Common library

.docker/docker-compose.jaeger.yml, .docker/docker-compose.seq.yml, .docker/docker-compose.splunk.yml, README.md, docker-compose.yml
- pulls jaeger, seq and splunk to separate compose files
=> Pull jaeger, seq and splunk into separate compose files

src/frontend/citizen-portal/src/app/components/find-ticket/find-ticket.component.html, src/frontend/citizen-portal/src/app/components/find-ticket/find-ticket.component.ts, src/frontend/staff-portal/src/app/components/ticket-page/ticket-page.component.html, src/frontend/staff-portal/src/app/components/ticket-page/ticket-page.component.scss, src/frontend/staff-portal/src/app/components/ticket-page/ticket-page.component.ts, src/frontend/staff-portal/src/app/shared/components/footer/footer.component.scss, src/frontend/staff-portal/src/index.html
- DGTL-1125, TCVP-1030
- updated the styling according to wire frames for staff portal and added invalid error notifications in the front end.
=> TCVP-1030 - worked on staff portal searching and error scenarios

src/backend/TrafficCourts/Staff.Service/Authentication/Claims.cs, src/backend/TrafficCourts/Staff.Service/Authentication/ConfigureJwtBearerOptions.cs, src/backend/TrafficCourts/Staff.Service/Authentication/Roles.cs, src/backend/TrafficCourts/Staff.Service/Program.cs, src/backend/TrafficCourts/Staff.Service/TrafficCourts.Staff.Service.csproj
- Add authorization requirement to swagger spec
- Add XML document documentation generation on swagger
- Add default authorization on controllers
- Add transform to extract "realm_access" roles into ASP.NET role claims
=> TCVP-1246 add authorization to api, swagger

src/frontend/citizen-portal/package.json, src/frontend/citizen-portal/src/app/components/shell-ticket/shell-ticket.component.ts
- TCVP-1133 fix OCR date returned always 1 day behind
- [*] Bug fix (non-breaking change which fixes an issue)
- [*] No
- [*] My code follows the style guidelines of this project
- [*] I have performed a self-review of my own code
- [*] I have made corresponding changes to the documentation
- [*] New and existing unit tests pass locally with my changes
=> TCVP-1133 fix OCR date returned always 1 day behind

src/frontend/staff-portal/src/app/app.module.ts, src/frontend/staff-portal/src/app/components/ticket-info/ticket-info.component.html, src/frontend/staff-portal/src/app/components/ticket-info/ticket-info.component.scss, src/frontend/staff-portal/src/app/components/ticket-info/ticket-info.component.spec.ts, src/frontend/staff-portal/src/app/components/ticket-info/ticket-info.component.ts, src/frontend/staff-portal/src/app/components/ticket-page/ticket-page.component.html, src/frontend/staff-portal/src/app/components/ticket-page/ticket-page.component.ts
- {TCVP-1112} worked on contact details component to the staff portal 
=> TCVP-1112 added contact details component to staff portal

src/backend/TrafficCourts/Staff.Service/Controllers/DisputeController.cs, src/backend/TrafficCourts/Staff.Service/OpenAPIs/OracleDataAPI/v1_0/OracleDataApi.v1_0.json, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/error/ControllerAdvisor.java
[TCVP-1210](https://justice.gov.bc.ca/jira/browse/TCVP-1210?)
- Added html error codes 404 and 500 to the oracle-data-api project.
- Updated OpenApi spec
- Exposed error codes in staff-api client
manual testing
=> TCVP-1210 Added Http Error codes 404 and 500 to oracle-data-api

src/backend/TrafficCourts/Staff.Service/Dockerfile.rhel8
Adds dockerfile to build staff API for OpenShift
=> Add docker file for building staff-api

src/backend/oracle-data-api/pom.xml, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeController.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/error/ControllerAdvisor.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/error/ErrorResponse.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/Dispute.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeService.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeControllerTest.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/util/RandomUtil.java
- Added validation to Rejected Reason - max length of 256 characters.
- Improved returned error (ReponseEntity) when exceptions are thrown, ie.
```
{
"status": 405,
"message": "Validation Failed",
"details": [
"rejectDispute.rejectedReason: size must be between 1 and 256"
]
}
```
mvn verify
=> TCVP-1058 Added 405 error code rules and junit tests

src/frontend/citizen-portal/src/app/components/shell-ticket/shell-ticket.component.html
=> TCVP-1256 OCR screen - violation time must be 24 hour clock

src/frontend/citizen-portal/.vscode/launch.json, src/frontend/citizen-portal/.vscode/tasks.json, src/frontend/citizen-portal/angular.json, src/frontend/citizen-portal/package.json
- adds `debug` task in package.json to support debugging
- adds `debug` configuration in angular.json to support debugging
- adds launch and task files for VS Code to build and launch Edge to debug front end code
=> Add configuration to enable debugging Angular from VS Code

src/frontend/citizen-portal/package.json, src/frontend/citizen-portal/src/app/components/find-ticket/find-ticket.component.ts, src/frontend/citizen-portal/src/app/components/scan-ticket/scan-ticket.component.html, src/frontend/citizen-portal/src/app/components/scan-ticket/scan-ticket.component.ts, src/frontend/citizen-portal/src/app/components/shell-ticket/shell-ticket.component.html, src/frontend/citizen-portal/src/app/components/shell-ticket/shell-ticket.component.ts, src/frontend/citizen-portal/src/app/shared/models/shellTicketView.model.ts
- TCVP-1133
- change datepicker to input
- remove moment
=> remove moment and change datepicker to input

docker-compose.yml, src/backend/TrafficCourts/Messaging/MessageContracts/DisputeApproved.cs, src/backend/TrafficCourts/Messaging/MessageContracts/DisputeCancelled.cs, src/backend/TrafficCourts/Staff.Service/Configuration/OracleDataApiConfiguration.cs, src/backend/TrafficCourts/Staff.Service/Mappers/Mapper.cs, src/backend/TrafficCourts/Staff.Service/Program.cs, src/backend/TrafficCourts/Staff.Service/Services/DisputeService.cs, src/backend/TrafficCourts/Staff.Service/TrafficCourts.Staff.Service.csproj
- Added MassTransit (RabbitMQ) to staff-api project
- Converted DisputeApproved message contract to a class from an interface
- Added DisputeCancelled message contract
- Added MassTransit events to reject/cancel/submit endpoints
dotnet test
=> TCVP-1058 Add MassTransit to staff-api

src/backend/TrafficCourts/Citizen.Service/Models/Dispute/TicketCount.cs, src/backend/TrafficCourts/Citizen.Service/Models/Dispute/TicketDispute.cs, src/backend/TrafficCourts/Citizen.Service/Services/IRedisCacheService.cs, src/backend/TrafficCourts/Citizen.Service/Services/Impl/RedisCacheService.cs, src/backend/TrafficCourts/Citizen.Service/Services/Tickets/Search/Rsi/RoadSafetyTicketSearchService.cs, src/backend/TrafficCourts/Citizen.Service/Services/Tickets/Search/TicketSearchErrorException.cs, src/backend/TrafficCourts/Citizen.Service/Startup.cs, src/backend/TrafficCourts/Staff.Service/Program.cs, src/backend/TrafficCourts/Test/Citizen.Service/Features/Tickets/SearchRequestTest.cs, src/backend/TrafficCourts/Test/Workflow.Service/Services/EmailSenderServerTests.cs, src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/Models/ArcFileRecord.cs, src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/Models/TcoDisputeTicket.cs, src/backend/TrafficCourts/TrafficCourts.Messaging.Test/TrafficCourts.Messaging.Test.csproj, src/backend/TrafficCourts/TrafficCourts.Messaging.Test/UnitTest1.cs, src/backend/TrafficCourts/Workflow.Service/appsettings.json
- just cleans up build warnings in the .NET backends
=> Clean up build warnings around null, unused values

src/frontend/staff-portal/src/app/auth/auth-config.module.ts, src/frontend/staff-portal/src/assets/config/oidc.json
=> use window.location.origin for redirectUrl

src/backend/TrafficCourts/Citizen.Service/Features/Tickets/AnalyseHandler.cs
Added a comment placeholder for [JIRA-1295](https://justice.gov.bc.ca/jira/browse/TCVP-1295)
=> TCVP-1295 created backlog TODO task for file storage leak

src/backend/TrafficCourts/Citizen.Service/Startup.cs, src/backend/TrafficCourts/Common/Configuration/ConfigurationManagerExtensions.cs, src/backend/TrafficCourts/Staff.Service/Program.cs, src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/Program.cs, src/backend/TrafficCourts/Workflow.Service/Program.cs
- Adds configuration from vault secrets, if available.
- Will support deployment on OpenShift with injected secrets from Vault
=> Load configuration from Vault secrets ini format files.

src/backend/TrafficCourts/Citizen.Service/Configuration/CitizenServiceConfiguration.cs, src/backend/TrafficCourts/Citizen.Service/Startup.cs, src/backend/TrafficCourts/Common/Configuration/ConfigurationManagerExtensions.cs, src/backend/TrafficCourts/Common/Configuration/IRedisConfiguration.cs, src/backend/TrafficCourts/Common/Configuration/RedisConfigurationProperties.cs, src/backend/TrafficCourts/Common/Configuration/RedisOptions.cs
- Do not require a connection to Redis during app startup
=> Adjust redis init code so it doesn't connect during startup

docker-compose.yml, src/frontend/citizen-portal/src/app/components/find-ticket/find-ticket.component.ts, src/frontend/citizen-portal/src/app/services/violation-ticket.service.ts, src/frontend/citizen-portal/src/app/shared/dialogs/image-ticket-not-found-dialog/image-ticket-not-found-dialog.component.html, src/frontend/staff-portal/src/app/app-routing.module.ts, src/frontend/staff-portal/src/app/app.module.ts, src/frontend/staff-portal/src/app/components/contact-info/contact-info.component.html, src/frontend/staff-portal/src/app/components/contact-info/contact-info.component.scss, src/frontend/staff-portal/src/app/components/contact-info/contact-info.component.spec.ts, src/frontend/staff-portal/src/app/components/contact-info/contact-info.component.ts, src/frontend/staff-portal/src/app/components/ticket-info/ticket-info.component.html, src/frontend/staff-portal/src/app/components/ticket-info/ticket-info.component.scss, src/frontend/staff-portal/src/app/components/ticket-info/ticket-info.component.ts, src/frontend/staff-portal/src/app/components/ticket-page/ticket-page.component.html, src/frontend/staff-portal/src/app/components/ticket-page/ticket-page.component.ts
=> added 3 error seenarios to the ocr

docker-compose.yml, src/frontend/citizen-portal/nginx.conf, src/frontend/staff-portal/nginx.conf
- docker-compose: change staff-portal to depend on staff-api
- docker build: remove `include` for api proxy pass because file included twice
=> Docker updates

src/frontend/citizen-portal/src/app/components/find-ticket/find-ticket.component.ts, src/frontend/citizen-portal/src/app/services/violation-ticket.service.ts, src/frontend/citizen-portal/src/app/shared/dialogs/image-ticket-not-found-dialog/image-ticket-not-found-dialog.component.html, src/frontend/citizen-portal/src/app/shared/dialogs/image-ticket-not-found-dialog/image-ticket-not-found-dialog.component.scss
- [TCVP-1030](https://justice.gov.bc.ca/jira/browse/TCVP-1030)
- code cleaning
=> TCVP-1030 Indicate to citizen OCR Error scenarios

src/frontend/citizen-portal/src/app/services/violation-ticket.service.ts, src/frontend/staff-portal/src/app/config/config.service.ts, src/frontend/staff-portal/src/app/core/core.module.ts, src/frontend/staff-portal/src/app/services/app-config.service.ts, src/frontend/staff-portal/src/app/shared/components/header/header.component.html, src/frontend/staff-portal/src/app/shared/components/header/header.component.scss
=> TCVP-1245 env and version header

src/frontend/citizen-portal/src/app/components/count-item-dispute-summary/count-item-dispute-summary.component.html, src/frontend/citizen-portal/src/app/components/count-item-summary/count-item-summary.component.html, src/frontend/citizen-portal/src/app/components/count-item-summary/count-item-summary.component.scss, src/frontend/citizen-portal/src/app/components/find-ticket/find-ticket.component.ts, src/frontend/citizen-portal/src/app/components/scan-ticket/scan-ticket.component.ts, src/frontend/citizen-portal/src/app/services/violation-ticket.service.ts
- TCVP-1276
- move position of the "count x" with style
- remove file in file input after upload
- add fall back condition when ocr errors occur
=> TCVP-1276 modifiy count items display & minor changes

src/backend/TrafficCourts/Citizen.Service/Features/Disputes/Create.cs, src/backend/TrafficCourts/Citizen.Service/Features/Tickets/AnalyseHandler.cs, src/backend/TrafficCourts/Citizen.Service/Services/IRedisCacheService.cs, src/backend/TrafficCourts/Citizen.Service/Services/Impl/RedisCacheService.cs, src/backend/TrafficCourts/Common/Features/FilePersistence/FilePersistenceService.cs, src/backend/TrafficCourts/Common/Features/FilePersistence/IFilePersistenceService.cs, src/backend/TrafficCourts/Common/Features/FilePersistence/InMemoryFilePersistenceService.cs, src/backend/TrafficCourts/Common/Features/FilePersistence/MinioFilePersistenceService.cs, src/backend/TrafficCourts/Common/Features/Mail/Model/MailTemplateCollection.cs, src/backend/TrafficCourts/Staff.Service/Mappers/Mapper.cs, src/backend/TrafficCourts/Test/Citizen.Service/Features/Disputes/CreateDisputeHandlerTest.cs, src/backend/TrafficCourts/Workflow.Service/Features/Mail/SendEmailConsumer.cs
- TCVP-1295 - when an uploaded file fails or user abandons dispute submission, the image uploaded to the file persistence is left as an orphan.  Moved the file upload to Redis, and only upload to file persistence, when the dispute is submitted.
- Fix minor issue to e-mail templates, where the ticket number population was against the wrong field.
Manual verification
- [N] No
=> TCVP-1295 fix file storage leak

src/backend/TrafficCourts/Citizen.Service/Models/Dispute/NoticeOfDispute.cs, src/backend/TrafficCourts/Messaging/MessageContracts/DisputeApproved.cs, src/backend/TrafficCourts/Messaging/MessageContracts/SubmitNoticeOfDispute.cs, src/backend/TrafficCourts/Staff.Service/Mappers/Mapper.cs, src/backend/TrafficCourts/Staff.Service/OpenAPIs/OracleDataAPI/v1_0/OracleDataApi.v1_0.json, src/backend/TrafficCourts/Staff.Service/Services/DisputeService.cs, src/backend/TrafficCourts/Test/Citizen.Service/Mappings/NoticeOfDisputeToMessageContractMappingTests.cs, src/backend/TrafficCourts/TrafficCourts.Staff.Service.Test/Services/DisputeServiceTest.cs, src/backend/TrafficCourts/Workflow.Service/Models/NoticeOfDispute.cs, src/backend/TrafficCourts/Workflow.Service/Models/TcoDisputeTicket.cs, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/Dispute.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/LegalRepresentation.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/ViolationTicket.java
- [TCVP-1339](https://justice.gov.bc.ca/jira/browse/TCVP-1339)
- Added new fields to the oracle-data-api and workflow-service.
- Corrected some mappings for staff-api.
=> TCVP-1339 fix mapping for new fields

src/frontend/citizen-portal/src/app/components/count-item-dispute-summary/count-item-dispute-summary.component.html, src/frontend/citizen-portal/src/app/components/dispute-submit-success/dispute-submit-success.component.html, src/frontend/citizen-portal/src/app/components/dispute-submit-success/dispute-submit-success.component.ts, src/frontend/citizen-portal/src/app/components/dispute-ticket-stepper/dispute-ticket-stepper.component.html, src/frontend/citizen-portal/src/app/components/dispute-ticket-stepper/dispute-ticket-stepper.component.ts, src/frontend/citizen-portal/src/app/components/dispute-ticket-summary/dispute-ticket-summary.component.html, src/frontend/citizen-portal/src/app/components/dispute-ticket-summary/dispute-ticket-summary.component.spec.ts, src/frontend/citizen-portal/src/app/components/dispute-ticket-summary/dispute-ticket-summary.component.ts, src/frontend/citizen-portal/src/app/services/notice-of-dispute.service.ts, src/frontend/citizen-portal/src/app/services/violation-ticket.service.ts
=> TCVP-1244, TCVP-1232 update count resolution request section

src/frontend/citizen-portal/src/app/components/dispute-submit-success/dispute-submit-success.component.html, src/frontend/citizen-portal/src/app/components/dispute-submit-success/dispute-submit-success.component.ts, src/frontend/citizen-portal/src/app/components/initiate-resolution/initiate-resolution.component.html, src/frontend/citizen-portal/src/app/components/initiate-resolution/initiate-resolution.component.ts, src/frontend/citizen-portal/src/app/shared/pipes/ticket-type.pipe.ts
- TCVP-1251
- bug fix on ticket type pipe
=> TCVP-1251 Part 2 & bug fix

src/frontend/staff-portal/src/app/app.module.ts, src/frontend/staff-portal/src/app/components/ticket-info/ticket-info.component.html, src/frontend/staff-portal/src/app/components/ticket-info/ticket-info.component.ts, src/frontend/staff-portal/src/app/components/ticket-page/ticket-page.component.ts, src/frontend/staff-portal/src/app/components/ticket-status/ticket-status.component.html, src/frontend/staff-portal/src/app/components/ticket-status/ticket-status.component.scss, src/frontend/staff-portal/src/app/components/ticket-status/ticket-status.component.spec.ts, src/frontend/staff-portal/src/app/components/ticket-status/ticket-status.component.ts
[TCVP-1208](https://justice.gov.bc.ca/jira/browse/TCVP-1208)
Added a new ticket-status component to the staff-portal detail screen.
This attempts to follow the wireframe as closely as possible.
No tests since "yarn test" is broken for this project.
=> TCVP-1208 created ticket-status component

src/frontend/citizen-portal/src/app/components/count-item-dispute-summary/count-item-dispute-summary.component.html, src/frontend/citizen-portal/src/app/components/initiate-resolution/initiate-resolution.component.ts, src/frontend/citizen-portal/src/app/services/violation-ticket.service.ts
- TCVP-1159
- TCVP-1203
- TCVP-1337
=> TCVP-1159, TCVP-1203, TCVP-1337 bug fix

src/frontend/citizen-portal/src/app/api/api/disputes.service.ts, src/frontend/citizen-portal/src/app/api/client-api.json, src/frontend/citizen-portal/src/app/api/model/noticeOfDispute.model.ts, src/frontend/citizen-portal/src/app/components/dispute-ticket-stepper/dispute-ticket-stepper.component.ts, src/frontend/citizen-portal/src/app/components/scan-ticket/scan-ticket.component.html, src/frontend/citizen-portal/src/app/components/scan-ticket/scan-ticket.component.ts, src/frontend/citizen-portal/src/app/services/violation-ticket.service.ts
=> TCVP-1311 update for storing citizen reaponses

src/frontend/citizen-portal/src/app/components/dispute-submit-success/dispute-submit-success.component.html
=> TCVP-1345 Request submitted screen - business rules for notices

src/frontend/citizen-portal/src/app/components/initiate-resolution/initiate-resolution.component.ts, src/frontend/citizen-portal/src/app/components/scan-ticket/scan-ticket.component.html, src/frontend/citizen-portal/src/app/components/scan-ticket/scan-ticket.component.ts, src/frontend/citizen-portal/src/app/services/violation-ticket.service.ts
=> TCVP-1311 bug fix of scan ticket

src/backend/TrafficCourts/Citizen.Service/Services/Tickets/Search/TicketSearchService.cs
- fixes wrong empty string check - was logging message when data was ok.
=> Fix if statement expression error

.gitops/charts/traffic-court-online/charts/citizen-api/values.yaml, .gitops/charts/traffic-court-online/charts/oracle-data-api/values.yaml, .gitops/charts/traffic-court-online/charts/staff-api/values.yaml, .gitops/charts/traffic-court-online/charts/workflow-service/templates/deployment.yaml, .gitops/charts/traffic-court-online/charts/workflow-service/values.yaml
- fixes default jaeger endpoint config
- fixes workflow service config for oracle data api
=> Helm chart updates

src/backend/TrafficCourts/Workflow.Service/Consumers/DisputeApprovedConsumer.cs, src/backend/TrafficCourts/Workflow.Service/Consumers/SubmitDisputeConsumer.cs
- Added exception handling for message consumers and updated log messages.
=> Update exception handling in message consumers

src/backend/TrafficCourts/Citizen.Service/Models/Tickets/ViolationTicket.cs, src/frontend/citizen-portal/src/app/components/count-summary/count-summary.component.html, src/frontend/citizen-portal/src/app/components/dispute-submit-success/dispute-submit-success.component.spec.ts, src/frontend/citizen-portal/src/app/components/dispute-submit-success/dispute-submit-success.component.ts, src/frontend/citizen-portal/src/app/components/dispute-ticket-stepper/dispute-ticket-stepper.component.html, src/frontend/citizen-portal/src/app/components/dispute-ticket-stepper/dispute-ticket-stepper.component.ts, src/frontend/citizen-portal/src/app/components/dispute-ticket-summary/dispute-ticket-summary.component.html, src/frontend/citizen-portal/src/app/components/dispute-ticket-summary/dispute-ticket-summary.component.spec.ts, src/frontend/citizen-portal/src/app/components/dispute-ticket-summary/dispute-ticket-summary.component.ts, src/frontend/citizen-portal/src/app/core/validators/form-group.validators.ts, src/frontend/citizen-portal/src/app/services/notice-of-dispute.service.ts, src/frontend/citizen-portal/src/app/services/violation-ticket.service.ts
=> TCVP-1225 Validations Part 2

src/frontend/citizen-portal/src/app/components/dispute-ticket-stepper/dispute-ticket-stepper.component.html, src/frontend/citizen-portal/src/app/components/dispute-ticket-stepper/dispute-ticket-stepper.component.scss, src/frontend/citizen-portal/src/app/components/dispute-ticket-stepper/dispute-ticket-stepper.component.ts, src/frontend/citizen-portal/src/app/services/violation-ticket.service.ts, src/frontend/citizen-portal/yarn.lock, src/frontend/staff-portal/src/app/app-routing.module.ts, src/frontend/staff-portal/yarn.lock
=> updated eticket error message

src/frontend/staff-portal/src/app/components/ticket-page/ticket-page.component.ts
Added a FIXME note that should solve the model inconsistencies when implemented.
=> TCVP-1208 Added FIXME note to address model inconsistencies

src/frontend/citizen-portal/src/app/api/client-api.json, src/frontend/citizen-portal/src/app/api/model/violationTicket.model.ts, src/frontend/citizen-portal/src/app/components/dispute-ticket-stepper/dispute-ticket-stepper.component.html, src/frontend/citizen-portal/src/app/components/dispute-ticket-stepper/dispute-ticket-stepper.component.ts, src/frontend/citizen-portal/src/app/services/violation-ticket.service.ts
- TCVP-1225
- fix form validate when init
- change ticketId to ticket_id
=> TCVP-1225 Validations Part 3

.gitops/charts/traffic-court-online/charts/citizen-api/templates/deployment.yaml, .gitops/charts/traffic-court-online/charts/staff-api/templates/deployment.yaml, .gitops/charts/traffic-court-online/charts/workflow-service/templates/deployment.yaml, src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/appsettings.json, src/backend/TrafficCourts/Workflow.Service/appsettings.Development.json, src/backend/TrafficCourts/Workflow.Service/appsettings.json
- adds logging config to default appsettings.json files
- sets log level to debug by default temporarily - not will change to helm variable in future
=> Add serilog configuration to config, enable debug logging temporarily

.gitops/charts/traffic-court-online/charts/oracle-data-api/templates/deployment.yaml
- adds and mounts PVC for H2 data persistence
=> Mount PVC in oracle data api for database storage

src/frontend/citizen-portal/src/app/components/dispute-submit-success/dispute-submit-success.component.html, src/frontend/citizen-portal/src/app/components/dispute-ticket-stepper/dispute-ticket-stepper.component.html, src/frontend/citizen-portal/src/app/components/dispute-ticket-summary/dispute-ticket-summary.component.html, src/frontend/citizen-portal/src/app/services/notice-of-dispute.service.ts
=> TCVP-1358 fix additional informations

src/backend/TrafficCourts/Test/Workflow.Service/Features/Mail/SendEmailConsumerTests.cs, src/backend/TrafficCourts/Test/Workflow.Service/Services/EmailSenderServiceTests.cs, src/backend/TrafficCourts/Workflow.Service/Configuration/EmailConfiguration.cs, src/backend/TrafficCourts/Workflow.Service/Features/Mail/SendEmailConsumer.cs, src/backend/TrafficCourts/Workflow.Service/Services/EmailSenderService.cs, src/backend/TrafficCourts/Workflow.Service/appsettings.json
- removes check for RequestId is null
=> fix issue when send email not sent as a request/response

src/frontend/citizen-portal/src/app/components/dispute-ticket-stepper/dispute-ticket-stepper.component.html, src/frontend/citizen-portal/src/app/components/dispute-ticket-stepper/dispute-ticket-stepper.component.ts, src/frontend/citizen-portal/src/app/core/validators/form-group.validators.ts, src/frontend/citizen-portal/src/app/services/notice-of-dispute.service.ts
=> TCVP-1225 Validations Part 4 (last)

src/backend/TrafficCourts/Workflow.Service/Services/ISmtpClientFactory.cs, src/backend/TrafficCourts/Workflow.Service/Services/SmtpClientFactory.cs, src/backend/TrafficCourts/Workflow.Service/Services/SmtpConnectFailedException.cs
- fix ISmptClient being disposed before being returned from factory
- add xml doc
- clean up exception variable names
- add argument null checks
=> fix bug where ISmtpClient was being disposed

.gitops/charts/traffic-court-online/charts/staff-api/templates/deployment.yaml, .gitops/charts/traffic-court-online/charts/staff-api/values.yaml, docker-compose.yml
TCVP-1268 
- fixed an issue with the env vars in docker-compose to properly wire minio with staff-api
- added env vars to staff-api helm
docker-compose up 
Tested that staff-api works properly
=> TCVP-1268 fixed docker-compose to include minio

src/backend/TrafficCourts/Staff.Service/OpenAPIs/OracleDataAPI/v1_0/OracleDataApi.v1_0.json, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/Dispute.java
- [TCVP-1375](https://justice.gov.bc.ca/jira/browse/TCVP-1375)
- Added "assignedTo" and "assignedTc" properties to the dispute model.
- Added some missing comments to the other properties.
=> TCVP-1375 add fields for locking

src/frontend/citizen-portal/src/app/components/scan-ticket/scan-ticket.component.html, src/frontend/citizen-portal/src/app/components/scan-ticket/scan-ticket.component.ts
=> TCVP-1272 temp remove upload new image

src/backend/TrafficCourts/Citizen.Service/Models/Dispute/DisputedCount.cs, src/backend/TrafficCourts/Citizen.Service/Models/Dispute/NoticeOfDispute.cs, src/backend/TrafficCourts/Citizen.Service/Startup.cs, src/backend/TrafficCourts/Citizen.Service/TrafficCourts.Citizen.Service.csproj, src/backend/TrafficCourts/Citizen.Service/Validators/DisputedCountValidator.cs, src/backend/TrafficCourts/Citizen.Service/Validators/LegalRepresentationValidator.cs, src/backend/TrafficCourts/Citizen.Service/Validators/NoticeOfDisputeValidator.cs, src/backend/TrafficCourts/Messaging/MessageContracts/SubmitNoticeOfDispute.cs, src/backend/TrafficCourts/Staff.Service/Mappers/Mapper.cs, src/backend/TrafficCourts/Staff.Service/OpenAPIs/OracleDataAPI/v1_0/OracleDataApi.v1_0.json, src/backend/TrafficCourts/Workflow.Service/Models/NoticeOfDispute.cs, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/Dispute.java
- [TCVP-1334](https://justice.gov.bc.ca/jira/browse/TCVP-1334)
- Added detailed validation for the request required to create dispute utilizing fluent validator.
- Updated some required fields to be not nullable in multiple services.
=> TCVP-1334 add validation for dispute create

src/backend/oracle-data-api/src/test/resources/application.yml
Small fix to disable the startup tasks when doing JUnit tests.
=> junit test fix

src/frontend/citizen-portal/package.json, src/frontend/citizen-portal/src/app/app.module.ts, src/frontend/citizen-portal/src/app/components/scan-ticket/scan-ticket.component.html, src/frontend/citizen-portal/src/app/components/scan-ticket/scan-ticket.component.ts, src/frontend/citizen-portal/yarn.lock, src/frontend/staff-portal/src/app/app.module.ts, src/frontend/staff-portal/src/app/components/contact-info/contact-info.component.html, src/frontend/staff-portal/src/app/components/ticket-info/ticket-info.component.html, src/frontend/staff-portal/src/app/components/ticket-request/ticket-request.component.html, src/frontend/staff-portal/src/app/components/ticket-request/ticket-request.component.scss, src/frontend/staff-portal/src/app/components/ticket-request/ticket-request.component.spec.ts, src/frontend/staff-portal/src/app/components/ticket-request/ticket-request.component.ts
- added ticket request information to staff portal
=> worked on ticket request information

src/backend/oracle-data-api/Dockerfile, src/frontend/citizen-portal/Dockerfile, src/frontend/staff-portal/Dockerfile
[TCVP-1389](https://justice.gov.bc.ca/jira/browse/TCVP-1389)
Modified a few Dockerfiles to explicity pull images from `docker.io`
=> TCVP-1389 Added specific server to Docker FROM clauses.

src/frontend/citizen-portal/src/app/components/dispute-ticket-stepper/dispute-ticket-stepper.component.html, src/frontend/citizen-portal/src/app/components/dispute-ticket-stepper/dispute-ticket-stepper.component.ts
=> bug/TCVP-1360 scroll to top of each vertical step in mat-stepper

src/backend/TrafficCourts/Citizen.Service/Validators/DisputedCountValidator.cs, src/frontend/citizen-portal/src/app/components/dispute-submit-success/dispute-submit-success.component.html, src/frontend/citizen-portal/src/app/components/dispute-ticket-stepper/dispute-ticket-stepper.component.ts, src/frontend/citizen-portal/src/app/core/services/form-utils.service.ts, src/frontend/citizen-portal/src/app/services/notice-of-dispute.service.ts
- change back end validation to allow particular values to be set (or null) for not guilty on a count since citizen portal forces disputant to make a choice of appear in court before choosing plea.  Also disputant may choose one plea then later go back and change plea.
- misc clean up
=> Bug/tcvp 1407 Allow not guilty disputes to be submitted

src/frontend/citizen-portal/src/app/services/violation-ticket.service.ts
=> TCVP-1372 fix cached info

src/frontend/citizen-portal/src/app/services/violation-ticket.service.ts
=> [TCVP-1315] added non mva ticket error to ocr

src/frontend/citizen-portal/src/app/shared/dialogs/image-ticket-not-found-dialog/image-ticket-not-found-dialog.component.html, src/frontend/citizen-portal/src/app/shared/dialogs/ticket-not-found-dialog/ticket-not-found-dialog.component.html, src/frontend/citizen-portal/src/app/shared/dialogs/ticket-not-found-dialog/ticket-not-found-dialog.component.scss, src/frontend/staff-portal/src/app/services/violation-ticket.service.ts, src/frontend/staff-portal/src/app/shared/components/tco-page-header/tco-page-header.component.html
- TCVP-1313
- TCVP-1349
- TCVP-1359
=> TCVP-1313-1349-1359

src/frontend/citizen-portal/src/app/components/dispute-ticket-stepper/dispute-ticket-stepper.component.html, src/frontend/citizen-portal/src/app/components/dispute-ticket-stepper/dispute-ticket-stepper.component.ts, src/frontend/citizen-portal/src/app/shared/directives/form-error-state-matcher.directive.ts
=> TCVP-1384-1461 fix 

src/frontend/citizen-portal/src/app/app.module.ts
- Faker has 1.9MB in the production build
=> Remove dependency to reduce build size

src/frontend/citizen-portal/src/app/components/dispute-ticket-summary/dispute-ticket-summary.component.html, src/frontend/citizen-portal/src/app/shared/components/resolution-header/resolution-header.component.html, src/frontend/staff-portal/src/app/components/ticket-info/ticket-info.component.html
=> TCVP-1363-1461 bug fixes

src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApiClient.cs, src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/oracle-data-api.nswag
Workaround for nswag bug.
Changed "jsonLibrary": "NewtonsoftJson",
=> Workaround for nswag bug

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeController.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeService.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeServiceTest.java
TCVP-1058
Updated business rules - permitted a Dispute to be REJECTED if it is has a status of VALIDATED.
mvn verify
=> TCVP-1058 implemented validation change per new requirements

src/frontend/staff-portal/src/app/components/ticket-info/ticket-info.component.html
=> count 2, count 3 autocomplete

src/frontend/staff-portal/src/app/components/contact-info/contact-info.component.ts, src/frontend/staff-portal/src/app/components/ticket-info/ticket-info.component.ts, src/frontend/staff-portal/src/app/components/ticket-request/ticket-request.component.html
=> ticket request section info for e-tickets and refresh

src/frontend/citizen-portal/src/app/components/initiate-resolution/initiate-resolution.component.html, src/frontend/citizen-portal/src/app/services/violation-ticket.service.ts, src/frontend/citizen-portal/src/app/shared/dialogs/image-ticket-not-found-dialog/image-ticket-not-found-dialog.component.html
=> [TCVP-1418] changed camera ticket validation to 45 days.

.github/dependabot.yml
Added Java/Maven to the dependabot scans
=> Added Java to the dependabot scans

src/frontend/citizen-portal/src/app/services/violation-ticket.service.ts
=> TCVP-1484 urgent bug fix (need to merge into main)

tools/port-forward-jaeger.bat
Added a batch script to easily remote into jaeger running in DEV or TEST for debugging purposes.
Usage:
`port-forward-jaeger.bat dev`
=> Added a script to easily connect to jaeger remotely

src/frontend/citizen-portal/src/app/components/dispute-ticket-stepper/dispute-ticket-stepper.component.html, src/frontend/citizen-portal/src/app/components/dispute-ticket-stepper/dispute-ticket-stepper.component.ts, src/frontend/citizen-portal/src/app/components/scan-ticket/scan-ticket.component.html, src/frontend/citizen-portal/src/app/services/notice-of-dispute.service.ts, src/frontend/staff-portal/src/app/components/contact-info/contact-info.component.html, src/frontend/staff-portal/src/app/components/contact-info/contact-info.component.ts, src/frontend/staff-portal/src/app/components/ticket-info/ticket-info.component.html, src/frontend/staff-portal/src/app/components/ticket-info/ticket-info.component.ts
Inputting a variety of DL number into citizen, staff portal and saving changes for valid DL numbers (7-9 digits for BC), (20 chars for others), required for Canada/US only
=> drivers licence number validation

src/backend/oracle-data-api/src/test/resources/application.yml
Just a simple addition to the application.yml file to control hibernate logging.
=> Added logging level for hibernate

infrastructure/certificates/tickets.gov.bc.ca.conf
Added docker commands to run openssl to regenerate/verify the csr.
Bumped the bits from 2048 to 4096
=> Updated CSR configuration

src/frontend/staff-portal/src/app/components/contact-info/contact-info.component.ts, src/frontend/staff-portal/src/app/components/ticket-info/ticket-info.component.ts
=> [TCVP-1471] worked on shifting date to adjust the time

src/frontend/citizen-portal/src/app/components/dispute-ticket-stepper/dispute-ticket-stepper.component.html, src/frontend/citizen-portal/src/app/services/notice-of-dispute.service.ts, src/frontend/staff-portal/src/app/services/dispute.service.ts
=> [TCVP-1471] worked on updating date and time

src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApi.v1_0.json, src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApiClient.cs, src/backend/TrafficCourts/Staff.Service/Controllers/JJController.cs, src/backend/TrafficCourts/Staff.Service/Services/IJJDisputeService.cs, src/backend/TrafficCourts/Staff.Service/Services/JJDisputeService.cs, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/JJDisputeController.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeService.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/JJDisputeService.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/JJDisputeControllerTest.java
- [TCVP-1435](https://justice.gov.bc.ca/jira/browse/TCVP-1435)
- Added functionality to update a single JJ Dispute through the Oracle Data Interface API based on unique violation ticket number and the jj dispute data being passed in the body.
- Added feature for changing JJDispute status to 'Review' when updating the JJDispute for admin submission.
- Regenerated OpenAPI spec of OracleDataApi.v1_0.json and added admin resolution submission endpoint to staff api in order to send update JJ Dispute request to oracle data api.
=> TCVP-1435 admin resolution submission

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/JJDisputeService.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/JJDisputeControllerTest.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/JJDisputeServiceTest.java
- Changed business logic for JJ Dispute status in order to allow updating from 'NEW' status into 'NEW' status.
=> TCVP-1435 Update JJ Dispute Status Change Rule

src/frontend/staff-portal/src/app/components/jj-dispute-assignments/jj-dispute-assignments.component.ts
- corrected counts for assigned / unassigned
=> updated counts

src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/Services/SftpService.cs
- [TCVP-1544](https://justice.gov.bc.ca/jira/browse/TCVP-1544)
- Added functionality to create sub-directories if they are not exist when uploading ARC files through SFTP.
=> TCVP-1544 Functionality to create sub directories

src/frontend/staff-portal/src/app/components/jj-dispute-assignments/jj-dispute-assignments.component.html, src/frontend/staff-portal/src/app/components/jj-dispute-assignments/jj-dispute-assignments.component.scss, src/frontend/staff-portal/src/app/components/jj-dispute-assignments/jj-dispute-assignments.component.ts
- JIRA Ticket 1577 testing feedback
Visually inspect text/font changes
retest bulk / individual assignments
=> testing feedback

src/backend/TrafficCourts/Workflow.Service/Consumers/DisputeApprovedConsumer.cs, src/backend/TrafficCourts/Workflow.Service/Services/SubmitDisputeToArcService.cs
- Added exception handling to the Workflow service to catch the errors when disputes are approved to send ARC API request.
=> Add ARC API Request Exception Handling

src/backend/TrafficCourts/Test/Workflow.Service/Services/EmailSenderServiceTests.cs, src/backend/TrafficCourts/Workflow.Service/Services/EmailSenderService.cs
- if allow list is configured, this change prevents an error from being thrown if all email addresses were filtered out
- the email address will not be sent and it will be consumed from the message broker.
=> Refs TCVP-1621 do not throw error if all addresses are filtered

src/backend/TrafficCourts/Test/Arc.Dispute.Service/Mappings/MappingTests.cs, src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/Mappings/DisputeTicketToArcFileRecordListConverter.cs, src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/Models/ArcFileRecord.cs, src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/Services/ArcFileService.cs
- Fixed the following issues with the ARC data files:
1.	The file number needs to have a suffix either 01 02 or 03 this will indicate the accused on the file you’re probably only ever going to be dealing with the first accused so I need the file number to be the VT# followed by 2 spaces and then 01.
2.	I also need the count which will probably be 001 as I believe you’re only dealing with MVA.
3.	The transaction number on an EV or ED is 00000 
4.	The DL/Client number must be 9 characters long if you only have 7 from the client you need to prepend with a zero and append a calculated check digit
5.	The name should be laid out surname, first name 
6.	The paragraph needs to be capitalized as well, as everything that comes from ARC is a capital …
=> Fixed some problems with the ARC data files

src/backend/TrafficCourts/Test/Arc.Dispute.Service/Mappings/MappingTests.cs, src/backend/TrafficCourts/Test/Arc.Dispute.Service/Models/DriversLicenceTest.cs, src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/Mappings/DisputeTicketToArcFileRecordListConverter.cs, src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/Models/DriversLicence.cs
- Adds the check digit to the drives licence
=> Refs TCVP-1613 add drivers licence checksum

infrastructure/openshift/test/oidc-route.yaml
=> Add public route for OIDC for test

src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/Program.cs
- [TCVP-1666](https://justice.gov.bc.ca/jira/browse/TCVP-1666)
- Removed the default setting to enable HTTPS redirection and authorization from ARC API.
=> TCVP-1666 - Removed Config to use HTTPS and Authorization

src/backend/TrafficCourts/Common/Authorization/KeycloakAuthorizationHandler.cs, src/backend/TrafficCourts/Common/Authorization/KeycloakAuthorizationOptions.cs, src/backend/TrafficCourts/Common/Authorization/KeycloakAuthorizationPolicyProvider.cs, src/backend/TrafficCourts/Common/Authorization/KeycloakAuthorizationRequirement.cs, src/backend/TrafficCourts/Common/Authorization/KeycloakAuthorizationServiceCollectionExtensions.cs, src/backend/TrafficCourts/Staff.Service/Authentication/Authentication.cs, src/backend/TrafficCourts/Staff.Service/Authentication/Policies.cs, src/backend/TrafficCourts/Staff.Service/Authentication/Resources.cs, src/backend/TrafficCourts/Staff.Service/Authentication/Roles.cs, src/backend/TrafficCourts/Staff.Service/Authentication/Scopes.cs, src/backend/TrafficCourts/Staff.Service/Controllers/DisputeController.cs, src/backend/TrafficCourts/Staff.Service/Controllers/JJControllerBase.cs, src/backend/TrafficCourts/Staff.Service/Controllers/VTCControllerBase.cs, src/backend/TrafficCourts/Staff.Service/Startup.cs
- Adds keycloak authorization code to staff API
=> Update keycloak authorization code

src/backend/TrafficCourts/Common/Authorization/KeycloakAuthorizationHandler.cs, src/backend/TrafficCourts/Common/Authorization/KeycloakAuthorizationServiceCollectionExtensions.cs, src/backend/TrafficCourts/Common/Authorization/KeycloakAuthorizeAttribute.cs, src/backend/TrafficCourts/Staff.Service/Authentication/Authentication.cs, src/backend/TrafficCourts/Staff.Service/Authentication/Claims.cs, src/backend/TrafficCourts/Staff.Service/Authentication/Policies.cs, src/backend/TrafficCourts/Staff.Service/Authentication/Resources.cs, src/backend/TrafficCourts/Staff.Service/Authentication/Roles.cs, src/backend/TrafficCourts/Staff.Service/Startup.cs
- Cleans up authorization
- Adds `KeycloakAuthorizeAttribute` to simplify setting up permissions on controller and actions, example usage `[KeycloakAuthorize(Resources.Dispute, Scopes.Read)]`
- Removes `Policies` type
- Removes `Roles` type
- Removes `Claims` type
=> Clean up authorization logic

src/backend/TrafficCourts/Staff.Service/Authentication/Resources.cs, src/backend/TrafficCourts/Staff.Service/Authentication/Scopes.cs, src/backend/TrafficCourts/Staff.Service/Controllers/DisputeController.cs, src/backend/TrafficCourts/Staff.Service/Controllers/JJController.cs, src/backend/TrafficCourts/Staff.Service/TrafficCourts.Staff.Service.csproj, src/backend/TrafficCourts/TrafficCourts.Staff.Service.Test/Controllers/DisputeControllerTest.cs, src/backend/TrafficCourts/TrafficCourts.Staff.Service.Test/Controllers/JJControllerTest.cs, src/backend/TrafficCourts/TrafficCourts.Staff.Service.Test/TrafficCourts.Staff.Service.Test.csproj
- [TCVP-1668](https://justice.gov.bc.ca/jira/browse/TCVP-1668)
- Updated Staff API to incorporate correct authorization configuration and permissions in order to guard each endpoint against unauthorized access.
- Added unit tests to check all Staff API endpoints to confirm that all are guarded with proper KeycloakAuthorization or explicit AllowAnonymous attribute.
- Added some response types which were previously missing from some endpoints.
=> TCVP-1668 - Add Auth Permission Scope for Staff API

src/backend/TrafficCourts/Citizen.Service/Dockerfile, src/backend/TrafficCourts/Citizen.Service/Dockerfile.rhel8, src/backend/TrafficCourts/Staff.Service/Dockerfile, src/backend/TrafficCourts/Staff.Service/Dockerfile.rhel8, src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/Dockerfile, src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/Dockerfile.rhel8, src/backend/TrafficCourts/Workflow.Service/Dockerfile, src/backend/TrafficCourts/Workflow.Service/Dockerfile.rhel8, src/backend/TrafficCourts/entrypoint.sh, src/backend/oracle-data-api/Dockerfile, src/backend/oracle-data-api/entrypoint.sh
- Adds entrypoint.sh script to load vault secrets as environment variables if available
- Launch service with correct with parameters
=> Update docker builds to use entrypoint.sh script

README.md
- update main readme with respect to configuration settings and usage, still work in progress
=> Update main README.md file with information (wip) around configuration

src/backend/TrafficCourts/Citizen.Service/Dockerfile, src/backend/TrafficCourts/Citizen.Service/Dockerfile.rhel8, src/backend/TrafficCourts/Staff.Service/Dockerfile, src/backend/TrafficCourts/Staff.Service/Dockerfile.rhel8, src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/Dockerfile, src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/Dockerfile.rhel8, src/backend/TrafficCourts/Workflow.Service/Dockerfile, src/backend/TrafficCourts/Workflow.Service/Dockerfile.rhel8, src/backend/oracle-data-api/Dockerfile
- change ownership and permissions on entrypoint.sh
=> Change entrypoint.sh permissions and ownership

src/backend/TrafficCourts/Citizen.Service/Models/Dispute/NoticeOfDispute.cs, src/backend/TrafficCourts/Citizen.Service/Validators/NoticeOfDisputeValidator.cs, src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApi.v1_0.json, src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApiClient.cs, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/Dispute.java
- [TCVP-1675](https://justice.gov.bc.ca/jira/browse/TCVP-1675?)
- Made email address and home phone number optional in Oracle Data API.
- Updated the Oracle OpenAPI Spec client json for Staff API and made email address and home phone number optional in Citizen API and Staff API as well.
- Added a missing regex for the home phone number field in Citizen API.
=> TCVP-1675 - Make Email and Phone Number Optional

src/backend/TrafficCourts/Citizen.Service/Validators/Rules/DateOfServiceLT30Rule.cs, src/backend/TrafficCourts/Test/Citizen.Service/Validators/Rules/DateOfServiceLT30RuleTest.cs
TCVP-1676
Change of requirements: future DateOfService Violation ticket dates are now permitted.
dotnet test
=> TCVP-1676 Violation tickets: future DateOfService dates are now allowed

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-online/charts/arc-dispute-api/templates/deployment.yaml, .gitops/charts/traffic-court-online/charts/citizen-api/templates/deployment.yaml, .gitops/charts/traffic-court-online/charts/citizen-web/templates/configmap.yaml, .gitops/charts/traffic-court-online/charts/citizen-web/templates/deployment.yaml, .gitops/charts/traffic-court-online/charts/staff-api/templates/deployment.yaml, .gitops/charts/traffic-court-online/charts/staff-web/templates/configmap.yaml, .gitops/charts/traffic-court-online/charts/staff-web/templates/deployment.yaml, .gitops/charts/traffic-court-online/charts/workflow-service/templates/deployment.yaml, .gitops/charts/traffic-court-online/values.yaml, .gitops/charts/traffic-court-test-values.yaml
Move default logging config to console to chart environment variables
Add test env values file
=> Adjust logging default values for .net services

infrastructure/keycloak/staff-api-authz-config.json
Adds an initial export of the staff-api authorization config. This configuration has been imported into dev and test.
=> Add initial staff-api-authz-config.json

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/error/ControllerAdvisor.java
Improved logging in oracle-data-api project
=> Improved logging in oracle data api

src/frontend/staff-portal/src/app/components/jj-dispute-assignments/jj-dispute-assignments.component.html
-  TCVP-1616
reviewed title in staff portal
=> TCVP-1616 title of column change

.env.template, .gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml
- add an entry to .env.template to indicate that all developer .env files need to contain the new entry contact 
Kevin Neufeld for this value
- udpated version number in helm charts
- ran staff portal and citizen portal to ensure not broken
=> helm values and .env.template addition

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/app/services/violation-ticket.service.ts, src/frontend/citizen-portal/src/assets/app.config.json
- JIRA 1676
submitted future dated ticket, accepted by API and UX
submitted > 30 days old handwritten, electronic and > 45 days old camera ticket rejected by API
=> future dated tickets

src/backend/TrafficCourts/Workflow.Service/Consumers/DisputeSubmitConsumer.cs
TCVP-1685
This PR implements the highlight workflow.
* When a Dispute is initially saved by the DisputeSubmitConsumer, send a verification email to the Disputant.
=> TCVP-1685 

src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/UserIdentityProviderHandler.cs, src/backend/TrafficCourts/TrafficCourts.Common.Test/OpenAPIs/UserIdentityProviderHandlerTest.cs
- Adds delegating handler to extract the username and full name from the current user and add to the out bound request
- Adds unit tests
=> TCVP-1756 create delegating handler to add user information to requests

src/backend/TrafficCourts/Citizen.Service/Features/Tickets/AnalyseHandler.cs, src/backend/TrafficCourts/Citizen.Service/Validators/FormRecognizerValidator.cs, src/backend/TrafficCourts/Citizen.Service/Validators/IFormRecognizerValidator.cs
- Change ValidateViolationTicket method to async to ensure async rules awaited
- Resolves warning that async method not awaited
=> Change ValidateViolationTicket method to async to ensure async rules awaited

src/backend/TrafficCourts/Citizen.Service/Validators/NoticeOfDisputeValidator.cs, src/backend/TrafficCourts/Common/Authentication/IOAuthClient.cs, src/backend/TrafficCourts/Common/Authentication/ITokenCache.cs, src/backend/TrafficCourts/Common/Authentication/ITokenService.cs, src/backend/TrafficCourts/Common/Authentication/OAuthClient.cs, src/backend/TrafficCourts/Common/Authentication/OAuthTokenService.cs, src/backend/TrafficCourts/Common/Authentication/Token.cs, src/backend/TrafficCourts/Common/Authentication/TokenAuthorizationHandler.cs, src/backend/TrafficCourts/Common/Authentication/TokenCache.cs, src/backend/TrafficCourts/Common/Authorization/KeycloakAuthorizationHandler.cs, src/backend/TrafficCourts/Common/Authorization/KeycloakAuthorizationOptions.cs, src/backend/TrafficCourts/Common/Authorization/KeycloakRolesClaimsTransformation.cs, src/backend/TrafficCourts/Common/Features/FilePersistence/InMemoryFilePersistenceService.cs, src/backend/TrafficCourts/Staff.Service/Authentication/Authentication.cs, src/backend/TrafficCourts/Staff.Service/Configuration/OracleDataApiConfiguration.cs, src/backend/TrafficCourts/Staff.Service/Controllers/DisputeController.cs, src/backend/TrafficCourts/Test/Arc.Dispute.Service/Mappings/CsvDataAttribute.cs, src/backend/TrafficCourts/Test/Arc.Dispute.Service/Mappings/MappingTests.cs, src/backend/TrafficCourts/Test/Citizen.Service/Services/RedisCacheServiceTests.cs, src/backend/TrafficCourts/Test/Citizen.Service/Validators/Rules/CountSectionRuleTest.cs, src/backend/TrafficCourts/Test/Workflow.Service/Mappings/MappingTests.cs, src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Client.Test/AddArcDisputeClientTest.cs, src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/Configuration/SftpConnectionOptions.cs, src/backend/TrafficCourts/TrafficCourts.Common.Test/Authorization/KeycloakAuthorizationRequirementTest.cs, src/backend/TrafficCourts/TrafficCourts.Common.Test/GetMimeTypeTest.cs, src/backend/TrafficCourts/TrafficCourts.Staff.Service.Test/Controllers/DisputeControllerTest.cs, src/backend/TrafficCourts/TrafficCourts.Staff.Service.Test/Controllers/JJControllerTest.cs, src/backend/TrafficCourts/Workflow.Service/Configuration/OracleDataApiConfiguration.cs
- Removes some of the nullable warnings from unit tests
- Removes warnings in application code
=> Remove build warnings in tests

src/backend/oracle-data-api/README.md, src/backend/oracle-data-api/src/main/resources/occm-openapi-spec.yaml
- Adds initial OpenAPI specification for the oracle data api
Ran tooling to validate format, used Swagger UI to run services against dev ORDS
=> add occm openapi spec

src/backend/TrafficCourts/Staff.Service/Startup.cs
=> Added a missing UserIdentityProviderHandler registration

src/backend/oracle-data-api/pom.xml, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/config/ApiClientConfiguration.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/config/WebClientConfiguration.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/config/WebClientProperties.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/ords/DisputeRepositoryImpl.java, src/backend/oracle-data-api/src/main/resources/occm-openapi-spec.yaml
- [TCVP-1782](https://justice.gov.bc.ca/jira/browse/TCVP-1782)
- Added dependencies for the generating ORDS OpenAPI spec client and configuration to delegate implementation.
=> TCVP-1782 Added dependencies for generating ORDS OpenAPI spec client

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/frontend/staff-portal/src/assets/app.config.json
- version numbers for 1.45.1 build
=> release number updates

src/backend/TrafficCourts/Staff.Service/Startup.cs
- remove duplicate service addition
successful build
=> removed one

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/frontend/staff-portal/src/assets/app.config.json
=> release 1.45.2

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml
- use dev.tickets.gov.bc.ca, test.tickets.gov.bc instead of longer form
=> updated email urls

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeController.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/DisputeRepository.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/ords/DisputeRepositoryImpl.java, src/backend/oracle-data-api/src/main/resources/occm-openapi-spec.yaml, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/impl/ords/DisputeServiceImplTest.java
TCVP-1738
Implemented DeleteDisputeById for ORDS
Added unit tests
mvn test
=> TCVP-1738 Implemented ORDS delete Dispute

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/frontend/staff-portal/src/assets/app.config.json
- Update settings to 1.46.0
Wasnt
=> release 1.46.0

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml
=> Release 1.46.1

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeController.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/DisputeMapper.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/ViolationTicketMapper.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/Dispute.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/ords/DisputeRepositoryImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeService.java, src/backend/oracle-data-api/src/main/resources/occm-openapi-spec.yaml
- [TCVP-1745](https://justice.gov.bc.ca/jira/browse/TCVP-1745)
- Added mapper for ORDS violation ticket model.
- Added functionality to insert disputes through ORDS to save the whole dispute object in oracle database.
=> TCVP-1745 integrate insert dispute ords

src/frontend/staff-portal/proxy.conf.json, src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-inbox/jj-dispute-inbox.component.html
- JIRA ticket 1827
Reviewed JJ Inbox vs. JJ Dispute Info values before/after change
=> violation timestamp

.gitops/charts/deploy.bat, .gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml
- Updates helm files for release 1.46.2
=> Change release tag 1.46.2

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeController.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/DisputeResult.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/DisputeRepository.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/h2/DisputeRepositoryImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/ords/DisputeRepositoryImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeService.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/BaseTestSuite.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeControllerTest.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/JJDisputeControllerTest.java
TCVP-1833
Added a new GET /api/dispute endpoint to find a Dispute by TicketNumber and Time.
Added junit tests
New tests
mvn verify
=> TCVP-1833 add findByTicketNumberAndTime oracle api endpoint

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/frontend/staff-portal/src/assets/app.config.json
=> release 1.47.0

.gitops/charts/traffic-court-test-values.yaml
=> release number

.gitops/charts/traffic-court-dev-values.yaml, src/frontend/staff-portal/src/assets/app.config.json
=> Release 1.48.1

src/backend/TrafficCourts/Workflow.Service/Services/OracleDataApiService.cs
- [TCVP-1892](https://justice.gov.bc.ca/jira/browse/TCVP-1892)
- Fixes the bug for the mapping of dispute counts from TCO model to OCCAM ORDS model when the dispute data is first inserted to the database.
=> TCVP-1892 Fixes an issue where disputeCounts cannot be populated

src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApi.v1_0.json, src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApiClient.cs, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/ords/DisputeRepositoryImpl.java, src/backend/oracle-data-api/src/main/resources/occm-openapi-spec.yaml, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/impl/ords/DisputeServiceImplTest.java
TCVP-1834
Implemented ORDS endpoint to findByTicketNumberAndTime()
Added junit tests
mvn verify
=> TCVP-1834 implemented ORDs endpoint to fetch by TicketNumber and Time

src/backend/oracle-data-api/src/main/resources/application.yml, src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-wr-inbox/jj-dispute-wr-inbox.component.ts, src/frontend/staff-portal/src/app/components/staff-workbench/ticket-inbox/ticket-inbox.component.ts
- switch to ORDS, dont fail on invalid JSON when checking for System Detected OCR Issues
=> Release 1 48 3

src/backend/oracle-data-api/Dockerfile, src/backend/oracle-data-api/src/main/resources/application.yml
- Attempts to add the JXM/Java metrics exporting
=> add prometheus jmx metrics exporting

src/frontend/citizen-portal/src/app/components/dispute-landing/dispute-landing.component.html, src/frontend/staff-portal/src/app/app.module.ts, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.html, src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-digital-case-file/jj-dispute-digital-case-file.component.html, src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-digital-case-file/jj-dispute-digital-case-file.component.scss, src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-digital-case-file/jj-dispute-digital-case-file.component.ts, src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-hearing-inbox/jj-dispute-hearing-inbox.component.html, src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-hearing-inbox/jj-dispute-hearing-inbox.component.ts, src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-wr-assignments/jj-dispute-wr-assignments.component.html, src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-wr-inbox/jj-dispute-wr-inbox.component.html, src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-wr-inbox/jj-dispute-wr-inbox.component.ts, src/frontend/staff-portal/src/app/components/jj-workbench/jj-workbench-dashboard/jj-workbench-dashboard.component.html, src/frontend/staff-portal/src/app/components/jj-workbench/jj-workbench-dashboard/jj-workbench-dashboard.component.ts, src/frontend/staff-portal/src/app/services/auth.service.ts, src/frontend/staff-portal/src/app/services/jj-dispute.service.ts
=> TCVP-1861 UX for searching DCF

src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-digital-case-file/jj-dispute-digital-case-file.component.html, src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-digital-case-file/jj-dispute-digital-case-file.component.ts
=> fix model changes

src/backend/oracle-data-api/pom.xml, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/DisputeMapper.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/ViolationTicketMapper.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/EmailHistory.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/FileHistory.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/JJDisputeCourtAppearanceRoP.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/JJDisputedCountRoP.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/ParticipantIDIR.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/ViolationTicket.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/ords/JJDisputeRepositoryImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/JJDisputeService.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/util/RandomUtil.java
Cleaned up all unused imports, bad code, and warnings.
mvn verify
=> Fixed Java compiler warnings/errors

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/frontend/staff-portal/src/assets/app.config.json
=> release 49.1

src/backend/TrafficCourts/Staff.Service/Controllers/LookupController.cs, src/backend/TrafficCourts/Staff.Service/Startup.cs
TCVP-1946
- Added api endpoint to return Languages from redis
dotnet test
=> TCVP-1946 staff-api create languages api lookup

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/ViolationTicketCount.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/util/RandomUtil.java
ORDS schema changed w.r.t statute text column size. Updated TCO model to match.
- Dispute.section is now 10 characters instead of 15.
mvn verify
=> Updated statute text column length due to db changes

src/backend/TrafficCourts/Workflow.Service/Sagas/VerifyEmailAddressSagaDefinition.cs, src/backend/TrafficCourts/Workflow.Service/Startup.cs
- Adds Saga message retry on concurrency exception
=> TCVP-1951 add message retry on concurrency exception

src/backend/TrafficCourts/Citizen.Service/Services/Impl/RedisCacheService.cs, src/backend/TrafficCourts/Citizen.Service/Startup.cs, src/backend/TrafficCourts/Common/Extensions.cs, src/backend/TrafficCourts/Messaging/LoggingExtensions.cs, src/backend/TrafficCourts/Messaging/MessageContracts/DispuantEmailFiltered.cs, src/backend/TrafficCourts/Messaging/MessageContracts/DispuantEmailSent.cs, src/backend/TrafficCourts/Staff.Service/Authentication/Authentication.cs, src/backend/TrafficCourts/Test/Citizen.Service/Mappings/NoticeOfDisputeToMessageContractMappingTests.cs, src/backend/TrafficCourts/Test/Citizen.Service/Services/RedisCacheServiceTests.cs, src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Client.Test/AddArcDisputeClientTest.cs, src/backend/TrafficCourts/TrafficCourts.Common.Test/Configuration/SwaggerConfigurationTests.cs, src/backend/TrafficCourts/TrafficCourts.Common.Test/Features/FilePersistence/ExtensionsTest.cs, src/backend/TrafficCourts/TrafficCourts.Common.Test/OpenAPIs/AddOracleDataApiClientTest.cs, src/backend/TrafficCourts/TrafficCourts.Staff.Service.Test/Controllers/EmailHistoryControllerTest.cs, src/backend/TrafficCourts/TrafficCourts.Staff.Service.Test/Controllers/FileHistoryControllerTest.cs, src/backend/TrafficCourts/Workflow.Service/Sagas/VerifyEmailAddressSagaStateMachine.cs
- Resolves the build warnings in the .net projects
=> Fix build warnings

src/backend/TrafficCourts/Citizen.Service/Validators/FormRecognizerValidator.cs, src/backend/TrafficCourts/Citizen.Service/Validators/Rules/CountActRegMustBeMVA.cs, src/backend/TrafficCourts/Citizen.Service/Validators/Rules/OnlyMVAIsSelectedRule.cs, src/backend/TrafficCourts/Citizen.Service/Validators/ValidationMessages.cs, src/backend/TrafficCourts/Test/Citizen.Service/Validators/Rules/OnlyMVAIsSelectedRuleTest.cs
TCVP-1645
OCR validation rule changes, test changes
dotnet test
=> TCVP-1645 updated OCR validation rules

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> release 1.49.2

.github/workflows/bld-oracle-data-api.yml
Created a workflow to build and push a build of the `oracle-data-api` project to OpenShift.
The workflow will be automatically triggered on the creation of a tag in Github.
The pushed image will be tagged with the same name of the Github tag, ie. `oracle-data-api:1.49.2`
Created a test tag and confirmed the image was created in OpenShift.
=> Created build action for oracle-data-api

src/backend/TrafficCourts/Citizen.Service/Dockerfile, src/backend/TrafficCourts/Citizen.Service/Dockerfile.rhel8, src/backend/TrafficCourts/Staff.Service/Dockerfile, src/backend/TrafficCourts/Staff.Service/Dockerfile.rhel8, src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/Dockerfile, src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/Dockerfile.rhel8, src/backend/TrafficCourts/Workflow.Service/Dockerfile, src/backend/TrafficCourts/Workflow.Service/Dockerfile.rhel8, src/backend/oracle-data-api/Dockerfile, src/frontend/citizen-portal/Dockerfile, src/frontend/staff-portal/Dockerfile
- Adds BUILD_IMAGE and RUNTIME_IMAGE to each application Dockerfile
Run docker-compose build
=> Add BUILD_IMAGE and RUNTIME_IMAGE Dockerfile args

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
- Update Helm chart tags to 1.50.1
- Update App Versions to 1.50.1
=> Release 1.50.1

infrastructure/openshift/dev/ords-proxy.yaml
Updated ords-proxy so that it works for both occam and tco schema
=> Updated ords-proxy so that it works for both occam and tco schema

src/backend/TrafficCourts/Test/Workflow.Service/Consumers/SearchDisputeConsumerTest.cs
TCVP-1811 Added xunit tests
dotnet test
=> TCVP-1811 Added xunit tests

src/backend/TrafficCourts/Citizen.Service/Configuration/TicketStorageType.cs, src/backend/TrafficCourts/Citizen.Service/Services/Tickets/Search/TicketSearchType.cs, src/backend/TrafficCourts/Common/Configuration/TicketStorageType.cs, src/backend/TrafficCourts/Common/Converters/Json/JsonUtils.cs, src/backend/TrafficCourts/Common/Features/Mail/EmailMessage.cs, src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApi.v1_0.json, src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApiClient.g.cs, src/backend/TrafficCourts/Messaging/Configuration/MassTransitTransport.cs, src/backend/TrafficCourts/Messaging/MessageContracts/Plea.cs, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/DisputantUpdateRequestStatus.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/DisputantUpdateRequestType.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/DisputeStatus.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/JJDisputeAttendanceType.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/JJDisputeCourtAppearanceAPP.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/JJDisputeCourtAppearanceCrown.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/JJDisputeHearingType.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/JJDisputeStatus.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/Plea.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/YesNo.java
Per recent team discussions, created an enum value of UNKNOWN at index 0 for all enums. This should help identify issues where enums have not been properly set.
mvn verify
dotnet test
=> Added an UNKNOWN enum value at index 0

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> release 1.51.0

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml
- Updated helm charts with similar changes to docker-compose to account for variables with 'unknown' as the default value
=> update helm charts

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeController.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeService.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeControllerTest.java
- Fixed logic with /dispute/{id}/email/verify endpoint
- Added junit tests to confirm functionality and code coverage
mvn verify
=> Fixed logic with /email/verify endpoint

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> release 1.51.2

src/backend/TrafficCourts/TrafficCourts.Coms.Client.Test/ServiceTests/GetFileAsync.cs
- fixes build warning in unit test
=> fix compile warning in unit test

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/JJDisputeMapper.java, src/backend/oracle-data-api/src/main/resources/tco-openapi-spec.yaml, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/JJDisputeMapperTest.java
Added mapping for JJDisputeRemark
Added jUnit test
mvn verify
=> Added mapping for JJDisputeRemark

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/ViolationTicketMapper.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/Dispute.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/ViolationTicket.java, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
- related to recent data changes, allows inserts of new disputes through citizen portal
=> New required fields

src/backend/bc-gov-virus-scan/openapi-3_0.yaml
- Adds the generated OpenAPI spec file (converted to yaml)
=> add openapi spec

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml
=> TCVP-2138 fix charts files

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> release 1.53.2

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> release 1.54.0

.gitops/charts/traffic-court-online/charts/citizen-api/templates/deployment.yaml, .gitops/charts/traffic-court-online/charts/staff-api/templates/deployment.yaml, .gitops/charts/traffic-court-online/charts/workflow-service/templates/deployment.yaml
- add double underscore to helm chart settings
- 
=> helm chart fixes

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> release 1.54.1

.gitops/charts/common-object-management-service-values.yaml, .gitops/charts/deploy-coms.ps1, .gitops/charts/deploy.ps1, infrastructure/openshift/tools/build-configs/clamav-build.yaml, infrastructure/openshift/tools/build-configs/virus-scan-api-build.yaml
- add deployment powershell to assist deployment of main tco and coms
- change coms image version
=> Update DevOps files

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/backend/TrafficCourts/Staff.Service/Services/JJDisputeService.cs, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> release 1.54.2

src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.html, src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.ts, src/frontend/citizen-portal/src/app/services/notice-of-dispute.service.ts
=> TCVP-2179 fix dispute stepper

src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApi.v1_0.json, src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApiClient.g.cs
Refreshed the generated Oracle Data OpenAPI client in .NET
=> Updated Oracle Data OpenApi client in .NET

src/frontend/citizen-portal/src/app/api/swagger.json, src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.ts
- TCVP-2192
manual tests entering a dispute switching back and forth between requiring and not requiring court appearance without filling in reasons.
=> dont require reasons if court appearance Y

infrastructure/openshift/tools/image-streams/dotnet.yaml, src/backend/TrafficCourts/Citizen.Service/Dockerfile.rhel8, src/backend/TrafficCourts/Staff.Service/Dockerfile.rhel8, src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/Dockerfile.rhel8, src/backend/TrafficCourts/Workflow.Service/Dockerfile.rhel8
- update image streams and Dockerfile
=> Adjust dotnet image streams and build definitions on openshift

src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApi.v1_0.json, src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApiClient.g.cs, src/frontend/staff-portal/src/app/api/model/emailHistory.model.ts, src/frontend/staff-portal/src/app/api/swagger.json, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.ts
- cant retrieve jj disputes or open written reasons
tested retrieving jj disputes
=> api updates

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> release 1.54.4

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
- release 1.54.5
- [] Bug fix (non-breaking change which fixes an issue)
=> release 1.54.5

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/JJDisputedCount.java, src/backend/oracle-data-api/src/main/resources/tco-openapi-spec.yaml, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/JJDisputeMapperTest.java
Fixed mapping of Doubles from ORDS.
=> Fixed mapping of double amounts

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> release 1.55.0

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> release 1.55.1

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> release 1.55.2

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> version update

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> release 1.55.4

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeController.java, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/app/components/staff-workbench/ticket-inbox/ticket-inbox.component.html, src/frontend/staff-portal/src/app/components/staff-workbench/ticket-inbox/ticket-inbox.component.scss, src/frontend/staff-portal/src/assets/app.config.json
=> ux updates

src/backend/TrafficCourts/Citizen.Service/Features/Disputes/Create.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/ObjectManagementService.cs
- TCVP-2256
Submit notice of dispute with handwritten ticket, open in staff workbench
=> coms issues

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> release 1.55.6

src/backend/TrafficCourts/Citizen.Service/Mappings/MappingProfile.cs, src/backend/TrafficCourts/Citizen.Service/Models/Disputes/DisputeCount.cs, src/backend/TrafficCourts/Citizen.Service/Models/Disputes/NoticeOfDispute.cs, src/backend/TrafficCourts/Messaging/MessageContracts/DisputeCount.cs, src/backend/TrafficCourts/Messaging/MessageContracts/DisputeUpdateRequest.cs, src/backend/TrafficCourts/Messaging/MessageContracts/SubmitNoticeOfDispute.cs, src/frontend/citizen-portal/src/app/api/model/noticeOfDispute.model.ts, src/frontend/citizen-portal/src/app/api/swagger.json, src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.html, src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.ts, src/frontend/citizen-portal/src/app/services/dispute.service.ts, src/frontend/citizen-portal/src/app/store/dispute/dispute.effects.ts
=> TCVP-2041, TCVP-2207 & bug fix

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> release 1.56.0

infrastructure/openshift/tools/build-configs/form-recognizer-layout-build.yaml, infrastructure/openshift/tools/image-streams/buildah.yaml, infrastructure/openshift/tools/image-streams/clamav.yaml, infrastructure/openshift/tools/image-streams/dotnet.yaml, infrastructure/openshift/tools/image-streams/eclipse-temurin.yaml, infrastructure/openshift/tools/image-streams/form-recognizer-layout.yaml, infrastructure/openshift/tools/image-streams/maven.yaml, infrastructure/openshift/tools/image-streams/nginx-120.yaml, infrastructure/openshift/tools/image-streams/node.yaml, infrastructure/openshift/tools/image-streams/pipelines-git-init-rhel8.yaml, infrastructure/openshift/tools/image-streams/rabbitmq.yaml, infrastructure/openshift/tools/image-streams/redis-exporter.yaml, infrastructure/openshift/tools/image-streams/redis.yaml
- Adds `importPolicy.scheduled=true` on image stream so remotely updated versions are pulled down. this helps with high level tagged images like `docker.io/eclipse-temurin:11`
- Adds build configuration for form-recognizer-layout
=> Update build configs and image stream definitions

src/backend/TrafficCourts/Citizen.Service/Services/Impl/CitizenDocumentService.cs, src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-digital-case-file/jj-dispute-digital-case-file.component.ts
=> TCVP-2028 Fix DCF search page and minor bugs

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> release 1.57.0

src/backend/TrafficCourts/Citizen.Service/Validators/DisputeCountValidator.cs, src/backend/TrafficCourts/Citizen.Service/Validators/NoticeOfDisputeValidator.cs, src/backend/TrafficCourts/Test/Citizen.Service/Validators/DisputeCountValidatorTest.cs, src/backend/TrafficCourts/Test/Citizen.Service/Validators/NoticeOfDisputeValidatorTest.cs, src/backend/TrafficCourts/Test/Citizen.Service/Validators/ValidatorTest.cs
- Adds validation rules for RequestTimeToPay to prevent `Unknown` when property is required
- Adds validation rules for RequestCourtAppearance to prevent `Unknown` when property is required
- Add initial unit tests
- Tidy up rule definitions to make them more readable by using private functions
- Unit Tests are not complete nor cover all validation logic
=> Update Dispute Validation

src/backend/TrafficCourts/Citizen.Service/Features/Disputes/Create.cs, src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.html, src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.ts, src/frontend/citizen-portal/src/app/services/notice-of-dispute.service.ts
=> TCVP-2291 dispute stepper fix for skip count

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> release 1.57.1

.gitops/charts/common-object-management-service.md, docker-compose.yml, infrastructure/openshift/common-object-management-service/deploymentconfig.yaml, src/backend/TrafficCourts/Citizen.Service/Validators/DisputeCountValidator.cs, src/backend/TrafficCourts/Staff.Service/Controllers/DocumentController.cs, src/backend/TrafficCourts/Staff.Service/Services/StaffDocumentService.cs, src/backend/TrafficCourts/Test/Citizen.Service/Validators/DisputeCountValidatorTest.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client.Test/RequestBuilderTest.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/RequestBuilder.cs, src/backend/TrafficCourts/TrafficCourts.Staff.Service.Test/Controllers/DocumentControllerTest.cs, src/backend/TrafficCourts/Workflow.Service/Consumers/SendEmailToDisputantConsumer.cs, src/frontend/staff-portal/src/app/api/api/document.service.ts, src/frontend/staff-portal/src/app/api/model/fileHistoryAuditLogEntryType.model.ts, src/frontend/staff-portal/src/app/api/model/fileMetadata.model.ts, src/frontend/staff-portal/src/app/api/swagger.json, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.ts
- add changes required for COMS version 0.4.0
- change openshift manifest to use tag version 0.4
- add readme document that COMS is not deployed via Helm
=> Add changes required for COMS 0.4.0

src/backend/TrafficCourts/Citizen.Service/Dockerfile, src/backend/TrafficCourts/Citizen.Service/Dockerfile.rhel8, src/backend/bc-gov-virus-scan/BCGov.VirusScan.Api/Dockerfile, src/backend/bc-gov-virus-scan/BCGov.VirusScan.Api/Dockerfile.rhel8, src/backend/bc-gov-virus-scan/entrypoint.sh
- change to use entrypoint.sh script for loading secrets/configuration
=> Add entrypoint script for loading secrets

.gitops/charts/README.md, .gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-online/charts/citizen-api/templates/deployment.yaml, .gitops/charts/traffic-court-test-values.yaml, .gitops/charts/virus-scan-dev-values.yaml, .gitops/charts/virus-scan-test-values.yaml, .gitops/charts/virus-scan/templates/deployment.yaml, .gitops/charts/virus-scan/values.yaml, src/backend/bc-gov-virus-scan/BCGov.VirusScan.Api/BCGov.VirusScan.Api.csproj, src/backend/bc-gov-virus-scan/BCGov.VirusScan.Api/Logging/EnvironmentVariableEnricher.cs, src/backend/bc-gov-virus-scan/BCGov.VirusScan.Api/Logging/EnvironmentVariableLoggerConfigurationExtensions.cs, src/backend/bc-gov-virus-scan/BCGov.VirusScan.Api/Monitoring/Timer.cs, src/backend/bc-gov-virus-scan/BCGov.VirusScan.Api/Program.cs, src/backend/bc-gov-virus-scan/BCGov.VirusScan.Api/appsettings.json
- Adjust log level to info from debug in test for Oracle Data API 
- Fix machine name logging in virus scan service
- Enable logging in virus scan service
- Enable metrics (sysdig) in virus can service
=> Virus scan updates

src/backend/TrafficCourts/Citizen.Service/Startup.cs, src/backend/TrafficCourts/Citizen.Service/TrafficCourts.Citizen.Service.csproj, src/backend/TrafficCourts/Common/Diagnostics/ITimerOperation.cs, src/backend/TrafficCourts/Common/Diagnostics/MeterExtension.cs, src/backend/TrafficCourts/Common/TrafficCourts.Common.csproj, src/backend/TrafficCourts/Staff.Service/Startup.cs, src/backend/TrafficCourts/Staff.Service/TrafficCourts.Staff.Service.csproj, src/backend/TrafficCourts/TrafficCourts.Common.Test/Diagnostics/MeterExtensionTest.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/Monitoring/ITimerOperation.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/Monitoring/Instrumentation.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/Monitoring/InstrumentedObjectManagementClient.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/Monitoring/Timer.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/Monitoring/ValueStopwatch.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/ObjectManagementService.cs, src/backend/TrafficCourts/Workflow.Service/Startup.cs
- Adds OpenTelemetry metrics for COMS operations. Core operations have explicit metrics, operations we are not using have a catch all.
=> Add opentelemetry metrics to coms client

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml
- Bumps version in helm chart to 1.57.3
=> Bump versions to 1.57.2 to 1.57.3

src/backend/bc-gov-virus-scan/BCGov.VirusScan.Api/Monitoring/ITimerOperation.cs, src/backend/bc-gov-virus-scan/BCGov.VirusScan.Api/Monitoring/Instrumentation.cs, src/backend/bc-gov-virus-scan/BCGov.VirusScan.Api/Monitoring/Timer.cs, src/backend/bc-gov-virus-scan/BCGov.VirusScan.Api/Services/VirusScanService.cs
- Changes metrics in virus scan service to use common instruments 
-
=> Change metrics to use common instruments with tags to differentiate

infrastructure/sysdig-readme.md
- Adds the beginning of a readme for sysdig/prometheus metrics
=> Add initial readme for sysdig / prometheus query

src/backend/TrafficCourts/Citizen.Service/Instrumentation/Instrumentation.cs, src/backend/TrafficCourts/Citizen.Service/Services/Impl/FormRecognizerService_2_1.cs, src/backend/TrafficCourts/Citizen.Service/Startup.cs, src/backend/TrafficCourts/Common/Diagnostics/ITimerOperation.cs, src/backend/TrafficCourts/Common/Diagnostics/Timer.cs, src/backend/TrafficCourts/TrafficCourts.Common.Test/Diagnostics/MeterExtensionTest.cs, src/backend/TrafficCourts/Workflow.Service/Instrumentation/Instrumentation.cs, src/backend/TrafficCourts/Workflow.Service/Services/EmailSenderService.cs, src/backend/TrafficCourts/Workflow.Service/Services/OracleDataApiService.cs, src/backend/TrafficCourts/Workflow.Service/Services/SmtpClientFactory.cs, src/backend/TrafficCourts/Workflow.Service/Startup.cs
- Adds metrics instrumentation for Oracle Data API
- Adds metrics instrumentation for SMTP (send email)
- Adds metrics instrumentation for Forms Recognizer 2.1
- Fixes error where disconnect may not be called if sending email throws exception
=> Instrument services

src/backend/oracle-data-api/src/main/resources/tco-openapi-spec.yaml, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.html, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.ts, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.ts, src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-hearing-inbox/jj-dispute-hearing-inbox.component.ts
- TCVP-2314, TCVP-2102, TCVP-2318
- [x ] My code follows the style guidelines of this project
=> TCVP-2314, TCVP-2102, TCVP-2318 Fix bugs preventing save of TCO Disputes

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> release 1.58.1

src/backend/TrafficCourts/TrafficCourts.Coms.Client/Monitoring/Instrumentation.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/Monitoring/InstrumentedObjectManagementClient.cs
- Fixes bug when time out exceptions or other exceptions were not being caught. The error was related to not awaiting the real client's call in the instrumentation wrapper. The old version was just returning the created task. The elapsed time metrics were probably wrong too.
=> Fix error instrumentation handling for COMS

src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.html, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.ts
- TCVP-1984 round fine amounts to nearest dollar surcharge also
=> TCVP-1984 round fine/ revised fine to dollar

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> release 1.58.2

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/JJDisputeMapper.java
=> updated court appearance mapper

src/frontend/citizen-portal/src/app/components/disputant-form/disputant-form.component.ts
=> TCVP-2251 update postal code validation

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> release 1.58.3

src/backend/TrafficCourts/Staff.Service/Authentication/Scopes.cs, src/backend/TrafficCourts/Staff.Service/Controllers/JJController.cs, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/OutgoingEmailMapper.java, src/backend/oracle-data-api/src/main/resources/occm-openapi-spec.yaml, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/OutgoingEmailMapperTest.java
=> TCVP-2307, TCVP-2346 Insert email history failing in test, confirm error

src/backend/TrafficCourts/Citizen.Service/Controllers/DisputesController.cs, src/backend/TrafficCourts/Messaging/MessageContracts/SearchDispute.cs, src/backend/TrafficCourts/Staff.Service/Mappers/Mapper.cs, src/backend/TrafficCourts/Test/Citizen.Service/Mappings/NoticeOfDisputeToMessageContractMappingTests.cs, src/backend/TrafficCourts/Test/Messaging/SearchDisputeResponseTest.cs, src/backend/TrafficCourts/Test/Workflow.Service/Consumers/SearchDisputeConsumerTest.cs, src/backend/TrafficCourts/TrafficCourts.Staff.Service.Test/Mappers/MapperTest.cs, src/backend/TrafficCourts/Workflow.Service/Consumers/SearchDisputeConsumer.cs, src/backend/TrafficCourts/Workflow.Service/Consumers/SendEmailToDisputantConsumer.cs, src/backend/TrafficCourts/Workflow.Service/Mappings/MappingProfile.cs, src/backend/TrafficCourts/Workflow.Service/Services/IOracleDataApiService.cs, src/backend/TrafficCourts/Workflow.Service/Services/OracleDataApiService.cs
- (Citizen API) Cleans up the citizen api's dispute controller to:
- log errors more cleanly
- handle dispute not found better
- handle error getting dispute better
- add comments with future todos
- add comments indicating where exceptions could be thrown in big controller actions
- (Messaging) Updates SearchDisputeResponse
- add `IsNotFound` property
- add `NotFound` static property for getting not found instance
- add `Error` static property for getting error instance
- add unit test to ensure `NotFound` and `Error` objects are created correctly
- (Staff API) `Mapper.ToDisputeApproved(...)` 
- add check if `NoticeOfDisputeGuid is not null` to avoid argument null exception in case of error
- clean up formatting of street address
- …
=> Clean up citizen ticket search logic, add logging and  handle not found

src/backend/TrafficCourts/Common/Features/Lookups/StatuteLookupService.cs
…call
- Fixed bug where information log message is always written, fixed `(Count >= 1)` to `(Count > 1)`
- Consolidate call to fetch data (maybe this is good or bad)
=> Fix erroneous log message when one value returned

.gitops/charts/traffic-court-test-values.yaml
- Makes change to the deployment for the TEST environment to use on premise Form Recognizer
- This configuration change has been deployed to TEST already.
Note: This change required a updated of the configuration key `FormRecognizer__Endpoint` which is in Vault. It was changed from the end point found in the Azure portal (Form recognizer instance > Keys and Endpoint > Endpoint) to the internally configured service, `http://ocr-form-recognizer-api.0198bb-test.svc.cluster.local:5000/`
=> change to use form recognizer on premise

src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.html, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.ts, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.html
=> TCVP-2350, TCVP-2353 updates to dispute count / dispute UX

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> release 1.59.0

src/backend/TrafficCourts/Citizen.Service/Services/OAuth/OAuthUserService.cs, src/frontend/citizen-portal/src/app/components/disputant-form/disputant-form.component.ts, src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.html, src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.ts, src/frontend/citizen-portal/src/app/services/violation-ticket.service.ts
=> TCVP-2331 fix base64 string conversion & dispute stepper updates

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> release 1.59.1

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> release 1.59.2

docker-compose.yml, src/frontend/citizen-portal/Dockerfile, src/frontend/citizen-portal/nginx-api-proxy-pass.conf, src/frontend/staff-portal/Dockerfile, src/frontend/staff-portal/nginx-api-proxy-pass.conf
- update docker build to no envsubst usage for staff portal, citizen portal
=> gettext not available

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> release 1.59.4

src/backend/TrafficCourts/Workflow.Service/Consumers/CreateDisputeInDatabaseConsumer.cs, src/frontend/citizen-portal/src/app/services/notice-of-dispute.service.ts, src/frontend/citizen-portal/src/app/services/violation-ticket.service.ts, src/frontend/citizen-portal/src/app/shared/components/resolution-header/resolution-header.component.ts
- TCVP-2347 these changes go with oracle changes to issued date. 
=> issued date updates

src/frontend/citizen-portal/src/app/services/violation-ticket.service.ts
=> one more utc

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> release 1.59.5

src/frontend/citizen-portal/src/app/components/disputant-form/disputant-form.component.html, src/frontend/citizen-portal/src/app/components/disputant-form/disputant-form.component.ts, src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.html, src/frontend/citizen-portal/src/app/services/notice-of-dispute.service.ts, src/frontend/citizen-portal/src/app/services/violation-ticket.service.ts
=> TCVP-2367, 2369 fix driving license number set to number not string

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> release 1.59.6

src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-hearing-inbox/jj-dispute-hearing-inbox.component.ts
- default to 'all jjs' and 'any date' for hearing inbox for ease of testing
=> TCVP-2305 jj, date filters for hearing inbox

.gitops/charts/traffic-court-test-values.yaml
…rets
- Changes dev to use on premise 2.1 model. Requires change to vault secrets.
=> Change dev to use Form Recognizer on premise. Requires changes to secrets

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml
- fixes prev commit where I changed test values
- changes dev to use on premise form recognizer
=> Fix deployment for dev, test Form Recognizer on prem

.gitops/charts/spilo-postgres-dev-values.yaml, docs/possible-oracle-errors.txt, infrastructure/openshift/tools/build-configs/clamav-build-bcgov.yaml, tools/coms-get-object-by-id.sql, tools/patroni.md
- add note on postgres database full / sync
- add some sql scripts for query COMS db
- add build config script
=> Some readme, scripts and add clamav build config

.gitops/charts/deploy-form-recognizer.ps1, .gitops/charts/form-recognizer-dev-values.yaml, .gitops/charts/form-recognizer-test-values.yaml, .gitops/charts/form-recognizer/templates/deployment.yaml, .gitops/charts/form-recognizer/values.yaml
- pull resource definitions to values file
- add deployment powershell script
- add dev and test values file for form recognizer
=> Form Recognizer : Move resources to values file per env, add dev and test values files

.gitops/charts/form-recognizer-dev-values.yaml, .gitops/charts/form-recognizer-test-values.yaml
=> doubled mem/cpu

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> release 1.60.1

src/frontend/staff-portal/src/app/components/staff-workbench/contact-info/contact-info.component.ts, src/frontend/staff-portal/src/app/components/staff-workbench/update-request-info/document-update-request-info/document-update-request-info.component.ts, src/frontend/staff-portal/src/app/components/staff-workbench/update-request-info/update-request-info.component.ts
=> TCVP-2133 wasnt saving DL province from E-ticket editing

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> release 1.60.2

src/frontend/citizen-portal/src/app/app.module.ts, src/frontend/citizen-portal/src/app/components/find-ticket/find-ticket.component.html, src/frontend/citizen-portal/src/app/components/find-ticket/find-ticket.component.scss, src/frontend/citizen-portal/src/app/components/find-ticket/find-ticket.component.ts, src/frontend/citizen-portal/src/app/shared/dialogs/image-ticket-not-found-dialog/image-ticket-not-found-dialog.component.html
- TCVP-2125 Ticket option text
=> TCVP-2125 email ticket option text

src/backend/TrafficCourts/Staff.Service/Controllers/JJController.cs, src/backend/TrafficCourts/Staff.Service/Services/IJJDisputeService.cs, src/backend/TrafficCourts/Staff.Service/Services/JJDisputeService.cs, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/JJDisputeControllerTest.java, src/frontend/staff-portal/src/app/api/api/jJ.service.ts, src/frontend/staff-portal/src/app/api/swagger.json, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.html, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.scss, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.html, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.ts, src/frontend/staff-portal/src/app/services/jj-dispute.service.ts
- TCVP-2406 Staff Portal set to concluded / cancelled for dispute based on finding
=> Feature/tcvp 2406 - Disputed Concluded or Cancelled in staff portal

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> release 1.60.3

src/frontend/citizen-portal/src/app/services/dispute.service.ts, src/frontend/citizen-portal/src/app/shared/dialogs/dispute-status-dialog/dispute-status-dialog.component.html, src/frontend/citizen-portal/src/app/shared/dialogs/dispute-status-dialog/dispute-status-dialog.component.ts
=> TCVP-2174 update pizza tracker for concluded/cancelled

src/frontend/staff-portal/src/app/components/staff-workbench/update-request-info/update-request-info.component.html
- TCVP-2410 submit button unavailable in Dispute Update Request
=> TCVP-2410 submit button unavailable in Dispute Update Request

src/frontend/citizen-portal/src/app/components/update-dispute/update-dispute.component.html, src/frontend/citizen-portal/src/app/services/dispute.service.ts
=> TCVP-2369 fix empty dispute counts

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> release 1.60.4

.gitops/charts/deploy-jaeger-aio.ps1, .gitops/charts/jaeger-aio/values.yaml
- bump jaeger version from 1.32 to 1.45
-
=> bump jaeger version from 1.32 to 1.45

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml
- Change version from 1.60.4 to 1.60.5
=> Change version from 1.60.4 to 1.60.5

src/backend/TrafficCourts/Common/Configuration/Extensions.cs
- Filter out tracing calls to /metrics
=> Filter out metric traces

src/backend/TrafficCourts/Citizen.Service/Services/Tickets/Search/Extensions.cs, src/backend/TrafficCourts/Citizen.Service/Services/Tickets/Search/Rsi/Authentication/LoggingHandler.cs
- Add delegating handler to log the request for troubleshooting.
=> Add debug logging for RSI ticket search

.gitops/charts/traffic-court-online/values.yaml
- removed H2_DATASOURCE
- Added SPRING_SLEUTH_ENABLED to support Jaeger traces
- Sorted environment variables by name
=> Remove H2, add SPRING_SLEUTH_ENABLED, sort by name

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml
=> Dev rsi search and 1.60.6 release

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/backend/TrafficCourts/Citizen.Service/Services/Tickets/Search/Rsi/RoadSafetyTicketSearchService.cs
- Fix invoice parsing on ticket search against RSI
=> Fix road safety ticket search

src/frontend/citizen-portal/src/app/services/violation-ticket.service.ts, src/frontend/staff-portal/src/app/components/staff-workbench/ticket-info/ticket-info.component.ts
=> remove 30 day check

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> release 1.61.1

src/backend/TrafficCourts/Workflow.Service/Consumers/DisputeUpdateRequestAcceptedConsumer.cs, src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.html, src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.ts, src/frontend/citizen-portal/src/app/shared/models/dispute-form.model.ts
=> Bug/tcvp 2399, TCVP-2413

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> release 1.61.2

src/frontend/citizen-portal/src/app/api/model/disputeStatus.model.ts, src/frontend/citizen-portal/src/app/api/swagger.json, src/frontend/citizen-portal/src/app/services/dispute.service.ts, src/frontend/citizen-portal/src/app/shared/dialogs/dispute-status-dialog/dispute-status-dialog.component.ts, src/frontend/staff-portal/src/app/api/model/disputeListItemStatus.model.ts, src/frontend/staff-portal/src/app/api/model/disputeStatus.model.ts, src/frontend/staff-portal/src/app/api/model/excludeStatus.model.ts, src/frontend/staff-portal/src/app/api/swagger.json
-TCVP-2427 Show dispute status Concluded in Pizza Tracker
- [] Bug fix (non-breaking change which fixes an issue)
Display a variety of dispute statuses in pizza tracker
=> Bug/tcvp 2427 Show dispute status concluded in pizza tracker

src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.html, src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.ts, src/frontend/citizen-portal/src/app/components/find-dispute/find-dispute.component.html, src/frontend/citizen-portal/src/app/components/find-dispute/find-dispute.component.ts, src/frontend/citizen-portal/src/app/components/find-ticket/find-ticket.component.ts, src/frontend/citizen-portal/src/app/core/core.module.ts, src/frontend/citizen-portal/src/app/core/interceptors/loading.interceptor.ts, src/frontend/citizen-portal/src/app/shared/services/file-utils.service.ts
=> TCVP-2373 add upload rules

src/backend/TrafficCourts/Citizen.Service/Mappings/MappingProfile.cs, src/frontend/citizen-portal/src/app/components/update-dispute-landing/update-dispute-landing.component.ts, src/frontend/staff-portal/src/app/components/staff-workbench/update-request-info/update-request-info.component.html, src/frontend/staff-portal/src/app/components/staff-workbench/update-request-info/update-request-info.component.ts
- TCVP-2412, TCVP-2404 update request bug with contact type, submit / cancel button changes
=> bug/TCVP-2412, bug/TCVP-2404 update request bugs

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> release 1.62.0

src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.ts
=> fixes for ticket scan

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> release 1.62.1

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml
- Bump version to 1.62.3
- Depends on #1248 
=> Release 1.62.3

src/frontend/citizen-portal/proxy.conf.json, src/frontend/citizen-portal/src/app/components/dispute-submit-success/dispute-submit-success.component.html, src/frontend/citizen-portal/src/app/components/dispute-submit-success/dispute-submit-success.component.ts, src/frontend/citizen-portal/src/app/services/notice-of-dispute.service.ts, src/frontend/citizen-portal/src/app/shared/enums/dispute-form-mode.ts, src/frontend/citizen-portal/src/app/store/dispute/dispute.effects.ts
- TCVP-2093 submit without email address
=> submit without email

src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.html, src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.ts, src/frontend/citizen-portal/src/app/services/violation-ticket.service.ts, src/frontend/citizen-portal/src/app/shared/services/file-utils.service.ts
=> TCVP-2373 update upload rules

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> release 1.62.5

src/backend/TrafficCourts/Citizen.Service/Controllers/DisputesController.cs, src/frontend/citizen-portal/proxy.conf.json, src/frontend/citizen-portal/src/app/components/update-dispute-landing/update-dispute-landing.component.ts, src/frontend/citizen-portal/src/app/services/dispute.service.ts, src/frontend/citizen-portal/src/app/store/dispute/dispute.effects.ts
- TCVP-2442 Unable to authenticate for update
=> TCVP-2442 unable to authenticate for update

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
- release 1.62.6
- [x ] Version change
=> release 1.62.6

src/frontend/citizen-portal/nginx.conf
- TCVP-2448 Insecure Referrer policy
Submit a new application with email verification, submit update requests.  Email verification not working but could be due to localhost issues, lets build dev and find out.
=> wava scan fix one

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/proxy.conf.json, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> release 1.63.0

src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-wr-inbox/jj-dispute-wr-inbox.component.html, src/frontend/staff-portal/src/app/components/staff-workbench/dispute-decision-inbox/dispute-decision-inbox.component.html
- TCVP-2452 disputant name missing on decision validation, jj wr inbox
=> use occam disputant name

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> release 1.63.1

src/frontend/staff-portal/src/app/app.module.ts, src/frontend/staff-portal/src/app/services/auth.service.ts, src/frontend/staff-portal/src/app/shared/components/header/header.component.ts, src/frontend/staff-portal/src/assets/config/keycloak.config.json
=> TCVP-2445 auto refresh access token

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> release 1.63.2

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> release 1.64.0

src/frontend/staff-portal/src/app/services/auth.service.ts
=> TCVP-2445 refresh token update

src/frontend/staff-portal/src/app/services/auth.service.ts
=> TCVP-2445 login update

README.md, docker-compose.yml, src/frontend/citizen-portal/proxy.conf.json, src/frontend/staff-portal/proxy.conf.json
- Adjust ports to follow convention
=> Adjust host port mappings.

src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-digital-case-file/jj-dispute-digital-case-file.component.html, src/frontend/staff-portal/src/app/services/jj-dispute.service.ts
- TCVP-2440
- Fixed the status view in DCF search
- If the status of dispute is changed to "Require Court Hearing", the DCF file search should show the status as "Require Court Hearing"
=> TCVP-2440: Missing Dispute (Staff and JJ Workbenches)

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Create release 1.65.1

src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.html, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.scss, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.ts
- TCVP-2470
- Added tooltip and fixed search
- Hover on the text to see the tooltip
- The search needs to work
=> TCVP-2470: JJ DCF Hearing - Update Findings Dropdown: ‘Not guilty as charged but guilty of lesser/included off…'

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Release 1.66.0

src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.html
- TVCP-2470
- Fixed the text message
- Checking the not guilty text message
=> TCVP-2470: Fixed the text

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml
=> Release 1.66.1

docker-compose.yml, src/frontend/staff-portal/proxy.conf.json
- update docker-compose config
- local docker using HTTP instead of HTTPS
=> Update config files

src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.html
- TCVP-2456
- Added tooltip
- Hover on MVA list under Driving Prohibition to check the tooltip
=> TCVP-2456: JJ DCF Hearing- Widen the dropdown display - Hover-overs not working

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, gitops/cleanup-image-streams.sh, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Release 1.67.0

src/backend/TrafficCourts/Citizen.Service/Services/Tickets/Search/Rsi/IRoadSafetyTicketSearchApi.cs
=> TCVP-2512 Update API paths

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Bump to 1.67.1 release

src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.html
- TCVP-2344
- Fixing display of fine and surcharge
- Change the fine amount in count and check on staff portal DCF with ticket number to check the amount is reflected correctly
=> TCVP-2344: DEV: Staff Workbench - Decision Validation Victim Surcharge is Wrong

src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApi.v1_0.json, src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApiClient.g.cs, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/JJDisputeCourtAppearanceRoP.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/JJDisputeRemark.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/JJDisputedCount.java, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.html, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.scss
- TCVP-2496
- Added multi line text
- Updated the max length of comment fields to 4000 chars
- Open the ticket and enter the multiline text in comments under court appearance. It should be saved and retrieved as entered
=> TCVP-2496: DCF: Court Appearance Comments Field Multiple Lines 

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Release 1.68.1

gitops/charts/README.md, gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml
TCVP-2505
Updated Citizen API helm charts for both DEV and TEST to reference the new Form Recognizer composite model.
=> TCVP-2505 Updated helm charts with composite model id

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Release 1.69.0

src/frontend/citizen-portal/src/app/components/initiate-resolution/initiate-resolution.component.html
- TCVP-1455
Tested in localhost to see user changes as requested in UX
=> TCVP-1455 correct link from PayBC to tickets.gov.bc.ca

src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.ts, src/frontend/citizen-portal/src/app/shared/components/resolution-footer/resolution-footer.component.html, src/frontend/citizen-portal/src/app/shared/dialogs/dispute-not-found-dialog/dispute-not-found-dialog.component.html, src/frontend/citizen-portal/src/app/shared/dialogs/dispute-status-dialog/dispute-status-dialog.component.html, src/frontend/citizen-portal/src/app/shared/dialogs/image-requirements-dialog/image-requirements-dialog.component.html, src/frontend/citizen-portal/src/app/shared/dialogs/ticket-not-found-dialog/ticket-not-found-dialog.component.html, src/frontend/citizen-portal/src/app/shared/dialogs/wait-for-ocr-dialog/wait-for-ocr-dialog.component.html
- TCVP-2151 
Ran in localhost and DEV to verify user requested changes to UX
=> TCVP-2151 use email addy instead of phone numbers

src/frontend/staff-portal/src/app/components/staff-workbench/ticket-inbox/ticket-inbox.component.ts
=> TCVP-2481 hide statuses = processing, rejected and cancelled

src/frontend/citizen-portal/src/app/components/initiate-resolution/initiate-resolution.component.html
- TCVP-1141
Clicked on all four links
=> TCVP-1141 eticket and isc ticket links

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Release 1.70.0

src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.html, src/frontend/citizen-portal/src/app/services/notice-of-dispute.service.ts
=> TCVP-2275 update lawyer validations

src/frontend/citizen-portal/src/app/components/disputant-form/disputant-form.component.html, src/frontend/citizen-portal/src/app/components/disputant-form/disputant-form.component.ts, src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.ts, src/frontend/citizen-portal/src/app/shared/models/dispute-form.model.ts
=> TCVP-2458 update contact lawyer information

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Release 1.71.0

src/backend/TrafficCourts/TrafficCourts.Staff.Service.Test/Services/IntegrationTestFactAttribute.cs, src/backend/TrafficCourts/TrafficCourts.Staff.Service.Test/Services/PrintDigialCaseFile/Print.cs
- disables the container based tests by default. developer can configure user secrets to testing.
=> Disable container based integration tests by default

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Release 1.71.1

gitops/charts/common-object-management-service/templates/deployment.yaml
- Add missing `_ENABLED` environment variables required for COMS to work.
Re-deployed COMS to dev via helm
=> Add missing env variables that enable features in COMS

src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-digital-case-file/jj-dispute-digital-case-file.component.html, src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-digital-case-file/jj-dispute-digital-case-file.component.scss, src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-digital-case-file/jj-dispute-digital-case-file.component.ts, src/frontend/staff-portal/src/app/components/staff-workbench/dispute-decision-inbox/dispute-decision-inbox.component.html, src/frontend/staff-portal/src/app/components/staff-workbench/ticket-inbox/ticket-inbox.component.html, src/frontend/staff-portal/src/app/components/staff-workbench/update-request-inbox/update-request-inbox.component.html
TCVP-2550 This PR:
- adds search filter functionality to the DCF tab on the Staff Workbench, just like the other 3 tabs. 
- updated the look n' feel of the search result table to match the other 3 tabs
- updated the date formate to yyyy-MM-dd to be consistent on all 4 tabs
=> TCVP-2550 Added search filters to DCF tab

src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-digital-case-file/jj-dispute-digital-case-file.component.html, src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-digital-case-file/jj-dispute-digital-case-file.component.scss, src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-digital-case-file/jj-dispute-digital-case-file.component.ts, src/frontend/staff-portal/src/app/components/staff-workbench/dispute-decision-inbox/dispute-decision-inbox.component.html, src/frontend/staff-portal/src/app/components/staff-workbench/dispute-decision-inbox/dispute-decision-inbox.component.scss, src/frontend/staff-portal/src/app/components/staff-workbench/dispute-decision-inbox/dispute-decision-inbox.component.ts, src/frontend/staff-portal/src/app/components/staff-workbench/ticket-inbox/ticket-inbox.component.html, src/frontend/staff-portal/src/app/components/staff-workbench/ticket-inbox/ticket-inbox.component.ts, src/frontend/staff-portal/src/app/components/staff-workbench/update-request-inbox/update-request-inbox.component.html, src/frontend/staff-portal/src/app/components/staff-workbench/update-request-inbox/update-request-inbox.component.ts, src/frontend/staff-portal/src/app/shared/utils/date-util.ts
TCVP-2550 
- Added filters to the Decision Validation tab on the Staff Workbench
- Made the resultset match the style of the other tabs
- Fixed duplicate code - Reused Date logic on other tabs
=> TCVP-2550 Added search filters to Decision Validation tab

src/frontend/citizen-portal/src/app/components/find-ticket/find-ticket.component.html
=> TCVP-1986 Wording change - OCR erroring on background text / Date of Service

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Update version to 1.72.0

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-online/charts/workflow-service/templates/deployment.yaml, gitops/charts/traffic-court-online/charts/workflow-service/values.yaml, gitops/charts/traffic-court-test-values.yaml
- fixes db connection string values in workflow service helm chart
=> traffic-court-online helm fix - saga settings

src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-file-history/jj-file-history.component.html
=> TCVP-1847 PR 1

src/frontend/citizen-portal/src/app/components/find-dispute/find-dispute.component.html, src/frontend/citizen-portal/src/app/components/find-dispute/find-dispute.component.scss, src/frontend/citizen-portal/src/app/shared/components/resolution-footer/resolution-footer.component.html
=> TCVP-2159 PR 1

src/frontend/staff-portal/src/app/app-routing.module.ts
=> Add routing

src/frontend/citizen-portal/src/app/components/find-dispute/find-dispute.component.html, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.html, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.scss, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.ts
- TCVP-2514
- Added the change plea
=> TCVP-2514 PR 1

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Release 1.73.0

src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-digital-case-file/jj-dispute-digital-case-file.component.html
TCVP-2402 updated UI to match Jira requirements.
Updated not found message to "Ticket not found" when there are no records to display (either specifically filtering or not).
=> TCVP-2402 updated UI message when viewing no records

src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.html, src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.ts
=> TCVP-2476 Add submitting message

src/frontend/citizen-portal/src/app/components/disputant-form/disputant-form.component.html, src/frontend/citizen-portal/src/app/components/disputant-form/disputant-form.component.ts, src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.ts
=> TCVP-2458 update contact info

src/backend/TrafficCourts/Workflow.Service/Startup.cs
- fixes issue where the default schema is assumed to be `public`, see https://github.com/npgsql/efcore.pg/issues/2917
=> Fix issue with default schema of db migration table

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml
=> Change keycloak token endpoint variable to OAuth__TokenEndpoint

gitops/charts/postgres/postgres-test-application-values.yaml
=> fix conflicting backup schedule

src/backend/TrafficCourts/TrafficCourts.Coms.Client/ComsJsonContext.cs, src/backend/TrafficCourts/TrafficCourts.Core/Http/Models/ModelSerializerContext.cs
- Fixes the code coverage error during build with respect to files not found
=> Exclude JsonSerializer generated code from code coverage

docker-compose.yml
=> CDOGS Addition to Staff API

src/frontend/citizen-portal/src/app/components/find-ticket/find-ticket.component.html
=> TCVP-1986 fix typo

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Release 1.74.1

.env.template
- Adds new required parameters
=> Add cdogs required  env vars for docker compose

src/frontend/citizen-portal/src/app/components/scan-ticket/scan-ticket.component.html, src/frontend/citizen-portal/src/app/components/scan-ticket/scan-ticket.component.ts
=> TCVP-2543 try fix image

src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-hearing-inbox/jj-dispute-hearing-inbox.component.html, src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-hearing-inbox/jj-dispute-hearing-inbox.component.ts, src/frontend/staff-portal/src/app/shared/modules/ngx-material/ngx-material.module.ts
=> TCVP-2455 fix styles

src/frontend/citizen-portal/src/app/components/dispute-submit-success/dispute-submit-success.component.html, src/frontend/citizen-portal/src/app/components/dispute-ticket-summary/dispute-ticket-summary.component.html, src/frontend/citizen-portal/src/app/components/dispute-ticket-summary/dispute-ticket-summary.component.ts, src/frontend/citizen-portal/src/app/components/email-verification-required/email-verification-required.component.html
=> TCVP-1787 bug fix

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Release 1.74.2

src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.ts
- TCVP-2573
- Added the refresh lock functionality
=> TCVP-2573 PR 1

src/frontend/citizen-portal/src/app/shared/components/page/page.component.ts
=> TCVP-2592 temp fix with disable screen blocking

src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.html, src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.scss, src/frontend/citizen-portal/src/app/services/notice-of-dispute.service.ts
TCVP-1224
- aligned declared message above submit button, now always bold
- added new sentence to warning.
- removed "handwritten" word from warning popup.
Declared message now uses bootstrap breakpoints:
=> TCVP-1224 Citizen Portal UI changes

src/frontend/citizen-portal/src/app/components/initiate-resolution/initiate-resolution.component.html
TCVP-2572
- updated external link on citizen-portal after finding a dispute.
=> TCVP-2572 Updated external link

src/frontend/citizen-portal/src/app/services/violation-ticket.service.ts
TCVP-2569
Added javascript check so the code doesn't crash. The code is expecting a forEach() method, but when uploading a wrong filetype, there is no such method.
=> TCVP-2569 Trying to upload an xls was crashing javascript

src/frontend/citizen-portal/src/app/components/disputant-form/disputant-form.component.html
TCVP-2577
Added new warning box to step 1 of the stepper.
=> TCVP-2577 Added warning box to stepper

src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.html, src/frontend/citizen-portal/src/app/components/dispute-ticket-summary/dispute-ticket-summary.component.html
TCVP-2579 Text changes only.
Per business requirements, updated textual wording a few places on the citizen portal.
=> TCVP-2579 citizen-portal wording changes

src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.html
TCVP-2578 Simple wording change on stepper, part 2, when no court hearing.
=> TCVP-2578 citizen-portal wording changes

src/backend/TrafficCourts/Citizen.Service/Services/Tickets/Search/Common/Invoice.cs
- Adds returning form number from the RSI service
=> TCVP-2563 - Add form number to RSI service

src/frontend/citizen-portal/src/app/components/find-ticket/find-ticket.component.ts, src/frontend/citizen-portal/src/app/components/initiate-resolution/initiate-resolution.component.html
- TCVP-2539
- Addressed the change (number 2) mentioned in the ticket to remove all references to 'resolution', and replace with 'dispute'.
- Addressed the last comment on the ticket.
- Other requested changes have been already in place. 
=> TCVP-2539 Citizen Portal Wording Updates

src/frontend/citizen-portal/nginx.conf
- TCVP-2543
- fix image security issue
- tested with local docker citizen-portal
=> TCVP-2543 fix image

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Release 1.75.0

src/frontend/citizen-portal/src/app/components/landing/landing.component.html, src/frontend/citizen-portal/src/app/components/tco-page/tco-page.component.html
=> TCVP-2669 PR 1

src/frontend/citizen-portal/src/app/components/ticket-landing/ticket-landing.component.html
=> TCVP-2670 Update Dispute Ticket - Start Page

src/frontend/citizen-portal/src/app/components/scan-ticket/scan-ticket.component.html
=> TCVP-2672 Update Violation Ticket Upload Image page

src/frontend/citizen-portal/src/app/components/initiate-resolution/initiate-resolution.component.html
=> TCVP-2673 Update Violation Ticket Details page

src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.html
=> TCVP-2677 Update WR Additional Info

src/frontend/citizen-portal/src/app/shared/dialogs/dispute-status-dialog/dispute-status-dialog.component.html
=> TCVP-2684 Update Dispute Status Tracker

src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.html
=> TCVP-2678 Update Hearing Counts Review page

src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.html, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.scss, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.ts, src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-hearing-inbox/jj-dispute-hearing-inbox.component.html, src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-hearing-inbox/jj-dispute-hearing-inbox.component.ts, src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-wr-assignments/jj-dispute-wr-assignments.component.html, src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-wr-assignments/jj-dispute-wr-assignments.component.ts, src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-wr-inbox/jj-dispute-wr-inbox.component.html, src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-wr-inbox/jj-dispute-wr-inbox.component.ts
=> TCVP-2601 display accident and Multiple Officers

gitops/charts/traffic-court-online/values.yaml, gitops/charts/traffic-court-test-values.yaml, src/backend/TrafficCourts/TrafficCourts.Core/Http/TokenRefreshService.cs
Changes the url for "Understand My Ticket" in the test env
- TCVP-2621 - Test TCO website should point to test solution explorer
=> TCVP-2621 - change "Understand My Ticket" for test env

src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApiOperationMetrics.cs, src/backend/TrafficCourts/Staff.Service/Startup.cs, src/backend/TrafficCourts/TrafficCourts.Core.Test/Diagnostics/OperationMetricsTest.cs, src/backend/TrafficCourts/TrafficCourts.Core/Diagnostics/OperationMetrics.cs, src/backend/TrafficCourts/TrafficCourts.Core/Diagnostics/Timer.cs, src/backend/TrafficCourts/Workflow.Service/Startup.cs
=> Adjust metrics for oracle data api

src/frontend/staff-portal/src/app/components/staff-workbench/ticket-info/ticket-info.component.html, src/frontend/staff-portal/src/app/components/staff-workbench/ticket-info/ticket-info.component.ts, src/frontend/staff-portal/src/app/services/lookups.service.ts, src/frontend/staff-portal/src/app/services/violation-ticket.service.ts
TCVP-2553
- Fixed bug where the statutes where showing as invalid even though they were valid on the TicketValidation screen
- Per Jira request, removed filtering statutes by ACT - now only by section/subsection/paragraph/sub-paragraph
=> TCVP-2553 Fixed statute lookup

src/frontend/citizen-portal/src/app/components/landing/landing.component.html, src/frontend/citizen-portal/src/assets/i18n/en.json, src/frontend/citizen-portal/src/assets/i18n/fr.json
=> TCVP-2669 Update Tickets.gov.bc.ca Home Page

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Release 1.78.1

src/backend/TrafficCourts/Citizen.Service/Startup.cs, src/backend/TrafficCourts/Staff.Service/Startup.cs, src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/Startup.cs, src/backend/TrafficCourts/Workflow.Service/Startup.cs
- Add missing time provider registration
=> Add missing time provider registration

src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApiOperationMetrics.cs, src/backend/TrafficCourts/TrafficCourts.Core.Test/Diagnostics/OperationMetricsTest.cs, src/backend/TrafficCourts/TrafficCourts.Core/Diagnostics/OperationMetrics.cs
- Trying to fix oracle data api metrics genertion
=> Trying to fix oracle data api metrics genertion

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Release 1.78.2

src/backend/TrafficCourts/Citizen.Service/Models/Disputes/DisputantContactInformation.cs, src/backend/TrafficCourts/Citizen.Service/Models/Disputes/Dispute.cs, src/backend/TrafficCourts/Citizen.Service/Models/Disputes/NoticeOfDispute.cs, src/backend/TrafficCourts/Messaging/MessageContracts/SubmitNoticeOfDispute.cs, src/backend/TrafficCourts/Staff.Service/Mappers/Mapper.cs, src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/Models/TcoDisputeTicket.cs, src/frontend/citizen-portal/src/app/components/create-notice-of-dispute/create-notice-of-dispute.component.html, src/frontend/citizen-portal/src/app/components/disputant-form/disputant-form.component.html, src/frontend/citizen-portal/src/app/components/disputant-form/disputant-form.component.ts, src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.html, src/frontend/citizen-portal/src/app/components/update-dispute/update-dispute.component.html, src/frontend/citizen-portal/src/assets/i18n/en.json, src/frontend/citizen-portal/src/assets/i18n/fr.json, src/frontend/staff-portal/src/app/components/staff-workbench/contact-info/contact-info.component.html, src/frontend/staff-portal/src/app/components/staff-workbench/contact-info/contact-info.component.ts
- [TCVP-2674](https://justice.gov.bc.ca/jira/browse/TCVP-2674)
- Updated contact information page by removing some text, changing some wording and making some fields optional.
- Refactored some properties in Citizen API models such as `NoticeOfDispute` to manage nullable fields better.
- Updated NoticeOfDispute related models to allow submission of null phone number, driver's licence number and driver's licence province.
- Updated logic in Citizen Portal contact information page to allow selecting empty driver's licence province by keeping the default selection as BC.
- Updated staff portal to allow submission of null phone number, driver's licence number and driver's licence province to ARC.
if your change is a breaking change, please …
=> TCVP-2674 Update Contact Information Page Data Submission

src/frontend/citizen-portal/src/assets/countries_list.json, src/frontend/staff-portal/src/assets/countries_list.json
- [TCVP-2674](https://justice.gov.bc.ca/jira/browse/TCVP-2674)
- Based on Lana's comment on the Jira ticket, added missing countries to the `countries_list.json` with hardcoded IDs and values since the new countries to be added are not available from Justin yet in DEV and TEST.
- Confirmed that IDs assigned as hardcoded do not exist in Justin currently in DEV.
=> TCVP-2674 Update Countries List

src/frontend/staff-portal/src/app/components/staff-workbench/ticket-info/ticket-info.component.html, src/frontend/staff-portal/src/app/components/staff-workbench/ticket-info/ticket-info.component.ts, src/frontend/staff-portal/src/app/core/utils/string-utils.class.ts, src/frontend/staff-portal/src/app/services/lookups.service.ts, src/frontend/staff-portal/src/app/services/violation-ticket.service.ts, src/frontend/staff-portal/src/assets/i18n/en.json, src/frontend/staff-portal/src/assets/i18n/fr.json
TCVP-2660 ACT is now required for statute lookup - may be MVA or MVR
Now, when typing in the Count X fields, MVA or MVR will preceed the statute to aid in finding the correct lookup value.
=> TCVP-2660 ACT is now required for statute lookup

src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.html, src/frontend/citizen-portal/src/assets/i18n/en.json, src/frontend/citizen-portal/src/assets/i18n/fr.json
- [TCVP-2675](https://justice.gov.bc.ca/jira/browse/TCVP-2675)
- Updated the wording on the WR Counts Review page.
- NOTE: Addition of the mandatory signature box will be on a separate PR. This covers all the other wording changes.
=> TCVP-2675 Update WR Counts Review Page Wording

src/frontend/citizen-portal/src/app/components/update-dispute-landing/update-dispute-landing.component.ts, src/frontend/citizen-portal/src/app/services/dispute.service.ts
- TCVP-2686
- "Email address not yet verified" popup
=> TCVP-2686 "Email address not yet verified" popup

src/backend/TrafficCourts/Messaging/LoggingExtensions.cs, src/backend/TrafficCourts/Workflow.Service/Sagas/VerifyEmailAddressSagaStateMachine.cs, src/backend/TrafficCourts/Workflow.Service/TrafficCourts.Workflow.Service.csproj
- Change when the saga is initialized
=> Email Verification failures

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Release 1.78.3

src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.html, src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.scss, src/frontend/citizen-portal/src/assets/i18n/en.json, src/frontend/citizen-portal/src/assets/i18n/fr.json
TCVP-2680 Legal Review text changes
- updated text, moved to i18n files
=> TCVP-2680 Legal Review Changes

src/frontend/citizen-portal/src/app/components/update-dispute/update-dispute.component.html, src/frontend/citizen-portal/src/app/components/update-dispute/update-dispute.component.ts, src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-wr-inbox/jj-dispute-wr-inbox.component.ts, src/frontend/staff-portal/src/app/components/staff-workbench/ticket-info/ticket-info.component.ts, src/frontend/staff-portal/src/app/services/jj-dispute.service.ts, src/frontend/staff-portal/src/app/services/violation-ticket.service.ts
=> TCVP-2585 fix update dispute

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Release 1.78.5

src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.html
TCVP-2681 Legal review changes - remove warning text when submitting a dispute.
=> TCVP-2681 Legal review - remove warning text box

src/frontend/citizen-portal/src/app/components/dispute-ticket-summary/dispute-ticket-summary.component.html, src/frontend/citizen-portal/src/assets/i18n/en.json, src/frontend/citizen-portal/src/assets/i18n/fr.json
=> TCVP-2682 Update Hearing Ticket Request Overview - Not Guilty

src/frontend/citizen-portal/src/assets/i18n/en.json, src/frontend/citizen-portal/src/assets/i18n/fr.json
=> TCVP-2683 Update Hearing Ticket Request Overview - Guilty

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Release 1.79.0

gitops/charts/traffic-court-dev-values.yaml
=> Ticket Search Type Config Change

src/frontend/citizen-portal/src/app/shared/components/resolution-footer/resolution-footer.component.html
=> TCVP-2671 Update Start a Traffic Ticket Dispute page

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Release 1.80.0

src/frontend/citizen-portal/nginx.conf
=> TCVP-2585 BC Services Card: Cannot see Update Dispute screen after authenticating

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Release 1.80.1

src/frontend/staff-portal/src/app/api/api/jJ.service.ts
=> TCVP-1583 hotfix print DCF

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Release 1.81.0

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Release 1.81.2

src/frontend/staff-portal/src/app/api/api/dispute.service.ts, src/frontend/staff-portal/src/app/api/model/fileHistory.model.ts, src/frontend/staff-portal/src/app/api/model/fileHistoryAuditLogEntryType.model.ts, src/frontend/staff-portal/src/app/api/swagger.json, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.ts, src/frontend/staff-portal/src/app/components/staff-workbench/contact-info/contact-info.component.ts, src/frontend/staff-portal/src/app/components/staff-workbench/ticket-info/ticket-info.component.ts, src/frontend/staff-portal/src/app/services/dispute.service.ts
=> TCVP-2637 new staff comment

src/backend/TrafficCourts/TrafficCourts.Core.Test/Http/OidcConfidentialClientTest.cs, src/backend/TrafficCourts/TrafficCourts.Core/Http/OidcConfidentialClient.cs, src/backend/TrafficCourts/TrafficCourts.Core/Http/OidcConfidentialClientDelegatingHandler.cs, src/backend/TrafficCourts/TrafficCourts.Core/Http/TagProvider.cs, src/backend/TrafficCourts/TrafficCourts.Core/Http/TokenRefreshService.cs
- adds and enhances the logging around the token retrieval, caching and use
=> TCVP-2642 enhance logging of access token handling

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Release 1.81.3

src/backend/TrafficCourts/Staff.Service/appsettings.json, src/backend/TrafficCourts/TrafficCourts.Core/Http/OidcConfidentialClient.cs, src/backend/TrafficCourts/TrafficCourts.Core/Http/TagProvider.cs, src/backend/TrafficCourts/TrafficCourts.Core/Http/TokenCache.cs, src/backend/TrafficCourts/TrafficCourts.Core/Http/TokenRefreshService.cs, src/backend/TrafficCourts/Workflow.Service/appsettings.json
- Adjust the default log level to Warning for infrastructure sources
- Adjust log messages to remove parameters and move to properties
=> Adjust logging

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Release 1.81.4

infrastructure/openshift/dev/ords-proxy-route.yaml, infrastructure/openshift/dev/ords-proxy.yaml
- extracts ords route from the ords deployment/service manifest allowing drop/recreate the latter without messing with the route.
=> Ords proxy

src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute-updates/jj-dispute-updates.component.html
TCVP-2497 Fixed display of translated text
=> TCVP-2497 Fixed bug with display of Dispute Update table

src/backend/TrafficCourts/Staff.Service/Services/JJDisputeService.cs, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.ts, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.ts
- [TCVP-2705](https://justice.gov.bc.ca/jira/browse/TCVP-2705)
- Fixed the issue with submitting and displaying incorrect total fine amount for dispute counts.
- Fixed the issue with revised date label is not shown after saving/updating counts.
- Fixed the issue with jj dispute count's description of offence was not properly displayed as full statute text after saving/updating dispute refreshes page.
=> TCVP-2705 fix total fine amount, description of offence and revised due date label

src/backend/TrafficCourts/TrafficCourts.Coms.Client/Metadata.cs
- Change the internal metadata names to match [changes](https://github.com/bcgov/common-object-management-service/blob/master/app/src/db/migrations/20230427000000_006-metadata-fix.js) introduced by the coms project.
=> Change internal names for coms metadata properties

src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.html, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.scss, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.html
=> TCVP-2740: JJ DCF - Styling/Table Size Issues

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Release 1.83.0

src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.html, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.scss
=> TCVP-2470: JJ DCF - Styling/Table Size Issues

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Release 1.83.1

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Release 1.83.2

src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.scss, src/frontend/staff-portal/src/app/shared/dialogs/confirm-reason-dialog/confirm-reason-dialog.component.html
- [TCVP-2701](https://justice.gov.bc.ca/jira/browse/TCVP-2701)
- Fixed the broken text
=> TCVP-2701: Return to Judicial Justice/Require Court Hearing/Adjourn-Continue Text Entry Broken

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Release 1.83.3

src/frontend/staff-portal/src/app/components/staff-workbench/contact-info/contact-info.component.html, src/frontend/staff-portal/src/app/components/staff-workbench/contact-info/contact-info.component.ts, src/frontend/staff-portal/src/app/components/staff-workbench/ticket-info/ticket-info.component.html, src/frontend/staff-portal/src/app/components/staff-workbench/ticket-info/ticket-info.component.ts, src/frontend/staff-portal/src/app/shared/dialogs/confirm-reason-dialog/confirm-reason-dialog.component.scss
- [TCVP-2715](https://justice.gov.bc.ca/jira/browse/TCVP-2715)
- Removed required field for Province and Phone
=> TCVP-2715: Field "Province/state" is not marked as required in UI, but it's impossible to save it empty if Address is not Canada/USA

src/backend/TrafficCourts/Citizen.Service/Services/Tickets/Search/TicketSearchService.cs, src/backend/TrafficCourts/Common/LegalSection.cs, src/backend/TrafficCourts/TrafficCourts.Common.Test/LegalSectionTest.cs
- Parses the section and subsection of the data returned by RSI ticket search
- Adds unit tests on the LegalSection type to ensure parsing/formatting working
=> TCVP-2563 parse the section information if it has value

src/backend/TrafficCourts/Common/Authorization/KeycloakAuthorizationHandler.cs
- adjusts the logging to help troubleshoot the authentication problems
=> Adjust logging in staff api authorization to assist with troubleshooting

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Release 1.84.0

src/backend/TrafficCourts/Common/Authorization/KeycloakAuthorizationHandler.cs
- missed logging the `scope` parameter.
=> Add missing scope parameter

src/frontend/staff-portal/package.json, src/frontend/staff-portal/yarn.lock
=> Keycloak Upgrade

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Release 1.84.1

src/backend/TrafficCourts/Citizen.Service/Services/Impl/FormRecognizerService_2_1.cs, src/backend/TrafficCourts/Common/Models/OcrViolationTicket.cs
Fixed reference to old OCR models
=> Fixed OCR reference to old models

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Release 1.84.3

src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-hearing-inbox/jj-dispute-hearing-inbox.component.ts, src/frontend/staff-portal/src/app/components/staff-workbench/ticket-inbox/ticket-inbox.component.html, src/frontend/staff-portal/src/app/components/staff-workbench/ticket-inbox/ticket-inbox.component.ts, src/frontend/staff-portal/src/app/components/table-filters/table-filters.component.html, src/frontend/staff-portal/src/app/components/table-filters/table-filters.component.ts
=> TCVP-2647, 2736 fixes

src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.html, src/frontend/staff-portal/src/assets/i18n/en.json, src/frontend/staff-portal/src/assets/i18n/fr.json
=> TCVP-2763 DCF wordings update

src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.html, src/frontend/citizen-portal/src/assets/i18n/en.json, src/frontend/citizen-portal/src/assets/i18n/fr.json
- TCVP-2680
- Modified label text
=> TCVP-2680: Update Hearing Additional Info

src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-digital-case-file/jj-dispute-digital-case-file.component.html, src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-hearing-inbox/jj-dispute-hearing-inbox.component.html, src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-wr-assignments/jj-dispute-wr-assignments.component.html, src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-wr-inbox/jj-dispute-wr-inbox.component.html, src/frontend/staff-portal/src/app/components/staff-workbench/dispute-decision-inbox/dispute-decision-inbox.component.html, src/frontend/staff-portal/src/app/components/staff-workbench/ticket-inbox/ticket-inbox.component.html, src/frontend/staff-portal/src/app/components/staff-workbench/update-request-inbox/update-request-inbox.component.html
- TCVP-2757
- Fixed the parameter
=> TCVP-2757: javascript:void()

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Release 1.85.0

.github/workflows/ci-acs-form-recognizer-init.yml
TCVP-2739 modified the CI script to automatically build and tag the current Form Recognizer 3.0 model and push it to an OpenShift ImageStream.
This build task is triggered whenever there is a commit to the `tools/form-recognizer/3.0/**` folder
=> Updated CI to initialize Form Recognizer model

src/backend/TrafficCourts/TrafficCourts.Core/Http/TagProvider.cs, src/backend/TrafficCourts/TrafficCourts.Core/Http/TokenRefreshService.cs
- Try to refresh if the token refresh failed. In test, keycloak returned service unavailable,
```
Level: Warning
MessageTemplate: Access token request failed, returning null
Properties: { [[-]](https://splunk.jag.gov.bc.ca/en-US/app/search/search?earliest=-7d%40h&latest=now&q=search%20index%3Dtest_traffic_court%20%22Properties.Application%22%3D%22TrafficCourts.Staff.Service%22%20%22Properties.SourceContext%22%3D%22TrafficCourts.Common.Authentication.KeycloakTokenRefreshService%22&display.page.search.mode=smart&dispatch.sample_ratio=1&sid=1709000446.165460_C14801B1-EF08-42EB-BEBE-8105A4061D9A#)
Application: TrafficCourts.Staff.Service
EventId: { [[-]](https://splunk.jag.gov.bc.ca/en-US/app/search/search?earliest=-7d%40h&latest=now&q=search% …
```
=> Handle situation token could not be refreshed, be sure to try again

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Release 1.86.0

src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/OracleDataApiExtensions.cs, src/backend/TrafficCourts/Staff.Service/Mappers/Mapper.cs, src/backend/TrafficCourts/TrafficCourts.Staff.Service.Test/Mappers/MapperTest.cs
If a disputed count is either fine reduction or request time to pay, the dispute type should be 'F' for fine, other 'A' for allegation.
- fixes the mapping from tco disputed count to the arc dispute type, either A or F.
=> TCVP-2786 Fix ARC dispute type

src/backend/TrafficCourts/Citizen.Service/Services/Impl/FormRecognizerService_2022_08_31.cs, src/backend/TrafficCourts/Citizen.Service/Validators/FormRecognizerValidator.cs
TCVP-2737
Added a timeout to Form Recognizer 3.0 just like we did with 2.1
=> TCVP-2737 Added timeout and logging to FR3.0

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Release 1.86.2

gitops/charts/traffic-court-dev-values.yaml
Updated helm values for new OCR
=> Updated default DEV values for FR

src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.html, src/frontend/staff-portal/src/app/components/staff-workbench/ticket-inbox/ticket-inbox.component.ts, src/frontend/staff-portal/src/app/shared/models/table-filter-options.model.ts, src/frontend/staff-portal/src/assets/i18n/en.json, src/frontend/staff-portal/src/assets/i18n/fr.json
=> TCVP-2647, 2763 fixes

gitops/charts/form-recognizer-3.0/templates/deployment-layout.yaml, gitops/charts/form-recognizer-3.0/templates/service-custom-template.yaml, gitops/charts/form-recognizer-3.0/templates/service-layout.yaml, gitops/charts/traffic-court-test-values.yaml
TCVP-2739
Update helm chart with a few tweaks needed to get it deployable to TEST.
This chart is still missing secrets and the main route configuration.
=> TCVP-2739 updated Form Recognizer 3.0 helm chart

src/frontend/citizen-portal/src/app/services/violation-ticket.service.ts, src/frontend/citizen-portal/src/app/shared/dialogs/image-requirements-dialog/image-requirements-dialog.component.html, src/frontend/citizen-portal/src/app/shared/dialogs/image-ticket-not-found-dialog/image-ticket-not-found-dialog.component.html
- TCVP-2791
- Added file type formats and validation
=> TCVP-2791: Citizen Portal: Don't Allow PDF Uploads to OCR / Update Text

src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-wr-assignments/jj-dispute-wr-assignments.component.ts
=> TCVP-2762 fix WR assignment team reset

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Release 1.87.1

src/backend/TrafficCourts/Citizen.Service/TrafficCourts.Citizen.Service.csproj, src/backend/TrafficCourts/Staff.Service/TrafficCourts.Staff.Service.csproj, src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/TrafficCourts.Arc.Dispute.Service.csproj, src/backend/TrafficCourts/Workflow.Service/TrafficCourts.Workflow.Service.csproj
- Upgrade `AutoMapper` from 12.0.1 to 13.0.1
- Remove `AutoMapper.Extensions.Microsoft.DependencyInjection` 12.0.1, DI code now exists in `AutoMapper`
- Remove unit test library `FluentAssertions` from Staff Service
=> AutoMapper Update

src/backend/TrafficCourts/Workflow.Service/Consumers/DisputeApprovedConsumer.cs, src/backend/TrafficCourts/Workflow.Service/Consumers/TagProvider.cs
- Map MVAR to MVR when sending to ARC
- Added precondition checks to avoid sending bad data to ARC
- Improved logging by using source generator and logging out common properties
=> TCVP-2795 Map MVAR to MVR when sending to ARC

src/backend/TrafficCourts/Citizen.Service/Services/Tickets/Search/TicketSearchService.cs
Small enhancement to log why some RSI search results are dropped.
=> TCVP-2651 Improved logging with RSI search results

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Release 1.88.0

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Release 1.88.1

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Release 1.88.2

src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.html, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.ts
=> TCVP-2467 try fix blank out fine amount and due date when not guilty

src/frontend/citizen-portal/src/app/components/ticket-landing/ticket-landing.component.html
=> TCVP-2776 Add dispute options to 'Do you want to dispute your traffic ticket?' page

src/frontend/staff-portal/src/app/components/staff-workbench/ticket-inbox/ticket-inbox.component.ts
=> TCVP-2647 fix included 'Concluded' records

src/backend/TrafficCourts/Staff.Service/Services/PrintDigitalCaseFileService.cs
- Fixes the issue mentioned in the last comment of this ticket: [TCVP-1583](https://justice.gov.bc.ca/jira/browse/TCVP-1583)
- Fixed an issue with the adjusted fine amount was being displayed incorrectly on the PDF if the 'include surcharge' option is selected.
=> TCVP-1583 Print DCF fix adjusted and surcharge amount

src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.html, src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.ts
- [TCVP-2711](https://justice.gov.bc.ca/jira/browse/TCVP-2711)
=> TCVP-2711: Update Dispute - Change Dispute Stepper Updates

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Release 1.89.0

gitops/charts/form-recognizer-3.0/README.md
TCVP-2827
For some reason Form Recognizer randomly corrupted itself. 
Using the FR3 API to manually analyze a document:
```
Exception
Azure.RequestFailedException: A transient error has occurred. Please try again. Status: 503 (Service Unavailable) ErrorCode: ServiceUnavailable
```
This PR adds support documentation that can help resolve the issue - by re-initializing the PVC.
=> TCVP-2827 added support documentation to init FR3 PVC

src/frontend/citizen-portal/src/app/components/ticket-landing/ticket-landing.component.html, src/frontend/citizen-portal/src/app/components/ticket-landing/ticket-landing.component.scss, src/frontend/citizen-portal/src/app/components/ticket-landing/ticket-landing.component.ts
=> TCVP-2776 styles update

src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.html, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.ts, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-file-history/jj-file-history.component.ts
=> TCVP-2637 show staff comments in file history

src/backend/TrafficCourts/TrafficCourts.OracleDataApi/OracleDataApiExtensions.cs
- Add EnumTypeConverter to IoC container so AutoMapper can create it
=> Add EnumTypeConverter to IoC container

src/backend/TrafficCourts/Messaging/LoggingExtensions.cs, src/backend/TrafficCourts/Staff.Service/Controllers/DisputeController.cs, src/backend/TrafficCourts/Staff.Service/Models/Disputes/GetDisputeCountResponse.cs, src/backend/TrafficCourts/Staff.Service/Services/DisputeService.cs, src/backend/TrafficCourts/Staff.Service/Services/IDisputeService.cs
- Adds ability to fetch the number of disputes with the given status.
=> Add get dispute count action

src/frontend/citizen-portal/src/app/components/disputant-form/disputant-form.component.html, src/frontend/citizen-portal/src/assets/i18n/en.json, src/frontend/citizen-portal/src/assets/i18n/fr.json
=> TCVP-2810 Update Given Name field for Corporate Disputes

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Release 1.90.0

src/frontend/staff-portal/src/app/components/paging/paging.component.html, src/frontend/staff-portal/src/app/components/paging/paging.component.scss, src/frontend/staff-portal/src/app/components/staff-workbench/ticket-inbox/ticket-inbox.component.html, src/frontend/staff-portal/src/app/components/staff-workbench/ticket-inbox/ticket-inbox.component.scss, src/frontend/staff-portal/src/app/components/table-filters/table-filters.component.html
=> TCVP-2771: Update front-end

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Release 1.90.1

src/frontend/staff-portal/src/scss/app.scss, src/frontend/staff-portal/src/scss/overrides/typography.scss
=> TCVP-2589 fix printing

src/backend/TrafficCourts/Citizen.Service/Controllers/DisputesController.cs
=> BC Services Login

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Release 1.90.2

src/backend/TrafficCourts/Workflow.Service/Services/EmailTemplates/DisputantEmailUpdateSuccessfulTemplate.cs, src/backend/TrafficCourts/Workflow.Service/Services/EmailTemplates/DisputeUpdateRequestAcceptedTemplate.cs, src/backend/TrafficCourts/Workflow.Service/Services/EmailTemplates/DisputeUpdateRequestReceivedTemplate.cs, src/backend/TrafficCourts/Workflow.Service/Services/EmailTemplates/DisputeUpdateRequestRejectedTemplate.cs, src/backend/TrafficCourts/Workflow.Service/Services/EmailTemplates/RejectedDisputeEmailTemplate.cs
- [TCVP-2815](https://justice.gov.bc.ca/jira/browse/TCVP-2815)
- Updated wording for auto-generated emails from workflow service.
=> TCVP-2815 Update email wording

src/frontend/citizen-portal/src/app/components/landing/landing.component.html
- [TCVP-2809](https://justice.gov.bc.ca/jira/browse/TCVP-2809)
=> TCVP-2809: TCO Snowplow report - Manage Dispute bar missing 

src/frontend/citizen-portal/src/app/components/disputant-form/disputant-form.component.html, src/frontend/staff-portal/src/app/components/staff-workbench/contact-info/contact-info.component.html, src/frontend/staff-portal/src/app/components/staff-workbench/ticket-info/ticket-info.component.html
- [TCVP-2875](https://justice.gov.bc.ca/jira/browse/TCVP-2875)
=> TCVP-2875: Phone Number Masking Issue

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Release 1.90.3

src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-file-history/jj-file-history.component.ts
=> TCVP-2869 fix jj dispute records not showing

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Release 1.90.4

src/frontend/staff-portal/src/app/components/staff-workbench/contact-info/contact-info.component.ts, src/frontend/staff-portal/src/app/components/staff-workbench/ticket-info/ticket-info.component.ts
=> Postal Code required fix

gitops/charts/rabbitmq/values-test.yaml, gitops/charts/traffic-court-online/charts/arc-dispute-api/templates/pdb.yaml, gitops/charts/traffic-court-online/charts/citizen-api/templates/pdb.yaml, gitops/charts/traffic-court-online/charts/citizen-web/templates/pdb.yaml, gitops/charts/traffic-court-online/charts/oracle-data-api/templates/pdb.yaml, gitops/charts/traffic-court-online/charts/staff-api/templates/pdb.yaml, gitops/charts/traffic-court-online/charts/staff-web/templates/pdb.yaml, gitops/charts/traffic-court-online/charts/workflow-service/templates/pdb.yaml, gitops/charts/traffic-court-test-values.yaml
=> Production charts

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Release 1.90.6

src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.html, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-file-history/jj-file-history.component.ts
=> DCF View Fix

gitops/charts/coms/common-object-management-service/templates/pdb.yaml, gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-online/charts/arc-dispute-api/templates/pdb.yaml, gitops/charts/traffic-court-online/charts/citizen-api/templates/pdb.yaml, gitops/charts/traffic-court-online/charts/citizen-web/templates/pdb.yaml, gitops/charts/traffic-court-online/charts/oracle-data-api/templates/pdb.yaml, gitops/charts/traffic-court-online/charts/staff-api/templates/pdb.yaml, gitops/charts/traffic-court-online/charts/staff-web/templates/pdb.yaml, gitops/charts/traffic-court-online/charts/workflow-service/templates/pdb.yaml, gitops/charts/traffic-court-test-values.yaml, src/backend/TrafficCourts/Common/Configuration/Extensions.cs, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
- fixes pdb selector
- fixes checking of jaeger endpoint is valid
- bump for 1.90.7
=> fix pdb selectors

src/backend/TrafficCourts/Citizen.Service/Caching/Cache.cs, src/backend/TrafficCourts/Citizen.Service/Features/Disputes/Create.cs, src/backend/TrafficCourts/Citizen.Service/Features/Tickets/Search/Handler.cs, src/backend/TrafficCourts/Citizen.Service/Services/Impl/FormRecognizerService_2022_08_31.cs, src/backend/TrafficCourts/Citizen.Service/Services/Impl/FormRecognizerService_2_1.cs, src/backend/TrafficCourts/Citizen.Service/Services/Tickets/Search/Mock/EmbeddedMockDataProvider.cs, src/backend/TrafficCourts/Citizen.Service/Services/Tickets/Search/Mock/FileMockDataProvider.cs, src/backend/TrafficCourts/Citizen.Service/Services/Tickets/Search/Mock/MockTicketSearchService.cs, src/backend/TrafficCourts/Citizen.Service/Services/Tickets/Search/Rsi/RoadSafetyTicketSearchService.cs, src/backend/TrafficCourts/Citizen.Service/Services/Tickets/Search/TicketSearchService.cs, src/backend/TrafficCourts/Common/Configuration/Extensions.cs, src/backend/TrafficCourts/Staff.Service/Caching/Cache.cs, src/backend/TrafficCourts/Staff.Service/Services/RedisDisputeLockService.cs
=> Opentelemetry filter

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Release 1.90.8

src/backend/TrafficCourts/Citizen.Service/Caching/Cache.cs, src/backend/TrafficCourts/Citizen.Service/Services/Tickets/Search/Rsi/RoadSafetyTicketSearchService.cs, src/backend/TrafficCourts/Citizen.Service/Startup.cs, src/backend/TrafficCourts/Staff.Service/Caching/Cache.cs, src/backend/TrafficCourts/Staff.Service/Services/DisputeService.cs, src/backend/TrafficCourts/Staff.Service/Services/KeycloakService.cs, src/backend/TrafficCourts/Staff.Service/Startup.cs, src/backend/TrafficCourts/TrafficCourts.Core/Caching/FusionCacheExtensions.cs
- removes many of the configured default cache entry defaults which fixes the timeouts we were seeing
- simplify cache per service by removing named caches
- update cache keys to include area (keycloak, ticket-search, etc)
=> remove factory timeouts, remove named caches, change cache keys

gitops/charts/traffic-court-test-values.yaml
- sets the `REDIS_CLUSTER_NODES` for test deployment
=> add redis cluster nodes to test env

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Release 1.90.9

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-online/charts/arc-dispute-api/templates/deployment.yaml, gitops/charts/traffic-court-online/charts/citizen-api/templates/deployment.yaml, gitops/charts/traffic-court-online/charts/citizen-web/templates/deployment.yaml, gitops/charts/traffic-court-online/charts/oracle-data-api/templates/deployment.yaml, gitops/charts/traffic-court-online/charts/staff-api/templates/deployment.yaml, gitops/charts/traffic-court-online/charts/staff-web/templates/deployment.yaml, gitops/charts/traffic-court-online/charts/workflow-service/templates/deployment.yaml, gitops/charts/traffic-court-online/values.yaml, gitops/charts/traffic-court-test-values.yaml, infrastructure/openshift/redinsight/redisinsight.yaml
- update redis connection info in helm charts
- ensure services are set to rolling update create strategy
=> Update redis config, ensure services are set as rolling update

src/backend/TrafficCourts/Citizen.Service/Startup.cs, src/backend/TrafficCourts/Staff.Service/Startup.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/Monitoring/Diagnostics.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/ObjectManagementService.cs, src/backend/TrafficCourts/Workflow.Service/Startup.cs
- add activity traces to the coms service
=> add activity trace points for coms

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Release 1.91.0

src/frontend/citizen-portal/src/app/components/find-ticket/find-ticket.component.scss, src/frontend/citizen-portal/src/app/services/dispute.service.ts, src/frontend/citizen-portal/src/app/store/dispute/dispute.reducers.ts, src/frontend/citizen-portal/src/app/store/dispute/dispute.state.ts
=> TCVP-2880 update dispute back button return to ticket search

src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute-remarks/jj-dispute-remarks.component.ts, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.html, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-file-history/jj-file-history.component.ts
=> TCVP-2637 fix show comment in File Remarks

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
- Update version to 2.0.0-rc-1
=> Update version to 2.0.0-rc-1

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Bump release version to 2.0.0-rc-2

gitops/openshift/dev/README.md, gitops/openshift/dev/citizen-web-for-maintenance.yaml, gitops/openshift/prod/README.md, gitops/openshift/prod/citizen-web-for-maintenance.yaml, gitops/openshift/test/README.md, gitops/openshift/test/citizen-web-for-maintenance.yaml, gitops/openshift/tools/README.md
- adds maintenance routes for citizen app and instructions for dev, test and prod
=> Add routes and instructions for going to/from maintenance

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Release 2.0.0

src/frontend/citizen-portal/src/app/components/landing/landing.component.html, src/frontend/citizen-portal/src/app/components/landing/landing.component.ts
=> Banner Fix

gitops/charts/traffic-court-prod-values.yaml
Merge initial PROD values into main.
=> Merge initial PROD chart values

gitops/charts/traffic-court-prod-values.yaml
Updated PROD helm chart values
- citizen-api should reference FormRecognizer service, not route.
=> Updated prod values for citizen-api

src/backend/TrafficCourts/Citizen.Service/Services/Impl/FormRecognizerService_2022_08_31.cs
TCVP-2903
Updated logging in Citizen API to use the logger directly instead of string format.
=> TCVP-2903 Updated Citizen API logging

src/frontend/citizen-portal/src/app/components/disputant-form/disputant-form.component.html
=> TCVP-2883 Change Dispute Contact Info Change

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-online/charts/staff-web/templates/deployment.yaml, gitops/charts/traffic-court-prod-values.yaml, gitops/charts/traffic-court-test-values.yaml, src/frontend/citizen-portal/src/assets/app.config.json, src/frontend/staff-portal/src/assets/app.config.json
=> Release 2.0.2

tools/keycloak-user-initializer/pom.xml, tools/keycloak-user-initializer/src/main/java/ca/bc/gov/open/jag/tco/keycloakuserinitializer/service/KeycloakService.java, tools/keycloak-user-initializer/src/main/java/ca/bc/gov/open/jag/tco/keycloakuserinitializer/util/TcoUserDataLoader.java
- [TCVP-2900](https://justice.gov.bc.ca/jira/browse/TCVP-2900)
- Upgraded user initializer app to use java 17 and spring boot 3 which is compatible with the latest version of keycloak used in prod (23.0.7).
=> TCVP-2900 Upgrade User Initializer App

gitops/charts/traffic-court-online/charts/staff-web/templates/configmap.yaml, gitops/charts/traffic-court-online/charts/staff-web/templates/deployment.yaml, gitops/charts/traffic-court-online/charts/staff-web/values.yaml
- TCVP-2911 - fix helm chart to support fixing staff portal banner
=> Fix staff portal banner config into main

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-prod-values.yaml, gitops/charts/traffic-court-test-values.yaml
- Bump version for Release 2.0.3 
=> TCVP-2914 Release 2.0.3

src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.html, src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.ts, src/frontend/citizen-portal/src/app/core/services/form-utils.service.ts
=> TCVP-2879 block change dispute from WR to hearing

src/frontend/staff-portal/src/app/components/staff-workbench/ticket-info/ticket-info.component.ts
=> TCVP-2637 fix comments saving wrong field

gitops/openshift/prod/citizen-web-for-justice-proxy.yaml
- down merging hotfix into develop branch
- 
=> Down merge hotfix to develop : increase citizen portal timeout

src/backend/bc-gov-virus-scan/BCGov.VirusScan.Api/BCGov.VirusScan.Api.csproj, src/backend/bc-gov-virus-scan/BCGov.VirusScan.Api/Monitoring/Instrumentation.cs
- Updates dependencies on virus scan service
=> TCVP-2922 Update virus scan package dependencies

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-prod-values.yaml, gitops/charts/traffic-court-test-values.yaml
- down merge release/2.0.3 into develop
=> TCVP-2914 Release 2.0.3 into develop

src/frontend/citizen-portal/src/app/app.component.ts, src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.html, src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.scss, src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.ts, src/frontend/citizen-portal/src/app/components/find-dispute/find-dispute.component.html, src/frontend/citizen-portal/src/app/components/find-ticket/find-ticket.component.html, src/frontend/citizen-portal/src/app/components/find-ticket/find-ticket.component.ts, src/frontend/citizen-portal/src/app/components/initiate-resolution/initiate-resolution.component.scss, src/frontend/citizen-portal/src/app/components/tco-page/tco-page.component.scss, src/frontend/citizen-portal/src/app/shared/components/resolution-header/resolution-header.component.html
=> TCVP-2387 fix mobile layout

src/backend/TrafficCourts/Citizen.Service/Validators/FormRecognizerValidator.cs, src/backend/TrafficCourts/Test/Citizen.Service/Validators/FormRecognizerValidatorTest.cs
=> TCVP-2914 Sanitized whitespace characters on some OCR fields to develop

src/backend/TrafficCourts/Staff.Service/Services/JJDisputeService.cs
TCVP-2878
Added basic logging to help diagnose missing file tags in COMS.
=> TCVP-2878 Added logging to help with missing data in COMS

src/frontend/staff-portal/src/app/app.module.ts, src/frontend/staff-portal/src/app/components/staff-workbench/contact-info/contact-info.component.html, src/frontend/staff-portal/src/app/components/staff-workbench/ticket-info/ticket-info.component.html, src/frontend/staff-portal/src/app/components/staff-workbench/ticket-info/ticket-info.component.scss, src/frontend/staff-portal/src/app/components/staff-workbench/ticket-request/ticket-request.component.scss, src/frontend/staff-portal/src/app/components/staff-workbench/upload/upload.component.html, src/frontend/staff-portal/src/app/components/staff-workbench/upload/upload.component.scss, src/frontend/staff-portal/src/app/components/staff-workbench/upload/upload.component.ts
- [TCVP-2872](https://justice.gov.bc.ca/jira/browse/TCVP-2872)
=> TCVP-2872: Add Upload Documents Feature to Ticket Validation Screen

docker-compose.yml, src/backend/TrafficCourts/TrafficCourts.Coms.Client.Test/ServiceTests/GetFileAsync.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/Metadata.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/ObjectManagementService.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/TrafficCourts.Coms.Client.csproj
- fixes the problem with coms 0.4.2 where the metadata header keys were changed
=> TCVP-2823 Fix issue where files are missing filenames

src/backend/TrafficCourts/TrafficCourts.Coms.Client.Test/ComsContainers.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client.Test/ComsIntegrationTest.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client.Test/IntegrationTest.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client.Test/ServiceTests/GetFileAsync.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client.Test/TrafficCourts.Coms.Client.Test.csproj, src/backend/TrafficCourts/TrafficCourts.Coms.Client/Metadata.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/MetadataValidator.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/ObjectManagementService.cs, src/backend/TrafficCourts/TrafficCourts.Core/Domain/Models/DocumentProperties.cs
- adds some "integration tests" to validate coms service behavior
- fixes getting filename from file header vs file metadata
=> TCVP-2823 fix issue with getting document filename

src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.ts
=> TCVP-2467 Blank out fine amount and due date when not guilty

src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-hearing-inbox/jj-dispute-hearing-inbox.component.html, src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-hearing-inbox/jj-dispute-hearing-inbox.component.ts, src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-wr-inbox/jj-dispute-wr-inbox.component.html, src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-wr-inbox/jj-dispute-wr-inbox.component.ts, src/frontend/staff-portal/src/app/components/staff-workbench/dispute-decision-inbox/dispute-decision-inbox.component.html, src/frontend/staff-portal/src/app/components/staff-workbench/dispute-decision-inbox/dispute-decision-inbox.component.ts
=> TCVP-1617 fix sorting

gitops/charts/traffic-court-prod-values.yaml
- bumps default resources for workflow service to resolve OOM killed pods in prod
=> Increase the default resources for workflow service

src/backend/TrafficCourts/Citizen.Service/TrafficCourts.Citizen.Service.csproj, src/backend/TrafficCourts/Common/TrafficCourts.Common.csproj, src/backend/TrafficCourts/Staff.Service/TrafficCourts.Staff.Service.csproj, src/backend/TrafficCourts/TrafficCourts.Coms.Client/TrafficCourts.Coms.Client.csproj, src/backend/TrafficCourts/TrafficCourts.Core/TrafficCourts.Core.csproj, src/backend/TrafficCourts/TrafficCourts.Workflow.Service.Test/Sagas/VerifyEmailAddress/SagaTest.cs, src/backend/TrafficCourts/TrafficCourts.Workflow.Service.Test/TrafficCourts.Workflow.Service.Test.csproj
- Updates Neovolve.Logging.Xunit
- Updates Serilog.Sinks.Splunk
- Updates FluentValidation.DependencyInjectionExtensions
- Updates OpenTelemetry packages
=> Dotnet package updates

src/backend/TrafficCourts/Messaging/BusConfiguratorExtensions.cs, src/backend/TrafficCourts/Messaging/Configuration/RetryOptions.cs, src/backend/TrafficCourts/Workflow.Service/Consumers/TagProvider.cs, src/backend/TrafficCourts/Workflow.Service/Migrations/VerifyEmailAddressStateMigrations/20240423152745_allow-null.Designer.cs, src/backend/TrafficCourts/Workflow.Service/Migrations/VerifyEmailAddressStateMigrations/20240423152745_allow-null.cs, src/backend/TrafficCourts/Workflow.Service/Migrations/VerifyEmailAddressStateMigrations/20240423155052_remove-concurrency-token.Designer.cs, src/backend/TrafficCourts/Workflow.Service/Migrations/VerifyEmailAddressStateMigrations/20240423155052_remove-concurrency-token.cs, src/backend/TrafficCourts/Workflow.Service/Sagas/VerifyEmailAddressSagaState.cs, src/backend/TrafficCourts/Workflow.Service/Sagas/VerifyEmailAddressSagaStateMachine.cs, src/backend/TrafficCourts/Workflow.Service/Sagas/VerifyEmailAddressStateMap.cs
- adds missing db migration when fields set nullable
- removes the concurrency token that causes state update conflicts
- adjusts the message retry logic, previously was set to retry after 2 minutes witch is too long
=> TCVP-2932 Fix Send Email Verification failures

src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.ts
- [TCVP-2705](https://jag.gov.bc.ca/jira/browse/TCVP-2705)
- Fixed the rounding issue of the surcharge and fine amount to have it matching the total fine amount correctly.
=> TCVP-2705: Fix fine amount rounding

src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.ts, src/frontend/citizen-portal/src/app/store/dispute/dispute.reducers.ts
=> TCVP-2447 Fix Disputant Upload Rules

src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.html
=> TCVP-2767 DCF Update - Make Findings Sections Expandable

src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute-court-appearances/jj-dispute-court-appearances.component.html, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.html
=> TCVP-2471 JJ DCF Hearing - rename comments field to JJ endorsements

src/frontend/citizen-portal/src/app/services/violation-ticket.service.ts
=> TCVP-2940 fix error msg

src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.html
=> TCVP-2766 DCF Update - Change Offence Amt to Fine Amount

src/backend/TrafficCourts/TrafficCourts.Coms.Client.Test/ComsContainers.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client.Test/ComsIntegrationTest.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/Models.g.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/ObjectManagementClient.g.cs
- Fixes a bug that prevents a COMS file from being deleted. The source [OpenAPI Specification](https://github.com/bcgov/common-object-management-service/blob/v0.4.2/app/src/docs/v1.api-spec.yaml) has errors. This require manually editing the generated code.
I updated the [Test Containers](https://testcontainers.com/) tests that stands up postgres, minio and coms instances and makes calls to the coms library.
=> TCVP-2958 Fix error preventing deleting files

src/backend/TrafficCourts/Staff.Service/Mappers/Mapper.cs, src/backend/TrafficCourts/TrafficCourts.Staff.Service.Test/Mappers/MapperTest.cs
- [TCVP-2786](https://justice.gov.bc.ca/jira/browse/TCVP-2786)
- Updated dispute count type mapping logic based on the new requirements defined in ticket: TCVP-2786. 
- Added functionality to filter out skipped counts to not send them to ARC. 
- Updated the unit tests based on the new logic and added new ones.
Ran updated XUnit tests. Also, created a dispute with 3 different counts with one of them being skipped count and confirmed in the output ARC file the skipped count only included as adnotated count entry (no disputed count entry) as well as other disputes having correct dispute types.
=> TCVP-2786: Update Dispute Type Mapping for ARC

src/backend/TrafficCourts/Test/Arc.Dispute.Service/Controllers/TcoDisputeTicketControllerTests.cs, src/backend/TrafficCourts/Test/Arc.Dispute.Service/Mappings/MappingTests.cs, src/backend/TrafficCourts/Test/Arc.Dispute.Service/Services/ArcFileServiceTests.cs, src/backend/TrafficCourts/Test/TrafficCourts.Test.csproj, src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/Controllers/TcoDisputeTicketController.cs, src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/Mappings/DisputeTicketToArcFileRecordListConverter.cs, src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/Models/TcoDisputeTicket.cs, src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/Services/ArcFileService.cs, src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/Services/IArcFileService.cs
- Removes counts from ARC file that do not have an act specified
=> TCVP-2873 Remove dispute counts that do not have Act

src/backend/TrafficCourts/Staff.Service/Mappers/Mapper.cs, src/backend/TrafficCourts/TrafficCourts.Staff.Service.Test/Mappers/MapperTest.cs
=> TCVP-2786 update dispute type sent to arc

src/backend/TrafficCourts/Workflow.Service/Services/EmailTemplates/RejectedDisputeEmailTemplate.cs, src/frontend/staff-portal/src/app/components/staff-workbench/contact-info/contact-info.component.html, src/frontend/staff-portal/src/app/components/staff-workbench/ticket-info/ticket-info.component.html
- [TCVP-2589](https://justice.gov.bc.ca/jira/browse/TCVP-2589)
=> TCVP-2589 [XL] Ticket Validation - Remove 'Cancel' Functions - Upgrade 'Reject' Functions [PROD]

src/backend/TrafficCourts/Common/Authorization/AccessTokenPropagationExtensions.cs, src/backend/TrafficCourts/Common/Authorization/AccessTokenPropagationHandler.cs, src/backend/TrafficCourts/Common/Authorization/IKeycloakAuthorizationService.cs, src/backend/TrafficCourts/Common/Authorization/KeycloakAuthorizationHandler.cs, src/backend/TrafficCourts/Common/Authorization/KeycloakAuthorizationOptions.cs, src/backend/TrafficCourts/Common/Authorization/KeycloakAuthorizationService.cs, src/backend/TrafficCourts/Common/Authorization/KeycloakAuthorizationServiceCollectionExtensions.cs, src/backend/TrafficCourts/Common/TrafficCourts.Common.csproj, src/backend/TrafficCourts/Staff.Service/Authentication/Scopes.cs, src/backend/TrafficCourts/Staff.Service/Features/Permissions/ApplicationPermissions.cs, src/backend/TrafficCourts/Staff.Service/Features/Permissions/Permission.cs, src/backend/TrafficCourts/Staff.Service/Features/Permissions/PermissionDto.cs, src/backend/TrafficCourts/Staff.Service/Features/Permissions/PermissionsEndpoint.cs, src/backend/TrafficCourts/Staff.Service/Program.cs, src/backend/TrafficCourts/Staff.Service/Startup.cs, src/backend/TrafficCourts/Staff.Service/TrafficCourts.Staff.Service.csproj
- Adds service and API endpoint to fetch current user's permissions
=> TCVP-2687 Add service and endpoints for fetching permissions

src/backend/TrafficCourts/Staff.Service/Controllers/DisputeController.cs, src/backend/TrafficCourts/TrafficCourts.OracleDataApi/Client/V1/OracleDataApi.v1_0.json, src/backend/TrafficCourts/TrafficCourts.OracleDataApi/Client/V1/OracleDataApiClient.g.cs, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeController.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeService.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeControllerTest.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeServiceH2Test.java
- [TCVP-2997](https://justice.gov.bc.ca/jira/browse/TCVP-2997)
- Updated allowed statuses logic when changing the status of a dispute into Cancelled, Rejected and Processing based on the new business rules defined in the ticket. 
- Updated unit tests.
=> TCVP-2997: Update Status Change Logic

src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-hearing-inbox/jj-dispute-hearing-inbox.component.html, src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-hearing-inbox/jj-dispute-hearing-inbox.component.scss, src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-wr-assignments/jj-dispute-wr-assignments.component.html, src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-wr-assignments/jj-dispute-wr-assignments.component.scss, src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-wr-assignments/jj-dispute-wr-assignments.component.ts, src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-wr-inbox/jj-dispute-wr-inbox.component.html, src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-wr-inbox/jj-dispute-wr-inbox.component.scss, src/frontend/staff-portal/src/scss/app.scss
- [TCVP-1617](https://justice.gov.bc.ca/jira/browse/TCVP-1617)
=> TCVP-1617 QA - JJ Workbench - Table header and sorting issues [PROD]

src/frontend/citizen-portal/src/app/services/violation-ticket.service.ts
- [TCVP-2940](https://justice.gov.bc.ca/jira/browse/TCVP-2940)
=> TCVP-2940 Incorrect error message to disputant [PROD]

src/backend/TrafficCourts/Messaging/MessageContracts/DisputeCancelled.cs, src/backend/TrafficCourts/Staff.Service/Mappers/Mapper.cs, src/backend/TrafficCourts/Workflow.Service/Services/EmailTemplates/CancelledDisputeEmailTemplate.cs
- [TCVP-2589](https://justice.gov.bc.ca/jira/browse/TCVP-2589)
=> TCVP-2589 Ticket Validation - Upgrade 'Cancel' & 'Reject' Functions [PROD]

src/frontend/citizen-portal/src/app/services/violation-ticket.service.ts, src/frontend/citizen-portal/src/app/shared/dialogs/image-ticket-not-found-dialog/image-ticket-not-found-dialog.component.html
=> TCVP-3005 RSI Search Date Filter Not Working [PROD]

src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/Controllers/TcoDisputeTicketController.cs
- TCVP-2873
- Fixed a bug with generic type logger in 'TcoDisputeTicketController' which caused 500 error when submitting disputes to ARC.
=> TCVP-2873: Fix submit to ARC logger error

src/frontend/staff-portal/src/app/components/staff-workbench/contact-info/contact-info.component.ts, src/frontend/staff-portal/src/app/components/staff-workbench/ticket-info/ticket-info.component.ts
- [TCVP-2589](https://jag.gov.bc.ca/jira/browse/TCVP-2589)
=> TCVP-2589 fixed the message

src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-digital-case-file/jj-dispute-digital-case-file.component.scss
=> TCVP-3012 DCF Search - Missing Columns Arrows

src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.html, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.scss, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.ts
- [TCVP-2985](https://jag.gov.bc.ca/jira/browse/TCVP-2985)
=> TCVP-2985 updated the ui changes

src/backend/TrafficCourts/TrafficCourts.TicketSearch/Mock/EmbeddedMockDataProvider.cs, src/backend/TrafficCourts/TrafficCourts.TicketSearch/TicketSearchService.cs, src/frontend/staff-portal/src/app/components/staff-workbench/contact-info/contact-info.component.html
=> TCVP-2977 Display ICBC-provided ISC/eTicket Names on Ticket Validation screen [PROD]

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-prod-values.yaml, gitops/charts/traffic-court-test-values.yaml
- TCVP-2973 add ticket search type to staff api helm chart
=> TCVP-2973 add ticket search type to staff api

src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.html, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.scss, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.ts, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute-remarks/jj-dispute-remarks.component.ts, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.html, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.ts, src/frontend/staff-portal/src/app/shared/dialogs/confirm-dialog/confirm-dialog.component.html, src/frontend/staff-portal/src/app/shared/dialogs/confirm-dialog/confirm-dialog.component.scss
- [TCVP-2986](https://jag.gov.bc.ca/jira/browse/TCVP-2986)
=> TCVP-2986 DCF Screen Overhaul - JJ Decision [PROD]

src/frontend/citizen-portal/src/app/components/disputant-form/disputant-form.component.html, src/frontend/citizen-portal/src/app/components/disputant-form/disputant-form.component.scss, src/frontend/citizen-portal/src/assets/i18n/en.json, src/frontend/citizen-portal/src/assets/i18n/fr.json
- [TCVP-2975](https://jag.gov.bc.ca/jira/browse/TCVP-2975)
=> TCVP-2975 Update Contact Information Screen / WR Signature Text [PROD]

src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-hearing-inbox/jj-dispute-hearing-inbox.component.html, src/frontend/staff-portal/src/app/components/staff-workbench/dispute-decision-inbox/dispute-decision-inbox.component.html, src/frontend/staff-portal/src/app/components/staff-workbench/ticket-inbox/ticket-inbox.component.html, src/frontend/staff-portal/src/app/components/staff-workbench/update-request-inbox/update-request-inbox.component.html, src/frontend/staff-portal/src/app/components/staff-workbench/update-request-info/address-update-request-info/address-update-request-info.component.html, src/frontend/staff-portal/src/app/components/staff-workbench/update-request-info/count-update-request-info/count-update-request-info.component.html, src/frontend/staff-portal/src/app/components/staff-workbench/update-request-info/court-options-update-request-info/court-options-update-request-info.component.html, src/frontend/staff-portal/src/app/components/staff-workbench/update-request-info/document-update-request-info/document-update-request-info.component.html, src/frontend/staff-portal/src/app/components/staff-workbench/update-request-info/name-update-request-info/name-update-request-info.component.html, src/frontend/staff-portal/src/app/components/staff-workbench/update-request-info/phone-update-request-info/phone-update-request-info.component.html, src/frontend/staff-portal/src/app/components/staff-workbench/update-request-info/update-request-info.component.html, src/frontend/staff-portal/src/app/shared/dialogs/confirm-dialog/confirm-dialog.component.html
- [TCVP-2764](https://jag.gov.bc.ca/jira/browse/TCVP-2764)
=> TCVP-2764 Harmonize Date Format - Staff Workbench & DCF Search [WR]

src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.html, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute-court-appearances/jj-dispute-court-appearances.component.html, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute-updates/jj-dispute-updates.component.html, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.html, src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-digital-case-file/jj-dispute-digital-case-file.component.html
- [TCVP-2769](https://jag.gov.bc.ca/jira/browse/TCVP-2769)
=> TCVP-2769 Harmonize Date Format - DCF [WR]

src/backend/TrafficCourts/Citizen.Service/Services/Tickets/Search/Rsi/IRoadSafetyTicketSearchApi.cs, src/backend/TrafficCourts/TrafficCourts.TicketSearch/Rsi/IRoadSafetyTicketSearchApi.cs
- fixes issue where trailing slash now errors out in test.
=> Remove trailing slash on ticket search url

src/frontend/staff-portal/src/app/components/staff-workbench/contact-info/contact-info.component.html, src/frontend/staff-portal/src/app/components/staff-workbench/ticket-status/ticket-status.component.html
- Harmonized date format for 'submitted date' and 'violation date' fields to be 'dd-MMM-yyyy' on ticket validation view.
=> TCVP-3006: Harmonize date format for staff portal

src/frontend/staff-portal/angular.json, src/frontend/staff-portal/package.json, src/frontend/staff-portal/src/app/app.module.ts, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.html, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.scss, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.ts, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.html, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.scss, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.ts, src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-digital-case-file/jj-dispute-digital-case-file.component.ts, src/frontend/staff-portal/src/app/components/staff-workbench/dispute-decision-inbox/dispute-decision-inbox.component.ts, src/frontend/staff-portal/src/app/components/staff-workbench/update-request-inbox/update-request-inbox.component.ts, src/frontend/staff-portal/src/app/components/table-filters/table-filters.component.html, src/frontend/staff-portal/src/app/components/table-filters/table-filters.component.scss, src/frontend/staff-portal/src/app/components/table-filters/table-filters.component.ts, src/frontend/staff-portal/yarn.lock
- [TCVP-2764](https://jag.gov.bc.ca/jira/browse/TCVP-2764)
- [TCVP-2769](https://jag.gov.bc.ca/jira/browse/TCVP-2769)
=> UAT - Harmonize Date Format - Staff Workbench & DCF Search [WR]

src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.html, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.html, src/frontend/staff-portal/src/app/components/table-filters/table-filters.component.html
- [TCVP-2769](https://jag.gov.bc.ca/jira/browse/TCVP-2769)
=> TCVP-2769 UAT - Harmonize Date Format - DCF [WR]

src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.html, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.html, src/frontend/staff-portal/src/app/components/table-filters/table-filters.component.html, src/frontend/staff-portal/src/app/components/table-filters/table-filters.component.ts
- [TCVP-2764](https://jag.gov.bc.ca/jira/browse/TCVP-2764)
=> TCVP-2764 UAT - Harmonize Date Format - Staff Workbench & DCF Search [WR]

src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.ts, src/frontend/staff-portal/src/app/components/table-filters/table-filters.component.ts
- [TCVP-3045](https://jag.gov.bc.ca/jira/browse/TCVP-3045)
=> TCVP-3045 QA - Include Surcharge When Fine not Revised

gitops/charts/traffic-court-online/charts/staff-web/templates/deployment.yaml
- volume name changed to configuration
=> Court house volume name fix

src/backend/TrafficCourts/Staff.Service/Services/DisputeService.cs, src/backend/TrafficCourts/Staff.Service/Services/PrintDigitalCaseFileService.cs
- Ensure the ICBC data is loaded when creating the print DCF
- Make async calls in parallel
=> TCVP-3049 ensure ICBC is called for print DCF

gitops/charts/traffic-court-dev-values.yaml, gitops/charts/traffic-court-prod-values.yaml, gitops/charts/traffic-court-test-values.yaml
=> Update version tags for release 2.3.15

src/frontend/staff-portal/src/app/config/config.service.ts, src/frontend/staff-portal/src/tests/mocks/mock-config.service.ts
- getting the courthouse data on http get
=> Courthouse data fixed
