docker-compose.yml, src/frontend/citizen-portal/nginx.conf
- Moved the frontend from 4200 to 8080 on local docker
- no longer need demo because of mock and keycloak now disabled on frontend too
- added swagger endpoint
- changes were required to handle reverse-proxying properly
Built and tested locally
Updated dev and rebuild with new environmental variable for API_URL successfully
=> Added swagger, moved frontend port

src/backend/TrafficCourtsApi/DisputeApi.Web.Test/Auth/OAuthClientTest.cs, src/backend/TrafficCourtsApi/DisputeApi.Web.Test/Auth/OAuthHandlerTest.cs, src/backend/TrafficCourtsApi/DisputeApi.Web.Test/Auth/TokenServiceTest.cs, src/backend/TrafficCourtsApi/DisputeApi.Web.Test/DisputeApi.Web.Test.csproj, src/backend/TrafficCourtsApi/DisputeApi.Web.Test/Features/ApiResponseTest.cs, src/backend/TrafficCourtsApi/DisputeApi.Web.Test/Features/Disputes/Commands/CreateDisputeCommandHandlerTest.cs, src/backend/TrafficCourtsApi/DisputeApi.Web.Test/Features/Disputes/Commands/CreateOffenceDisputeCommandHandlerTest.cs, src/backend/TrafficCourtsApi/DisputeApi.Web.Test/Features/Disputes/Configuration/DisputeServiceConfigurationTest.cs, src/backend/TrafficCourtsApi/DisputeApi.Web.Test/Features/Disputes/DisputeControllerTest.cs, src/backend/TrafficCourtsApi/DisputeApi.Web.Test/Features/Disputes/DisputeServiceTest.cs, src/backend/TrafficCourtsApi/DisputeApi.Web.Test/Features/Disputes/Models/DisputeModelTest.cs, src/backend/TrafficCourtsApi/DisputeApi.Web.Test/Features/Disputes/Queries/GetAllDisputesQueryHandlerTest.cs, src/backend/TrafficCourtsApi/DisputeApi.Web.Test/Features/Disputes/Queries/GetDisputeQueryHandlerTest.cs, src/backend/TrafficCourtsApi/DisputeApi.Web.Test/Features/TicketLookup/TicketDisputeFromRsiServiceTest.cs, src/backend/TrafficCourtsApi/DisputeApi.Web.Test/Features/TicketLookup/TicketLookupHandleTest.cs, src/backend/TrafficCourtsApi/DisputeApi.Web.Test/Features/Tickets/Configuration/TicketServiceConfigurationTest.cs, src/backend/TrafficCourtsApi/DisputeApi.Web.Test/Features/Tickets/Models/TicketModelTest.cs, src/backend/TrafficCourtsApi/DisputeApi.Web.Test/Features/Tickets/TicketServiceTest.cs, src/backend/TrafficCourtsApi/DisputeApi.Web.Test/Features/Tickets/TicketsControllerTest.cs, src/backend/TrafficCourtsApi/DisputeApi.Web.Test/Health/DisputeApiHealthCheckTest.cs, src/backend/TrafficCourtsApi/DisputeApi.Web.Test/StartUpTest.cs, src/backend/TrafficCourtsApi/DisputeApi.Web.Test/Utils/AllowCirculationAutoDataAttribute.cs, src/backend/TrafficCourtsApi/DisputeApi.Web.Test/Utils/AutoMockAutoDataAttribute.cs, src/backend/TrafficCourtsApi/TrafficCourts.Common.Test/Configuration/SerilogLoggingTest.cs, src/backend/TrafficCourtsApi/TrafficCourts.Common.Test/Configuration/SplunkEventCollectorTest.cs, src/backend/TrafficCourtsApi/TrafficCourts.Common.Test/TrafficCourts.Common.Test.csproj
- This PR changes the unit test library from NUnit to xUnit.  xUnit handles isolation between tests better.
=> Change NUnit to xUnit, it is just better

docker-compose.yml
- Added `DB_CONNECTION_STRING` environment variable for postgres db connection string
=> Add DB_CONNECTION_STRING environment variable for postgres db

src/frontend/citizen-portal/nginx.conf
- removes the `/api` and `/swagger` locations from the nginx.conf that is added to the container. In future changes, we will re-add the `/api` location. `/swagger` should added via config map change per env.
=> Remove api and swagger locations from defailt nginx.conf

.github/workflows/pr-label.yml, src/backend/TrafficCourtsApi/DisputeApi.Web.Test/Features/Disputes/DisputeServiceTest.cs, src/backend/TrafficCourtsApi/DisputeApi.Web/Features/Disputes/DisputeService.cs
- Adjusts the dotnet unit test so that it does not use instance fields
=> Fix dotnet unit tests to try to avoid random failures

src/backend/TrafficCourtsApi/DisputeApi.Web.Test/Features/Disputes/DisputeServiceTest.cs, src/backend/TrafficCourtsApi/DisputeApi.Web.Test/Features/Tickets/TicketServiceTest.cs
When using In Memory database, if the same name is used, the database will be shared db contexts
=> Fix issue where duplicate key errors would occur randomly

src/frontend/citizen-portal/src/app/app-routing.module.ts, src/frontend/citizen-portal/src/main.ts
'enableProdMode' was still looking at the environment files. Update this to use config
=> 'enableProdMode' without using environment file

.github/workflows/main-deploy.yml, infrastructure/openshift/dev/citizen-web-configuration-configmap.yaml, infrastructure/openshift/test/tickets-test.gov.bc.ca-route.yaml, infrastructure/openshift/traffic-courts-online-app.yml
- Adds config map and volume mount for app.config.json
- Renames docker image name from `citizen-portal` to c`itizen-web`
=> Add config map for citizen-web, change image name

src/frontend/citizen-portal/nginx.conf
Comments out the Content-Security-Policy header preventing the OCR working. Need to have task to add this url or move OCR to backend.
=> disable CSP which prev OCR from working for demo session

src/frontend/citizen-portal/src/app/components/stepper/step-additional/step-additional.component.html, src/frontend/citizen-portal/src/app/components/stepper/step-additional/step-additional.component.ts, src/frontend/citizen-portal/src/app/services/dispute-form-state.service.ts
We removed requiredIfTrue as it would overwrite validators exactly when we didn't want to effect default ones.
- updates dynamic validators logic for input, select and checkbox on witnesses
- Now shows `Enter positive number` when a negative number typed
- Still shows `Required`
Ran through no witnesses called, 1 witness selected from dropdown, and witnesses selected on inputs. Meanwhile testing the bug for typing a manual negative number. 
=> updates dynamic validators logic on witnesses inputs

src/backend/TrafficCourts/Common/Configuration/SerilogExtensions.cs
- disable min level of information when sending to splunk
=> disable minimum level sending to splunk and use global setting

src/backend/TrafficCourts/Citizen.Service/Controllers/TicketsController.cs, src/backend/TrafficCourts/Citizen.Service/Models/Tickets/OcrViolationTicket.cs, src/backend/TrafficCourts/Citizen.Service/Services/FormRecognizerService.cs, src/backend/TrafficCourts/Citizen.Service/Validators/FormRecognizerValidator.cs, src/backend/TrafficCourts/Test/Citizen.Service/Controllers/TicketsControllerTests.cs
Refactored ViolationTicket fields to be a Dictionary instead of a List.  
Replaced 
`public List<Field> Fields { get; set; } = new List<Field>();`
With
`public Dictionary<string, Field> Fields { get; set; } = new Dictionary<string, Field>();`
Cleaned up serialization. Now looks like this:
dotnet test
=> Refactored ViolationTicket fields to be a Dictionary instead of a List

src/backend/TrafficCourts/Citizen.Service/Controllers/TicketsController.cs, src/backend/TrafficCourts/Citizen.Service/Features/Tickets/AnalyseHandler.cs, src/backend/TrafficCourts/Test/Citizen.Service/Controllers/TicketsControllerTests.cs
Fixed the return type for the /analyse endpoint, updated xUnit test.
The endpoint now returns a ProblemDetails object detailing why the request failed with a 400 BAD REQUEST response.
Swagger is now responsive again!
This is an example when submitting a ticket with an invalid ticket number:
=> Fixed return type of analyse endpoint

src/backend/TrafficCourts/Citizen.Service/Models/Tickets/OcrViolationTicket.cs, src/backend/TrafficCourts/Citizen.Service/Services/FormRecognizerService.cs, src/backend/TrafficCourts/Citizen.Service/Validators/FormRecognizerValidator.cs, src/backend/TrafficCourts/Citizen.Service/Validators/Rules/FieldMatchesRegexRule.cs, src/backend/TrafficCourts/Citizen.Service/Validators/Rules/OnlyMCAIsSelectedRule.cs, src/backend/TrafficCourts/Citizen.Service/Validators/Rules/ValidationRule.cs, src/backend/TrafficCourts/Citizen.Service/Validators/ValidationMessages.cs, src/backend/TrafficCourts/Test/Citizen.Service/Validators/Rules/FieldMatchesRegexRuleTest.cs, src/backend/TrafficCourts/Test/Citizen.Service/Validators/Rules/OnlyMCAIsSelectedRuleTest.cs
[TCVP-933](https://justice.gov.bc.ca/jira/browse/TCVP-933)
- Added new OnlyMCAIsSelectedRule to ensure only the MCA checkbox is selected in the "Did commit the offense(s) indicated" section
- Added xUnit tests
- To be more clear, refactored Confidence to be either GlobalConfidence or FieldConfidence.
- To be more clear, refactored ValidationErrors to be either GlobalValidationErrors or FieldValidationErrors.
dotnet test
=> TVCP-933 Added OnlyMCAIsSelectedRule validation rule

src/frontend/citizen-portal/.dockerignore, src/frontend/citizen-portal/README.md
Added missing `.dockerignore` file for frontend.  Without this, docker-compose will include the large `node_modules` dependencies and any locally built files - these should be generated every time, not copied from local development.
This file must exist at the same level as the build context invoked from docker-compose, which in this case is:
```
build:
context: ./src/frontend/citizen-portal
```
=> Added missing .dockerignore file to frontend

docker-compose.yml, src/frontend/citizen-portal/Dockerfile, src/frontend/citizen-portal/nginx.conf.template
There was a disconnect between the front and backend services when using docker-compose. This fix addresses that - the frontend now properly references the backend both when launching the citizen-portal locally (in vscode) or in docker via docker-compose.
Added API_BASE_PATH as a env variable in docker-compose so the citizen-portal properly references the API.
=> Fixed docker-compose so the frontend works

src/backend/TrafficCourts/Citizen.Service/Validators/Rules/TicketAmountValidRule.cs, src/backend/TrafficCourts/Citizen.Service/Validators/Rules/TimeRule.cs, src/backend/TrafficCourts/Citizen.Service/Validators/Rules/ViolationDateLT30Rule.cs
Persisted correctly parsed datatypes back onto their respective field value.
This way, Violation Date will always be of the standard ISO 8601 format:
ie. yyyy-MM-dd
Any Violation Time will consistently be formatted as an ISO 8601 value.
ie. hh:mm
Currency will always be formatted the same per US currency: $xx.xx
dotnet test
=> Persisted correctly parsed datatypes back onto the field value

src/backend/TrafficCourts/TrafficCourts.Ticket.Search.Service/Startup.cs
fixes issue where background worker was being registered regardless of search time. Mock does not register dependent services.
=> Only register worker if using RSI ticket search

docker-compose.yml, src/frontend/staff-portal/Dockerfile
Added staff-portal to docker-compose.
At the moment, the API_BASE_PATH references the http://citizen-api:8080/api/, but I assume this will change at some point to reference the staff-api
=> Docker - added staff-portal to docker-compose

src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/Configuration/SftpConfig.cs, src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/Program.cs, src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/appsettings.json
- Adds ssh key auth option by reading the key file from a path as part of SFTP client configuration.
=> Added ssh key authentication option for sftp client config

docker-compose.yml
"citizen-api" would not start due to invalid reference to "seq".  "seq" was removed from docker-compose, but references to it was not.
=> Fixed broken docker-compose

src/backend/TrafficCourts/Citizen.Service/Program.cs, src/backend/TrafficCourts/Citizen.Service/appsettings.Development.json, src/backend/TrafficCourts/Common/Configuration/SwaggerConfiguration.cs, src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/Program.cs, src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/appsettings.Development.json, src/backend/TrafficCourts/TrafficCourts.Common.Test/Configuration/SwaggerConfigurationTests.cs
Adds a optional setting to enable swagger instead of relying on `IsDevelopment` configuration.
Added unit tests to ensure the default and expected explicit configuration are mapped correctly
=> Add configurable setting to enable Swagger

src/backend/TrafficCourts/Common/TrafficCourts.Common.csproj
- This adds Serilog.Enrichers.Context to the common library that was being reference in the app settings.
=> Add missing Serilog.Enrichers.Context package reference

src/backend/oracle-data-interface/pom.xml
Added jacoco coverage report to oraface-api pom.xml, hooked into the test target.
Running tests now also generates the code coverage report that can be consumed by github.
```
mvn clean test
```
(in \target\site\jacoco\index.html)
mvn test
=> Added jacoco coverage report to oraface-api

.docker/docker-compose.seq.yml, .docker/docker-compose.splunk.yml, README.md
- ensure services are configured to depend on seq or splunk respectively
- add examples of running just the `citizen-api` for front end dev.
- the splunk config is currently giving an error about not finding the network
=> fix dependencies when using seq or splunk logging, add examples

src/backend/oracle-data-interface/src/main/java/ca/bc/gov/open/jag/tco/oracledatainterface/config/ApplicationConfig.java, src/backend/oracle-data-interface/src/main/java/ca/bc/gov/open/jag/tco/oracledatainterface/controller/v1_0/DisputeController.java
In preparation for the TCVP-1210 ticket, this small change versions the oraface-api via a routing strategy (version in URL path).
- Prefixed all endpoints with /api/v1.0
- Added a swagger group to more easily switch between versions.
- Moved the DisputeController to a v1.0 package
Going forward, if there are changes to the endpoints or model changes to the Dispute object, we'll need to create a new controller (and likely refactor the old Dispute object to a v1.0 package in the model folder).
=> TCVP-1210 versioned the oraface-api with a versioned-route strategy

src/backend/TrafficCourts/Staff.Service/Controllers/DisputeController.cs, src/backend/TrafficCourts/Staff.Service/OpenAPIs/OracleDataAPI/v1_0/IOracleDataApi_v1_0Client.cs, src/backend/TrafficCourts/Staff.Service/OpenAPIs/OracleDataAPI/v1_0/OracleDataApi.v1_0.json, src/backend/TrafficCourts/Staff.Service/OpenAPIs/OracleDataAPI/v1_0/OracleDataApi_v1_0Client.cs, src/backend/TrafficCourts/Staff.Service/Program.cs, src/backend/TrafficCourts/Staff.Service/TrafficCourts.Staff.Service.csproj, src/backend/TrafficCourts/TrafficCourts.Staff.Service.Test/Controllers/DisputeControllerTest.cs, src/backend/TrafficCourts/TrafficCourts.Staff.Service.Test/TrafficCourts.Staff.Service.Test.csproj
[TCVP-1210](https://justice.gov.bc.ca/jira/browse/TCVP-1210)
- Added an OpenApi connected service to the staff-api project to consume the oracle-data-api swagger spec.
- Added a static copy of the OracleDataApi, v1.0 json swagger spec.
- Added a new DisputeController as a wrapper to the OracleDataApi to retrieve a single Dispute.
- Extracted interface of OracleDataApi to be able to create unit tests
- Created a single unit test, happy path
- PR updated to reflect new "oracle-data-api" project name.
UserSecrets should include a new property for the Oracle Data API basePath:
`OracleDataApi:BaseUrl`
TODO: create tests for other HTTP return codes.
dotnet test …
=> Added Oracle Data API as an OpenAPI connected service

src/backend/TrafficCourts/Staff.Service/Controllers/DisputeController.cs, src/backend/TrafficCourts/TrafficCourts.Staff.Service.Test/Controllers/DisputeControllerTest.cs
[TCVP-1214](https://justice.gov.bc.ca/jira/browse/TCVP-1214)
Added an endpoint to the staff-api (a wrapper to the oracle-data-api endpoint) that retrieves all Disputes.
Added xunit tests
dotnet test
=> TCVP-1214 Added staff-api wrapper for all disputes

docker-compose.yml, src/backend/README.md, src/backend/TrafficCourts/Staff.Service/Dockerfile
[TCVP-1214](https://justice.gov.bc.ca/jira/browse/TCVP-1214)
- Fixed staff-api Dockerfile
- Created staff-api in docker-compose
`docker-compose up -d` now will launch the staff-api (a wrapper to oracle-data-api)
Swagger spec is at: http://localhost:5005/swagger/index.html
=> TCVP-1214 Exposed staff-api to docker-compose

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/error/ControllerAdvisor.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/error/DeprecatedException.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/error/NotAllowedException.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeService.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/BaseTestSuite.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeControllerTest.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeServiceTest.java
Added HTML 405 error code rules to Dispute status change PUT endpoints
In short:
- a Dispute status can only be set to PROCESSING iff status is NEW or PROCESSING
- a Dispute status can only be set to CANCELLED iff status is REJECTED or PROCESSING
- a Dispute status can only be set to REJECTED iff status is NEW, CANCELLED, or REJECTED
mvn verify
=> TCVP-1058 Added 405 error code rules and junit tests

docker-compose.yml
Added a missing ORACLEDATAAPI__BASEURL env var to staff-api in docker-compose.yml
This should default to the oracle-data-api container.
=> Added missing env var to staff-api

src/backend/TrafficCourts/Staff.Service/Controllers/DisputeController.cs, src/backend/TrafficCourts/Staff.Service/OpenAPIs/OracleDataAPI/v1_0/IOracleDataApi_v1_0Client.cs, src/backend/TrafficCourts/Staff.Service/OpenAPIs/OracleDataAPI/v1_0/OracleDataApi_v1_0Client.cs, src/backend/TrafficCourts/Staff.Service/Program.cs, src/backend/TrafficCourts/Staff.Service/Services/DisputeService.cs, src/backend/TrafficCourts/Staff.Service/Services/IDisputeService.cs, src/backend/TrafficCourts/TrafficCourts.Staff.Service.Test/Controllers/DisputeControllerTest.cs
Refactored DisputeController, moved usage of the oracleDataApi client into a service layer so that other operations can be done at the same time, ie email the client when submitting a dispute.  Business logic should exist in the Service layer, not the main Controller layer.
For now the DisputeService is just a wrapper for the oracleDataApi client, but we can use this class to add other functionality to the endpoint logic.
dotnet test
=> TCVP-1058 added DisputeService to handle service layer tasks

src/backend/TrafficCourts/Staff.Service/Controllers/DisputeController.cs, src/backend/TrafficCourts/Staff.Service/Controllers/HttpError.cs, src/backend/TrafficCourts/Staff.Service/Program.cs, src/backend/TrafficCourts/Staff.Service/Services/DisputeService.cs, src/backend/TrafficCourts/Staff.Service/Services/IDisputeService.cs, src/backend/TrafficCourts/TrafficCourts.Staff.Service.Test/Controllers/DisputeControllerTest.cs
Added PUT endpoints to the staff-api for **reject**, **cancel**, and **submit**.  These endpoints are simple wrappers for the oracle-data-api.
- enhanced error returns by using ProblemDetails instead. 
TODO: add xunit tests
TODO: more logic per the JIRA ticket to
- auto delete submissions after a year
- email citizen
- submit Dispute to ARC
- etc.
dotnet test
=> TCVP-1058 added staff-api endpoints for reject, cancel, and submit

src/backend/TrafficCourts/Citizen.Service/Models/Dispute/TicketDispute.cs, src/backend/TrafficCourts/Messaging/MessageContracts/SubmitDispute.cs, src/backend/TrafficCourts/Staff.Service/Controllers/DisputeController.cs, src/backend/TrafficCourts/Staff.Service/OpenAPIs/OracleDataAPI/v1_0/OracleDataApi.v1_0.json, src/backend/TrafficCourts/Staff.Service/Services/DisputeService.cs, src/backend/TrafficCourts/Staff.Service/Services/IDisputeService.cs, src/backend/TrafficCourts/TrafficCourts.Staff.Service.Test/Controllers/DisputeControllerTest.cs, src/backend/TrafficCourts/Workflow.Service/Consumers/SubmitDisputeConsumer.cs, src/backend/TrafficCourts/Workflow.Service/Models/Dispute.cs, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeController.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/Dispute.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/TicketCount.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/DisputeRepository.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeService.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeControllerTest.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeServiceTest.java
- [TCVP-1281](https://justice.gov.bc.ca/jira/browse/TCVP-1281)
- Refactored Oracle Data API entity data models to use UUID instead of incremented Integer IDs.
- Updated Staff API controller and services to use GUIDs for ID related operations accordingly.
- Updated XUnit tests to use GUIDs.
- Added email address field to the oracle-data-api dispute model and refactored message contracts and other related services to include email address field as well.
=> Feature tcvp 1281 - update oracle data api models to use guid

src/backend/TrafficCourts/Citizen.Service/Models/Tickets/OcrViolationTicket.cs, src/backend/TrafficCourts/Citizen.Service/Services/Impl/FormRecognizerService.cs, src/backend/TrafficCourts/Citizen.Service/Validators/Rules/CheckboxIsValidRule.cs, src/backend/TrafficCourts/Citizen.Service/Validators/Rules/DriversLicenceValidRule.cs, src/backend/TrafficCourts/Citizen.Service/Validators/Rules/FieldIsRequiredRule.cs, src/backend/TrafficCourts/Citizen.Service/Validators/Rules/FieldMatchesRegexRule.cs, src/backend/TrafficCourts/Citizen.Service/Validators/Rules/OnlyMVAIsSelectedRule.cs, src/backend/TrafficCourts/Citizen.Service/Validators/Rules/TicketAmountValidRule.cs, src/backend/TrafficCourts/Citizen.Service/Validators/Rules/ValidationRule.cs, src/backend/TrafficCourts/Test/Citizen.Service/Validators/Rules/FieldMatchesRegexRuleTest.cs
- Moves nested types out of OcrViolationTicket
- Fixes error with rendering swagger ui
=> Move Field, BoundingBox and Point types from nested under OcrViolationTicket

src/frontend/citizen-portal/nginx.conf, src/frontend/staff-portal/nginx.conf
- adds missing semi-colon on include directives in nginx.conf
=> add missing semi-colon on include directive

docker-compose.yml, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeController.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeService.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeControllerTest.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeServiceTest.java
Implemented a few requirement changes from business regarding when a Dispute is allowed to change state.  Now:
- a Dispute status can only be set to PROCESSING iff status is NEW or REJECTED
- a Dispute status can only be set to CANCELLED iff status is NEW, REJECTED or PROCESSING
- a Dispute status can only be set to REJECTED iff status is NEW
Updated junit tests
ran `mvn verify`
=> TCVP-1058 implemented business rule changes

src/backend/TrafficCourts/Citizen.Service/Features/Disputes/Create.cs, src/backend/TrafficCourts/Common/Converters/Json/DateOnlyJsonConverter.cs, src/backend/TrafficCourts/Messaging/MessageContracts/DisputeSubmitted.cs, src/backend/TrafficCourts/Test/Citizen.Service/Controllers/DisputesControllerTest.cs, src/backend/TrafficCourts/Workflow.Service/Consumers/SubmitDisputeConsumer.cs, src/backend/TrafficCourts/Workflow.Service/Services/IOracleDataApiService.cs, src/backend/TrafficCourts/Workflow.Service/Services/OracleDataApiService.cs
- [TCVP-1296](https://justice.gov.bc.ca/jira/browse/TCVP-1296)
- Fixed the issue that was preventing a dispute to be created through the citizen api create endpoint by updating DateOnlyJsonConverter.
- Updated message consumers and contracts to work with new guid type ids from oracle-data-api.
- Updated oracle data api base uri in workflow service to match most up to date api version.
=> TCVP 1296 fix for citizen api create dispute endpoint

src/backend/TrafficCourts/Staff.Service/Startup.cs
Bug fix.
Per best practices for REST APIs, route endpoints should be lowercase.
Since the [RFC 3986 specification for URI standards](https://tools.ietf.org/html/rfc3986) denotes that URIs are case-sensitive, it's common practice to ensure all endpoints are lowercase to help avoid confusion about inconsistent capitalisation.
dotnet test
=> Fixed endpoint capitalisation

docker-compose.yml, src/backend/TrafficCourts/Citizen.Service/Configuration/Extensions.cs, src/backend/TrafficCourts/Citizen.Service/Controllers/TicketsController.cs, src/backend/TrafficCourts/Citizen.Service/Startup.cs, src/backend/TrafficCourts/Common/Configuration/TicketStorageConfiguration.cs, src/backend/TrafficCourts/Common/Configuration/TicketStorageType.cs, src/backend/TrafficCourts/Common/Features/FilePersistence/Extensions.cs, src/backend/TrafficCourts/Common/Features/FilePersistence/MinioFilePersistenceService.cs, src/backend/TrafficCourts/Common/StreamExtensions.cs, src/backend/TrafficCourts/Staff.Service/Models/ViolationTicket.cs, src/backend/TrafficCourts/Staff.Service/Models/ViolationTicketImage.cs, src/backend/TrafficCourts/Staff.Service/Services/DisputeService.cs, src/backend/TrafficCourts/Staff.Service/Startup.cs, src/backend/TrafficCourts/Staff.Service/TrafficCourts.Staff.Service.csproj, src/backend/TrafficCourts/TrafficCourts.Staff.Service.Test/Services/DisputeServiceTest.cs
[TCVP-1268](https://justice.gov.bc.ca/jira/browse/TCVP-1268)
Per the JIRA requirements, modified the `/api/dispute/{id}` staff-api endpoint by extending the returned `Dispute `object to include the raw byte[] (raw image) of the uploaded violation ticket image that is located in the object store.
- Created a FilePersistenceExtension in Common to wire up Minio, an object store (copied from Citizen Service configuration)
- Configured the StaffApi to use the new common file persistence extension
- Extended ViolationTicket to included a new ViolationTicketImage object that holds the byte[] of the actual image
- Enhanced the GetDisputeAsync service call to pull the raw image from Minio and store it in the returned ViolationTicket 
- Added xUnit …
=> TCVP-1268 Added FilePersistence to staff-api

src/backend/TrafficCourts/Staff.Service/OpenAPIs/OracleDataAPI/v1_0/OracleDataApi.v1_0.json, src/backend/TrafficCourts/Staff.Service/Services/DisputeService.cs, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/OracleDataApiApplication.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/config/AuditConfig.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/config/SpringSecurityAuditorAware.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeController.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/Auditable.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/Dispute.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/DisputedCount.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/LegalRepresentation.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/ViolationTicket.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/ViolationTicketCount.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/DisputeRepository.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeService.java, src/backend/oracle-data-api/src/main/resources/application.yml, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeControllerTest.java
[TCVP-1301](https://justice.gov.bc.ca/jira/browse/TCVP-1301)
In preparation for TCVP-1301, this PR adds audit fields to the Oracle data model objects, 
ie.
```
{
"createdBy": "System",
"createdTs": "2022-05-09T20:55:10.139+00:00",
"modifiedBy": "System",
"modifiedTs": "2022-05-09T20:55:10.139+00:00",
...
}
```
The **...Ts** fields are automatically populated when doing an INSERT (both createdTS and modifiedTS) or an UPDATE (only modifiedTS).
The **...By** fields are currently statically set to "System" until a way is found to provide a username to the oracle-data-api
The audit fields are added to these objects:
- Dispute
- DisputedCount
- LegalRepresentation
- ViolationTicket
- ViolationTicketCount
if your change is a breaking change, …
=> TCVP-1301 Add audit fields to Oracle data model objects

docker-compose.yml
Set default values to be able to authenticate with Keycloak when running the staff-api locally in Docker
=> Fixed issue with jwt auth not working in staff-api in Docker

src/backend/TrafficCourts/Staff.Service/Services/DisputeService.cs
TCVP-1268
Fixed a bug where the service could not parse the ocrViolationTicket json string to retrieve the image filename that is in the object store.
dotnet test
=> TCVP-1268 bug fix to better parse the ocrViolationTicket

src/backend/TrafficCourts/Test/Workflow.Service/Consumers/DisputeApproveNotifyConsumerTests.cs, src/backend/TrafficCourts/Test/Workflow.Service/Consumers/DisputeSubmitNotifyConsumerTests.cs, src/backend/TrafficCourts/Test/Workflow.Service/Features/Mail/SendEmailConsumerTests.cs, src/backend/TrafficCourts/Workflow.Service/Configuration/EmailConfiguration.cs, src/backend/TrafficCourts/Workflow.Service/Consumers/DisputeApprovedNotifyConsumer.cs, src/backend/TrafficCourts/Workflow.Service/Consumers/DisputeSubmitConsumer.cs, src/backend/TrafficCourts/Workflow.Service/Consumers/DisputeSubmitNotifyConsumer.cs, src/backend/TrafficCourts/Workflow.Service/Features/Mail/SendEmailConsumer.cs, src/backend/TrafficCourts/Workflow.Service/Services/EmailSenderService.cs, src/backend/TrafficCourts/Workflow.Service/Startup.cs
- TCVP-1333 - have the e-mail notification as its own consumer, for submit and approval of disputes
Unit testing to verify calls work.
=> TCVP-1333 - Move e-mail send publishes to its own consumers

.gitops/charts/traffic-court-online/charts/oracle-data-api/templates/deployment.yaml
- Sets oracle data api service to use recreate instead of rolling due to single PVC.
=> change oracle data api to use recreate strategy instead of rolling

src/backend/TrafficCourts/Common/Configuration/TicketStorageConfiguration.cs
To simplify deployment configuration, defaulted the staff-api TicketStorageType to be ObjectStore instead of InMemory
=> TCVP-1268 Default ticket storage to ObjectStore, not memory

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/Dispute.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/DisputeRepository.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/scheduled/CodeTableTasks.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/scheduled/DisputeTasks.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/scheduled/StartupTasks.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeService.java, src/backend/oracle-data-api/src/main/resources/application.yml
[TCVP-1369](https://justice.gov.bc.ca/jira/browse/TCVP-1369)
- Changed Dispute.assignedTs to be a timestamp object instead of a date object
- Created a cronjob that runs every 5 minutes to clear the assignedTo and assignedTs properties on all Disputes whose assignedTs is older than 1 hour.
- Cleaned up CodeTableTasks by pulling out startup tasks into it's own file.
=> TCVP-1376 Created an unassign Dispute cron job

src/backend/TrafficCourts/Staff.Service/OpenAPIs/OracleDataAPI/v1_0/OracleDataApi.v1_0.json, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeController.java
TCVP-1376
Exposed the Unassign Dispute cronjob task as a endpoint (/disputes/unassign) that can be called manually (ie, an external cronjob trigger).
=> TCVP-1376 - created /dispute/unassign endpoint for cronjobs

.docker/docker-compose.splunk.yml, docker-compose.yml
- Fixed `docker-compose.splunk.yml` - still had references to ticket-search
- Moved splunk env vars from `docker-compose.yml` to `docker-compose.splunk.yml`
I confirmed logging works in splunk locally with 
```
docker-compose -f docker-compose.yml -f ./.docker/docker-compose.splunk.yml up -d --build oracle-data-api
```
=> Moved splunk env vars to splunk.yml

src/backend/TrafficCourts/Staff.Service/Controllers/DisputeController.cs, src/backend/TrafficCourts/Staff.Service/OpenAPIs/OracleDataAPI/v1_0/OracleDataApi.v1_0.json, src/backend/TrafficCourts/Staff.Service/Services/DisputeService.cs, src/backend/TrafficCourts/Staff.Service/Services/IDisputeService.cs, src/backend/TrafficCourts/TrafficCourts.Staff.Service.Test/Controllers/DisputeControllerTest.cs, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeController.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/DisputeStatus.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeService.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeControllerTest.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeServiceTest.java
Added a new Dispute status of VALIDATED.  A NEW Dispute can be opened by a staff on the staff-portal. After staff has vetted and approved field values on an OCR Violation Ticket, the staff can click a Validate button which moves the Dispute to the VALIDATED state, which in turn can move to the PROCESSING state when they click Submit.
This PR adds VALIDATED as a new possible state to the oracle-data-api project.
- added a new /dispute/{id}/validate endpoint to oracle-data-api
- regenerated openapi spec for staff-api
- added a new /dispute/{id}/validate endpoint to staff-api
mvn verify
dotnet test …
=> TCVP-1058 Added Validated Dispute status.

src/backend/TrafficCourts/Messaging/MessageContracts/DisputeApproved.cs, src/backend/TrafficCourts/Staff.Service/Mappers/Mapper.cs, src/backend/TrafficCourts/Test/Arc.Dispute.Service/Mappings/MappingTests.cs, src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/Mappings/CustomMap.cs, src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/Models/ArcFileRecord.cs, src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/Models/TcoDisputeTicket.cs, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/ViolationTicketCount.java
- [TCVP-1364](https://justice.gov.bc.ca/jira/browse/TCVP-1364)
- Added functionality to parse full section of statutes into 3 groups required for ARC if 3 fields are not passed separately. 
For example: If the full section field is passed as "127(1)(a)(ii)", it would be parsed out and split into the following 3 groups and the last part (subparagraph) will be ignored:
Section: 127
Subsection: 1
Paragraph: a
- Added 'subparagraph' field to the Oracle data model.
- Added some default field values that are required to be represented on each record of ARC file.
If Yes: Has Docker been updated …
=> Feature TCVP-1364 update arc section parse method rebase

src/backend/TrafficCourts/Staff.Service/Controllers/DisputeController.cs, src/backend/TrafficCourts/Staff.Service/OpenAPIs/OracleDataAPI/v1_0/OracleDataApi.v1_0.json, src/backend/TrafficCourts/Staff.Service/Services/DisputeService.cs, src/backend/TrafficCourts/Staff.Service/Services/IDisputeService.cs, src/backend/TrafficCourts/TrafficCourts.Staff.Service.Test/Controllers/DisputeControllerTest.cs, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeController.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/DisputeRepository.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeService.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeControllerTest.java
- [TCVP-1395](https://justice.gov.bc.ca/jira/browse/TCVP-1395)
- Added functionality to fetch all disputes by filtering them through specifying a status type to exclude the disputes having the specified status from the returned result set.
- Added ability to combine status filter with older than date filter.
- Updated Staff API get all disputes endpoint to get optional parameters to filter by status and older than date.
=> TCVP-1395 add status filter for fetching all disputes

src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApi.v1_0.json, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeController.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/JJDispute.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/DisputeRepository.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeService.java
- [TCVP-1423](https://justice.gov.bc.ca/jira/browse/TCVP-1423)
- Added functionality to retrieve all disputes that can be filtered by specified jj assigned.
- Added a new JJDispute model class and schema for H2 db for storing/retrieving JJ Workbench related data.
- Updated open api client spec.
=> TCVP-1423 add JJDispute model and endpoint for fetching all disputes filtered by jjAssigned

.gitops/charts/traffic-court-online/charts/citizen-api/templates/deployment.yaml, .gitops/charts/traffic-court-online/charts/citizen-api/values.yaml, .gitops/charts/traffic-court-online/charts/staff-api/templates/deployment.yaml, .gitops/charts/traffic-court-online/charts/staff-api/values.yaml, .gitops/charts/traffic-court-online/charts/workflow-service/templates/deployment.yaml, .gitops/charts/traffic-court-online/charts/workflow-service/values.yaml
- Adds exposing application metrics collection in the citizen-api
- other services will be added shortly outside of this PR
=> Add dotnet monitor container if metrics enabled

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/JJDisputeController.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/JJDisputeRepository.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/JJDisputeService.java, src/backend/oracle-data-api/src/main/resources/application.yml, src/backend/oracle-data-api/src/main/resources/data.sql, src/backend/oracle-data-api/src/test/resources/application.yml
- [TCVP-1423](https://justice.gov.bc.ca/jira/browse/TCVP-1423)
- Added a new controller, service and repository for JJ Disputes in order to provide functionality to fetch all JJ Disputes by optionally filtering them based on the specified JJ staff and/or JJ group assigned.
- Created a data.sql script to auto populate the JJDispute table in H2 database on startup.
=> TCVP-1423 fetch filtered jj disputes

.docker/docker-compose.jaeger.yml, .gitops/charts/traffic-court-online/charts/oracle-data-api/templates/deployment.yaml, docker-compose.yml, src/backend/oracle-data-api/src/main/resources/application.yml
- Added env variables to docker-compose and docker-compose.jaeger files to disable exporting to jaeger by default for local development in order to prevent error messages in the logs.
- Configured docker-compose.jaeger to enable jaeger trace exporting by default.
- Updated helm chart to add spring sleuth enabled parameter and value.
=> Configured docker-compose files to disable jaeger exporting for oracle-data-api by default

.github/workflows/pr-oracle-api.yml
Added continuous integration (CI) to oracle-data-api Java project.
This workflow will run all the JUnit tests on every PR with changes to the /src/backend/oracle-data-api folder.
=> Added JUnit CI to oracle-data-api project

src/backend/TrafficCourts/Workflow.Service/Services/SubmitDisputeToArcService.cs
- Changed ARC dispute service base URI to start with http instead of https.
=> Fixed the base URI to send request to ARC dispute service in Workflow Service

src/backend/TrafficCourts/Citizen.Service/Features/Disputes/Create.cs, src/backend/TrafficCourts/Citizen.Service/Features/Tickets/AnalyseHandler.cs, src/backend/TrafficCourts/Citizen.Service/Features/Tickets/Search.cs
- [TCVP-1518](https://justice.gov.bc.ca/jira/browse/TCVP-1518)
- Added suffix to generated Ticket IDs to distinguish it from OCRed vs Looked Up Ticket when saving and retrieving Ticket details from Redis to create a dispute.
- Improved the error handling and log messages based on the Violation Ticket type.
=> TCVP-1518 - Add suffix to generated Ticket ID

src/backend/oracle-data-api/src/main/resources/data.sql
- Staff API OpenAPI spec expects MODIFIED_BY and MODIFIED_TS fields to be not NULL so it returns a serialization error when fetching the jj disputes with the auto populated data.
- Updated data.sql to populate MODIFIED_BY and MODIFIED_TS fields of JJDISPUTE table on startup so Staff API JJ Dispute endpoints work properly.
=> Updated data.sql to fix Staff API JJDispute endpoints

src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApi.v1_0.json, src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApiClient.cs, src/backend/TrafficCourts/Staff.Service/Controllers/JJController.cs, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/JJDisputeController.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/JJDisputeService.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/BaseTestSuite.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/JJDisputeControllerTest.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/JJDisputeServiceTest.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/util/RandomUtil.java
- [TCVP-1435](https://justice.gov.bc.ca/jira/browse/TCVP-1435)
- Added validation rules for updating statuses of JJ Disputes when an admin resolution is submitted.
- Added unit tests for JJ Dispute status update business rules.
- Updated Staff API to handle 405 not allowed exception if the oracle-data-api returns error due to failed JJ Dispute status update. (Updated the OpenAPI spec json)
=> TCVP-1435 JJ Dispute Status Update Validation

src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/Services/ArcFileService.cs
- [TCVP-1591](https://justice.gov.bc.ca/jira/browse/TCVP-1591)
- Fixes a bug that prevents ARC file to be processed by other systems due to the encoding type of the final file being initialized with a Byte Order Mark (BOM) Character.
- Updated ARC file encoding to ASCII instead of UTF8 prior to streaming/writing in data.
Tested running ARC Dispute API locally and sending a request for creating an ARC file. Opened created ARC file in SFTP location via Notepad++ and confirmed the encoding is UTF-8 only.
=> TCVP-1591 Change encoding when writing to ARC file

src/backend/TrafficCourts/Test/Arc.Dispute.Service/Mappings/MappingTests.cs, src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/Mappings/DisputeTicketToArcFileRecordListConverter.cs
- [TCVP-1627](https://justice.gov.bc.ca/jira/browse/TCVP-1627)
- Added a minute between the transaction times since each transaction timestamp for EV and ED must be unique for ARC to process.
Ran ARC API locally and sent a request to create a new ARC data file. Then checked the content of the file to see whether all transaction times are 1 minute apart. They all looked accurate.
=> TCVP-1627 Add a minute difference between each transaction time of EV and ED

src/backend/TrafficCourts/Test/Arc.Dispute.Service/Mappings/MappingTests.cs, src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/Mappings/DisputeTicketToArcFileRecordListConverter.cs
- [TCVP-1629](https://justice.gov.bc.ca/jira/browse/TCVP-1629)
- Fixes a bug with ARC file output by adding two spaces after file number (between the 10th character and the "01" at the end) instead of one.
- Fixes a bug with the checksum digit was not applied to the disputed type ticket rows.
Ran ARC API locally and sent a request to create a new ARC data file. Then checked the content of the file to see whether there are two space after the File Number or not. The output file content was correct.
=> TCVP-1629 / ARC File - Add Two Spaces After File Number

src/backend/TrafficCourts/Test/Arc.Dispute.Service/Configuration/SftpConnectionOptionsTests.cs, src/backend/TrafficCourts/Test/TrafficCourts.Test.csproj, src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/Configuration/SftpConnectionOptions.cs, src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/Startup.cs
- Allows the SSH key to be provided in environment variable as well as a file on disk
- key in variable will take precedence over file
- key in file will still work
- will still fall back to usename and password if no ssh key is available
=> allow ssh key to be provided in configuration/env variable

.gitattributes, src/backend/TrafficCourts/entrypoint.sh, src/backend/oracle-data-api/entrypoint.sh
- allow adding a "sleep x" before the main entry point starts for troubleshooting
=> add optional sleep at start of container start

src/backend/TrafficCourts/Staff.Service/Controllers/JJController.cs
- Fixes the bug for the wrong read scope for the update jj-dispute endpoint in Staff API by changing it to update.
=> Auth guard scope for the jj-dispute update endpoint

.gitops/charts/traffic-court-online/charts/citizen-web/templates/configmap.yaml, .gitops/charts/traffic-court-online/charts/staff-web/templates/configmap.yaml
kube-dns.kube-system.svc.cluster.local does not exist on openshift, so removed the `resolve` directive for now.
=> removed nginx resolver directive

infrastructure/openshift/dev/ords-proxy.yaml
Adds the required manifests for creating objects to allow proxy to ORDS endpoints in Dev only. Dev IP addresses added to allow list as per values provided. See https://justice.gov.bc.ca/jira/projects/TCVP/issues/TCVP-1682
=> Add ORDS proxy for development only

.docker/docker-compose-ocr.yml, .gitops/azure/azure-custom-cron-logs.yml, .gitops/azure/azure-custom-cron-requests.yml
TCVP-1595
Added 2 OpenShift configuration files to create cronjobs to cleanup Form Recognizer data.
Job1: Run daily, remove old log files over 1 month old
Job2: Run hourly, remove old Form Recognizer OCR ticket images and results that are over 1 hour old.
To deploy these jobs:
oc apply -f azure-custom-cron-logs.yml
oc apply -f azure-custom-cron-requests.yml
Added a new container to docker-compose to test this functionality.
Deployed to DEV and confirmed the data is properly cleared out.
=> TCVP-1595 OpenShift cronjobs to cleanup Form Recognizer data

.gitops/charts/traffic-court-online/charts/arc-dispute-api/values.yaml, .gitops/charts/traffic-court-online/charts/citizen-api/values.yaml, .gitops/charts/traffic-court-online/charts/staff-api/values.yaml, .gitops/charts/traffic-court-online/charts/workflow-service/values.yaml
- Adjusts default memory limits and request vaults for .net containers
=> Adjust default memory requests to 256Mi, limits to 512Mi

src/backend/TrafficCourts/Workflow.Service/Consumers/DisputeSubmitConsumer.cs
- changes the logging of the dispute so it is destructured instead of logging the type name.
Note, Serilog may not use the same serializer as the Oracle Data API.
=> Add object destructuring to log.Trace statement to get object contents

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-online/values.yaml, .gitops/charts/traffic-court-test-values.yaml, src/backend/oracle-data-api/Dockerfile
- changes Dockerfile for oracle-data-api to pass JAVA_OPTS as parameters to java executable
- moves the JAVA_OPTS settings to environment specific configuration as it is used for log levels
=> Fix passing JAVA_OPTS to oracle data api

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/JJDispute.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/JJDisputeRemark.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/JJDisputeService.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/JJDisputeControllerTest.java
- [TCVP-1688](https://justice.gov.bc.ca/jira/browse/TCVP-1688)
- Adds JJDisputeRemark model and JPA hibernate config to create table in H2 database.
- Adds functionality to store JJ Remarks in H2 database through the existing JJ Dispute update endpoint in Oracle Data API.
=> TCVP-1688 - Add JJ Dispute Remarks

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/Dispute.java
Small PR to add a specific length on a description column instead of leaving it as default.  This way the validator will engage.
The column is currently 255 (the default in H2), but can be expanded later when the Oracle datamodel is defined.
mvn verify
=> TCVP-1703 added length on a description column

src/backend/oracle-data-api/.gitignore, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/BooleanConverter.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/Dispute.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/DisputeRepository.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeServiceTest.java
TCVP-1673
Added `emailAddressVerified `and `emailVerificationToken `to Dispute
Added service to retrieve Dispute by `emailVerificationToken`
Added a converter that maps Boolean datatype to 'Y' 'N' characters
Added junit test.
Note: at the moment, these database fields are unused. Next task is to write API endpoints to update these values.
Also, the OpenAPI definition is not yet updated in staff-api (that will be done when the staff-api is updated with new api endpoints)
mvn verify
=> TCVP-1673 add email verified flag

docker-compose.yml, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeController.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/Dispute.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeService.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeServiceTest.java
TCVP-1686
Created a new endpoint in the oracle-data-api project to update the Dispute.EmailAddressVerified flag based on an emailVerificationToken
PUT /api/v1.0/dispute/{uuid}/email/validate
Endpoint returns 200 or 500.
mvn verify
=> TCVP-1686 Create validateEmail API endpoint

src/backend/TrafficCourts/Staff.Service/Program.cs, src/backend/TrafficCourts/Workflow.Service/Program.cs
- removes Https Redirection middleware which attempts to redirect http to https traffic. With this middleware, the following warning is logged at startup "Failed to determine the https port for redirect." In our services, internal inter-pod traffic is not HTTPS. Any HTTPS is handled by proxies that perform edge TLS termination.
=> Remove UseHttpsRedirection middleware

.gitops/charts/traffic-court-dev-values.yaml, .gitops/charts/traffic-court-online/values.yaml, .gitops/charts/traffic-court-test-values.yaml, docker-compose.yml, src/backend/README.md, src/backend/TrafficCourts/Citizen.Service/Controllers/LookupController.cs, src/backend/TrafficCourts/Citizen.Service/Validators/Rules/CountSectionRule.cs, src/backend/TrafficCourts/Common/Features/Lookups/StatuteLookupService.cs, src/backend/TrafficCourts/Common/Models/Statute.cs, src/backend/TrafficCourts/Test/Citizen.Service/Validators/Rules/CountSectionRuleTest.cs, src/backend/oracle-data-api/pom.xml, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/config/ConfigProperties.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/config/WebClientConfiguration.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/dto/StatuteDTO.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/error/OracleDataApiException.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/StatuteMapper.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/GetStatutesListServiceResponse.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/Statute.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/LookupService.java, src/backend/oracle-data-api/src/main/resources/application.yml, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/LookupServiceTest.java, src/backend/oracle-data-api/src/test/resources/application.yml
- [TCVP-1680](https://justice.gov.bc.ca/jira/browse/TCVP-1680)
- Added Spring WebClient configuration with timeout and retry in order to perform communications with ORDS.
- Added functionality to get statutes from the ORDS statutes endpoint to save into Redis.
- Updated docker-compose and helm chart with the new ORDS connection related environment variables.
- Updated 'Statute' object in Common project to match the json returned from ORDS and saved in Redis. Also, updated StatuteLookupService's section based query as well.
Ran all existing and new unit tests. Ran the project locally and sent a GET request to the "/api/v1.0/codetable/refresh" to trigger …
=> TCVP-1680 Integration with ORDS

docker-compose.yml
Added a fake SMTP email server for local development.
docker-compose up -d now brings up an smtp-server container that catches all emails regardless of the receipient. This way developers can view sent emails in HTML to confirm the structure of the email.
http://localhost:5080/
=> Added fake-smtp server for development

src/backend/TrafficCourts/Citizen.Service/Controllers/DisputesController.cs, src/backend/TrafficCourts/Citizen.Service/Features/Disputes/Create.cs, src/backend/TrafficCourts/Common/Features/Mail/Model/MailTemplateCollection.cs, src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApi.v1_0.json, src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApiClient.cs, src/backend/TrafficCourts/Staff.Service/Controllers/DisputeController.cs, src/backend/TrafficCourts/Staff.Service/Mappers/Mapper.cs, src/backend/TrafficCourts/Staff.Service/Services/DisputeService.cs, src/backend/TrafficCourts/Workflow.Service/Consumers/EmailVerificationReceivedConsumer.cs, src/backend/TrafficCourts/Workflow.Service/Services/IOracleDataApiService.cs, src/backend/TrafficCourts/Workflow.Service/Services/OracleDataApiService.cs, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeController.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeService.java
Refactoring to cleanup naming convention. EmailValidation should be EmailVerification in the context of verifying one's email.
Updated citizen-api endpoint
/api/disputes/email/{uuid}/validate
Updated oracle-data-api endpoint
/dispute/email/{uuid}/validate
=> Renamed email validate endpoint to verify

infrastructure/keycloak/staff-api-authz-config.json, src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApi.v1_0.json, src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApiClient.cs, src/backend/TrafficCourts/Staff.Service/Authentication/Scopes.cs, src/backend/TrafficCourts/Staff.Service/Controllers/JJController.cs, src/backend/TrafficCourts/Staff.Service/Services/IJJDisputeService.cs, src/backend/TrafficCourts/Staff.Service/Services/JJDisputeService.cs, src/backend/TrafficCourts/TrafficCourts.Staff.Service.Test/Controllers/JJControllerTest.cs, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/JJDisputeController.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/JJDisputeService.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/JJDisputeControllerTest.java
- [TCVP-1695](https://justice.gov.bc.ca/jira/browse/TCVP-1695)
- [TCVP-1696](https://justice.gov.bc.ca/jira/browse/TCVP-1696)
- Through a separate put endpoint, added functionality to assign one or more JJDisputes to a JJ, or unassign them if a username is not specified.
- Through separate put endpoints, added functionality to set JJ Dispute status to review and accepted along with remarks from the user.
- Updated the OpenApi spec json and added controller and service in Staff API to pass the request to Oracle API in order to assign/unassign one or more JJ Disputes to a JJ. 
- Added controller and service in Staff API to pass the request to Oracle API in order to update a JJ Dispute's status to Review and Accepted.
- Added specific …
=> TCVP-1695 Adds assign JJ feature through a separate update endpoint and authorization

src/backend/oracle-data-api/pom.xml, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeController.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/DisputeRepository.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/h2/DisputeRepositoryImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/ords/DisputeRepositoryImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeService.java, src/backend/oracle-data-api/src/main/resources/occm-openapi-spec.yaml, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/impl/ords/DisputeServiceImplTest.java
TCVP-1741
- Implemented unassignDispute that calls ORDS. 
- Moved unassignDispute logic from DisputeService to DisputeRepository so it can be implemented differently by H2 or ORDS
- Changed ApiException so it extends RuntimeException so it can propagate up to controller
- Added junit tests
new junit tests,
mvn verify
=> TCVP-1741 impl unassignDispute

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/DisputeMapper.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/DisputeStatus.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/DisputeRepository.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/h2/DisputeRepositoryCustom.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/h2/DisputeRepositoryCustomImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/h2/DisputeRepositoryImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/ords/DisputeRepositoryImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeService.java, src/backend/oracle-data-api/src/main/resources/occm-openapi-spec.yaml, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeControllerTest.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/impl/ords/DisputeServiceImplTest.java
TCVP-1739
- exposed ORDS endpoints assignViolationTicket and violationTicketStatus in OpenAPI spec
- Implemented DisputeRepository.setStatus() for ORDS
- Implemented DisputeRepository.assignDispute() for ORDS (I changed my mind with this. By calling this, only the 2 fields are updated, not everything else)
- enhanced DisputeStatus enum so it's compatible with ORDS (in ORDS, the enum values are 4 characters max)
- updated DisputeMapper to properly parse ORDS dateTime objects and the DisputeStatus enum
- added a DisputeRepository.flushAndClear() that can be called for H2 (so the objects get properly flushed and reloaded) and ignored for ORDS
- moved assignDispute and setStatus to repository so the implementation can get overridden by ORDS
- …
=> TCVP-1739 impl set Dispute status

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/DisputeRepository.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/h2/DisputeRepositoryCustom.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/h2/DisputeRepositoryCustomImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/ords/DisputeRepositoryImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeService.java, src/backend/oracle-data-api/src/main/resources/occm-openapi-spec.yaml, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/impl/ords/DisputeServiceImplTest.java
- Updated OpenApi spec file to integrate dispute update endpoint from ORDS.
- Added new DisputeRepository custom update method to be able to update a given dispute with its id both through ORDS and in H2 database.
- Added JUnit tests for update dispute ORDS request.
Ran Oracle API locally and sent proper request to the update dispute endpoint and confirmed the records in both ORDS and H2 updated successfully.
=> TCVP-1737 integrate update dispute ords

docker-compose.yml, src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApi.v1_0.json, src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApiClient.cs, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/config/ApiClientConfiguration.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/DisputeMapper.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/Auditable.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/Dispute.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/DisputeCount.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/h2/DisputeRepositoryImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/h2/EmailHistoryRepositoryImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/h2/JJDisputeRepositoryImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/ords/DisputeRepositoryImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/ords/EmailHistoryRepositoryImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/ords/JJDisputeRepositoryImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/scheduled/StartupTasks.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/impl/csv/LookupServiceImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/impl/ords/LookupServiceImpl.java, src/backend/oracle-data-api/src/main/resources/application.yml, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/BaseTestSuite.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/LookupServiceTest.java, src/backend/oracle-data-api/src/test/resources/application.yml
ORDS integration
- split ords.enabled flag so it's more granular. There are now 4 properties instead that can be changed via ENV vars:
```
repository:
lookup: ${LOOKUP_REPOSITORY_SRC:ords}
dispute: ${DISPUTE_REPOSITORY_SRC:ords}
jjdispute: ${JJDISPUTE_REPOSITORY_SRC:h2}
history: ${HISTORY_REPOSITORY_SRC:h2}
```
Made a few tweaks to the model so the staff-api doesn't error when pulling OCCAM data.
- modifiedTs is nullable
- modifiedBy is nullable
- temporarily removed noticeOfDisputeId since it's missing from ORDs
- temporarily removed disputeCountId since it's missing from ORDs
mvn verify
=> Oracle Data API: made ords.enabled more granular to allow enabling portions at a time.

src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.html, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.ts, src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-assignments/jj-dispute-assignments.component.html, src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-assignments/jj-dispute-assignments.component.ts, src/frontend/staff-portal/src/app/components/staff-workbench/dispute-decision-inbox/dispute-decision-inbox.component.ts, src/frontend/staff-portal/src/app/config/config.service.ts, src/frontend/staff-portal/src/app/services/auth.service.ts, src/frontend/staff-portal/src/app/services/jj-dispute.service.ts
- stop using hard coded list of JJs, needed for functional user testing
- sign into staff portal using test user id that has no special keycloak privileges except belonging to group admin-judicial-justice
- confirm that user can see list of JJs in staff portal
=> use dynamic jj list from keycloak

.env.template, docker-compose.yml, src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApi.v1_0.json, src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApiClient.cs, src/backend/TrafficCourts/Staff.Service/Services/DisputeService.cs, src/backend/TrafficCourts/Workflow.Service/Mappings/MappingProfile.cs, src/backend/TrafficCourts/Workflow.Service/Services/OracleDataApiService.cs, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/config/ApiClientConfiguration.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeController.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/DisputeMapper.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/ViolationTicketMapper.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/Dispute.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/DisputeCount.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/DisputeRepository.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/ords/DisputeRepositoryImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeService.java, src/backend/oracle-data-api/src/main/resources/application.yml, src/backend/oracle-data-api/src/main/resources/occm-openapi-spec.yaml, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeServiceTest.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/impl/ords/DisputeServiceImplTest.java, src/backend/oracle-data-api/src/test/resources/application.yml, src/frontend/staff-portal/package.json, src/frontend/staff-portal/src/app/api/model/dispute.model.ts, src/frontend/staff-portal/src/app/api/swagger.json
TCVP-1833
- Enabled console logging to some .NET containers to help with debugging when running locally in docker-compose
- Fixed mapping issues when there's bad data in Oracle
- Added missing TicketNumber value to ViolationTicket
- Fixed debugging statements
- Removed deprecated emailVerificationToken field
- 
mvn verify
ran tests in .NET
docker-compose up -d --build to confirm entire workflow works and data is persisted/loaded from ORDs.
=> TCVP-1883 Enable ORDs for persistence

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/ViolationTicketMapper.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/Dispute.java
- [TCVP-1855](https://justice.gov.bc.ca/jira/browse/TCVP-1885)
- Added an after mapping method to parse address source into multiple address fields based on the column length when inserting data through ORDS.
Ran the app locally and sent a request to save a dispute with lawyer address field having more than 200 characters and confirmed that it was parsed into separate fields.
=> TCVP-1855 Added mapping method to parse lawyer address field

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/config/ApiClientConfiguration.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/config/ConfigProperties.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/DisputeMapper.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/Dispute.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/ViolationTicket.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/ViolationTicketCount.java, src/backend/oracle-data-api/src/main/resources/application.yml, src/backend/oracle-data-api/src/main/resources/occm-openapi-spec.yaml, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeServiceH2Test.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeServiceOrdsTest.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/util/RandomUtil.java, src/backend/oracle-data-api/src/test/resources/application.yml
Create junit regression test to confirm Mapping to/from ORDS. The test creates a fully populated Dispute where every field is at the character limit, persists to ORDS, reads the new records from ORDS, then compares and prints the differences - the original and persisted objects should be identical.
- created ENV variable for enabling ORDS debugging
- fixed mapping of courtLocation
- fixed missing size constraints in TCO model
- moved DisputeServiceTest to DisputeServiceH2Test and created new DisputeServiceOrdsTest 
To run this test, ensure the following ENV variables are set:
- DISPUTE_REPOSITORY_SRC
- ORDS_API_URL
- ORDS_API_DEBUG
`mvn test …
=> Created junit test to confirm Mapping to/from ords

src/backend/TrafficCourts/Citizen.Service/Features/Disputes/Create.cs, src/backend/TrafficCourts/Common/Features/FilePersistence/FilePersistenceService.cs, src/backend/TrafficCourts/Common/Features/FilePersistence/IFilePersistenceService.cs, src/backend/TrafficCourts/Common/Features/FilePersistence/InMemoryFilePersistenceService.cs, src/backend/TrafficCourts/Common/Features/FilePersistence/MinioFilePersistenceService.cs, src/backend/TrafficCourts/Staff.Service/Services/DisputeService.cs, src/backend/TrafficCourts/TrafficCourts.Common.Test/Features/FilePersistence/MinioFilePersistenceServiceTest.cs
- [TCVP-1903](https://justice.gov.bc.ca/jira/browse/TCVP-1903)
- Fixes a bug that was causing not being able to save OCR violation ticket JSON data into database through changing the approach to save and retrieve the data from Minio object storage.
- Added a generic file persistence service method to save json objects into minio object storage. Also updated dispute create process to store ocr violation ticket data in object storage as json file with a filename same as created dispute's violationTicketGuid.
- Added a file persistence service method to get deserialized json object by filename if target deserialization object type matches. Also updated Staff API dispute service to retrieve the OcrViolationTicket from object storage.
- Added …
=> TCVP-1903 functionality to save/retrieve ocr json data to/from object storage

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeService.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeControllerTest.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/util/RandomUtil.java
TCVP-1918
- Updated the saving of a Dispute in the oracle-data-api to throw a 400 if the duplicate TicketNumber on the Dispute and ViolationTicket doesn't match.
- Added junit test
mvn verify
=> TCVP-1918 enforced duplicate field TicketNumber has same values

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/DisputeMapper.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/ViolationTicketMapper.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/Dispute.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/JJDispute.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/util/RandomUtil.java
TCVP-1921
Fixed mapping of interpreterLanguageCd in oracle-data-api only.  
This change part of a larger set of changes for TCVP-1943 (story). Once all sub-tasks for 1943 are completed, the entire branch can be merged into main.
integration tests no longer complains about this field.
=> TCVP-1921 Fixed mapping of interpreterLanguage

src/backend/TrafficCourts/Citizen.Service/Features/Disputes/Create.cs, src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApi.v1_0.json, src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApiClient.g.cs, src/backend/TrafficCourts/Messaging/MessageContracts/SubmitNoticeOfDispute.cs, src/backend/TrafficCourts/Staff.Service/Services/DisputeService.cs, src/backend/TrafficCourts/Test/Workflow.Service/Mappings/MappingTests.cs, src/backend/TrafficCourts/TrafficCourts.Staff.Service.Test/Services/DisputeServiceTest.cs, src/backend/TrafficCourts/Workflow.Service/Services/OracleDataApiService.cs, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/DisputeMapper.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/ViolationTicketMapper.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/Dispute.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/util/RandomUtil.java
- TCVP-1903
- Added functionality to save filename of an OCRed violation ticket in the database instead of saving the whole violation ticket JSON.
- Used the filename for a few validations to determine the violation ticket type and retrieve ticket data from object storage.
=> TCVP-1903 - Part 2- Save OCR Ticket JSON Filename

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/DisputeMapper.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/ViolationTicketMapper.java, src/backend/oracle-data-api/src/main/resources/occm-openapi-spec.yaml
- Refactored Oracle Data API to match database changes for renaming ocrViolationTicketJsonTxt field to ocrTicketJsonFilenameTxt.
- Updated mappings and open api spec for ocrTicketJsonFilenameTxt.
- Updated noticeOfDisputeGuid in open api spec to set max length to 36 chars.
=> Rename and update mapping for ocr violation ticket json field

src/backend/oracle-data-api/pom.xml, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/DisputeMapper.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/ViolationTicketMapper.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/Auditable.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/Dispute.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/ViolationTicket.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/ords/DisputeRepositoryImpl.java, src/backend/oracle-data-api/src/main/resources/occm-openapi-spec.yaml, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/impl/ords/DisputeServiceImplTest.java
- Fixes the bugs: [TCVP-1911](https://justice.gov.bc.ca/jira/browse/TCVP-1911) and [TCVP-1919](https://justice.gov.bc.ca/jira/browse/TCVP-1919)
- Updated all date-time fields' format to be compatible with UTC time ISO standard as well as match those fields' format in JSON for ORDS serialization/deserialization of date-time format.
- Removed unnecessary usage of java.sql.Date library from the pom file for generated sources and tests.
Created a new dispute record in Oracle database with all date fields provided by sending a request through Oracle API. Sent a GET request to the Oracle API to return the same record and compared the date fields' format with the …
=> TCVP-1911 and TCVP-1919 - save and get all dates in UTC

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeController.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeControllerTest.java
TCVP-1834
Moved the endpoint to /api/dispute/status to make is more clear that this endpoint doesn't return a Dispute, but rather DisputeStatuses.
mvn verify
=> TCVP-1834 updated findDisputeByTicketNumber endpoint

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/DisputeMapper.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/ViolationTicketMapper.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/DisputeMapperTest.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/ViolationTicketMapperTest.java
- [TCVP-1956](https://justice.gov.bc.ca/jira/browse/TCVP-1956)
- Fixed the after mapping method logic to concatenate multiple lawyer address fields into single field when returning dispute data from ords.
- Added JUnit tests for mappers to verify the logic of lawyer address field custom mapping method.
Ran mvn verify
=> TCVP-1956 Fix lawyer address field mapping

infrastructure/openshift/tools/image-streams/dotnet.yaml, infrastructure/openshift/tools/image-streams/eclipse-temurin.yaml, infrastructure/openshift/tools/image-streams/maven.yaml, infrastructure/openshift/tools/image-streams/node.yaml, infrastructure/openshift/tools/image-streams/rabbitmq.yaml, infrastructure/openshift/tools/image-streams/redis-exporter.yaml, infrastructure/openshift/tools/image-streams/redis.yaml
- Adds image stream objects for builds. I tried to add to ArgoCD, but ArgoCD does not like OpenShift specific objects.
these will need to be `oc apply`ed
=> Add mirrored image streams for version we depend on

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/Auditable.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/DisputantUpdateRequest.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/DisputantUpdateStatus.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/DisputantUpdateType.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/ShortNamedEnum.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/ShortNamedEnumType.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/DisputantUpdateRequestRepository.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeService.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeServiceH2Test.java
TCVP-1963
Added a model object for DisputantUpdateRequests. This is the first step for TCVP-1963, endpoints forthcoming.
- the disputeId is just a Long since this this object may be stored in H2 for now, while the parent Dispute object in ORDs. 
- added a DisputantUpdateType enum that when serialized to the database, appears as a 3 character short name, not the full enum name.
- added a ShortNamedEnum to easily serialize/deserialize enums to/from the database.
- added junit test
mvn verify
=> TCVP-1963 added DisputantUpdateRequest model

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeController.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/DisputantUpdateRequest.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/DisputantUpdateRequestRepository.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeService.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeServiceH2Test.java
TCVP-1963
Added endpoints:
```
POST /api/dispute/{guid}/updateRequest
GET /api/dispute/{id}/updateRequest
PUT /api/dispute/updateRequest/{id}
```
The POST will create a new DisputantUpdateRequest record in H2
The GET will return all DisputantUpdateRequest records in H2 that for the given disputeId.
The PUT will upstate the status of a particular DisputantUpdateRequest record in H2.
Added junit tests
mvn verify
=> TCVP-1963 Added endpoints for DisputantUpdateRequest

src/backend/TrafficCourts/Messaging/MessageContracts/DisputeApproved.cs, src/backend/TrafficCourts/Staff.Service/Mappers/Mapper.cs, src/backend/TrafficCourts/Test/Arc.Dispute.Service/Mappings/MappingTests.cs, src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Client/ArcDisputeClient.g.cs, src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Client/swagger.json, src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/Mappings/DisputeTicketToArcFileRecordListConverter.cs, src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/Models/ArcFileRecord.cs, src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/Models/TcoDisputeTicket.cs
- fixes issue where transaction date and time are slightly different on each record.
- removes the milliseconds from the date and times
- splits out the name fields into separate properties - CitizenName is deprecated but will be used first if not null.
=> Ensure transaction date and time are the same on each record

src/backend/TrafficCourts/Test/Workflow.Service/Consumers/DisputantUpdateRequestAcceptedConsumerTest.cs, src/backend/TrafficCourts/Test/Workflow.Service/Mappings/MappingTests.cs, src/backend/TrafficCourts/Workflow.Service/Consumers/DisputantUpdateRequestAcceptedConsumer.cs, src/backend/TrafficCourts/Workflow.Service/Services/IOracleDataApiService.cs, src/backend/TrafficCourts/Workflow.Service/Services/OracleDataApiService.cs
TCVP-1975
Added logic to save dispute changes per the DisputantUpdateRequest object when the request is accepted.
dotnet test
docker-compose up
=> TCVP-1975 saved dispute changes

src/backend/TrafficCourts/Common/Features/Mail/Model/MailTemplateCollection.cs, src/backend/TrafficCourts/Messaging/MessageContracts/DisputantUpdateRequestRejected.cs, src/backend/TrafficCourts/Staff.Service/Controllers/DisputeController.cs, src/backend/TrafficCourts/Staff.Service/Services/DisputeService.cs, src/backend/TrafficCourts/Staff.Service/Services/IDisputeService.cs, src/backend/TrafficCourts/Test/Workflow.Service/Consumers/DisputantUpdateRequestRejectedConsumerTest.cs, src/backend/TrafficCourts/Workflow.Service/Consumers/DisputantUpdateRequestAcceptedConsumer.cs, src/backend/TrafficCourts/Workflow.Service/Consumers/DisputantUpdateRequestRejectedConsumer.cs
TCVP-1974
Created an endpoint in the staff-api that rejects a DisputantUpdateRequest
`/api/dispute/updaterequest/{id}/reject`
The endpoint (via the workflow worker service)
- calls oracle-data-api to update DisputantUpdateRequest status.
- send confirmation email indicating request was rejected
- adds a file history record
=> TCVP-1974 added RejectDisputeUpdateRequest endpoint

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/DisputeMapper.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/ViolationTicketMapper.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/DisputeResult.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/ords/DisputeRepositoryImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeService.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/util/DateUtil.java, src/backend/oracle-data-api/src/main/resources/occm-openapi-spec.yaml, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeControllerTest.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/JJDisputeControllerTest.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/impl/ords/DisputeServiceImplTest.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/util/DateUtilTest.java
TCVP-1833
Enhanced the returned result for the `/api/v1.0/dispute/status` endpoint to also include jjDispute status.
Sample response in Swagger:
`curl -X 'GET' 'http://localhost:5010/api/v1.0/dispute/status?ticketNumber=AX12345678&issuedTime=08%3A00'
`
- Fixed junit tests
- Refactored/moved DisputeRepositoryImpl.DATE_TIME_FORMAT to a DateUtil class
=> TCVP-1833 Added jjDisputeStatus to find query

src/backend/TrafficCourts/Test/Arc.Dispute.Service/Mappings/MappingTests.cs, src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/Mappings/DisputeTicketToArcFileRecordListConverter.cs, src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/Models/TcoDisputeTicket.cs
- Fix issue where dispute record citizen name was not mapped the same way as the adnotated record
- Added unit tests to validate the citizen's name is mapped correctly
=> Fix mapping of name on dispute ARC record. Add unit tests

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/config/OrdsTcoApiClientConfiguration.java, src/backend/oracle-data-api/src/main/resources/tco-openapi-spec.yaml, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeServiceOrdsTcoTest.java
TCVP-1995
Added an OpenAPI endpoint for ORDS-TCO for retrieving a JJDispute from TCO.
Added an integration test to confirm the record successfully pulls from the database.
The datatype of each field is mostly just string for now.  Someone with database access will need to go through each field and confirm the datatype and nullable aspects.
mvn verify
=> TCVP-1995 added GET jjDispute endpoint

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeController.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/DisputantUpdateRequestStatus.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeService.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeServiceH2Test.java
- [TCVP-1983](https://justice.gov.bc.ca/jira/browse/TCVP-1983)
- Added 'HOLD' status to DisputantUpdateRequestStatus enum.
- Created the endpoint and service to receive a list of DisputantUpdateRequest IDs and based on those IDs, update the status of one or more DisputantUpdateRequest records to PENDING from HOLD only.
- Changing the status is only permitted from HOLD to PENDING for any of the DisputantUpdateRequest records submitted.
- Partial update is not allowed. If any of the submitted IDs cannot be found in the database, the whole update will throw 404 and all statuses will remain the same. 
Tested by creating new test records in H2 database and …
=> TCVP-1983 add disputant update requests status change

src/backend/TrafficCourts/Citizen.Service/Controllers/DisputesController.cs, src/backend/TrafficCourts/Citizen.Service/Models/Dispute/DisputantContactInformation.cs, src/backend/TrafficCourts/Citizen.Service/Models/Dispute/DisputeCount.cs, src/backend/TrafficCourts/Citizen.Service/Models/Dispute/NoticeOfDispute.cs, src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApi.v1_0.json, src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApiClient.g.cs, src/backend/TrafficCourts/Messaging/MessageContracts/DisputantUpdateRequest.cs, src/backend/TrafficCourts/Messaging/MessageContracts/SearchDispute.cs, src/backend/TrafficCourts/Test/Workflow.Service/Consumers/DisputantUpdateRequestAcceptedConsumerTest.cs, src/backend/TrafficCourts/Test/Workflow.Service/Consumers/DisputantUpdateRequestRejectedConsumerTest.cs, src/backend/TrafficCourts/Test/Workflow.Service/Consumers/SearchDisputeConsumerTest.cs, src/backend/TrafficCourts/Workflow.Service/Consumers/DisputantUpdateRequestAcceptedConsumer.cs, src/backend/TrafficCourts/Workflow.Service/Consumers/DisputantUpdateRequestRejectedConsumer.cs, src/backend/TrafficCourts/Workflow.Service/Consumers/SearchDisputeConsumer.cs, src/backend/TrafficCourts/Workflow.Service/Services/IOracleDataApiService.cs, src/backend/TrafficCourts/Workflow.Service/Services/OracleDataApiService.cs, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeController.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/error/ControllerAdvisor.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeService.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeControllerTest.java
TCVP-2007
Citizen API - added PUT endpoint to process a disputant's contact info
`PUT /api/dispute/{guidhash}/contact`
body:
```
{
"email_address": "",
"disputant_given_name1": "",
"disputant_given_name2": "",
"disputant_given_name3": "", 
"disputant_surname": "", 
"address_line1": "", 
"address_line2": "", 
"address_line3": "", 
"address_city": "", 
"address_province": "", 
"address_province_country_id": "",
"address_province_seq_no": "",
"address_country_id": "",
"postal_code": "", 
"home_phone_number": ""
}
```
response codes:
**200** - Ok
**400** - If the Dispute's status is not one of [NEW, VALIDATED, PROCESSING] or JJDispute status is non-null
**404** - If the Dispute could not be found.
**500** - Internal Server Error
If the …
=> TCVP-2007 Added PUT endpoint to process a disputant's contact info

src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApi.v1_0.json, src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApiClient.g.cs, src/backend/TrafficCourts/Test/Workflow.Service/Consumers/DisputantUpdateRequestConsumerTest.cs, src/backend/TrafficCourts/Workflow.Service/Consumers/DisputantUpdateRequestAcceptedConsumer.cs, src/backend/TrafficCourts/Workflow.Service/Consumers/DisputantUpdateRequestConsumer.cs, src/backend/TrafficCourts/Workflow.Service/Services/IOracleDataApiService.cs, src/backend/TrafficCourts/Workflow.Service/Services/OracleDataApiService.cs, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/DisputeResult.java
TCVP-2012
- Created DisputantUpdateRequestConsumer
- Added useless C# Moq Tests
The consumer will consume a DisputantUpdateRequest request and will save necessary DisputantUpdateRequest records into ORDS.
docker-compose up, confirmed messages from citizen-api go through the workflow service and are saved in the H2 database.
=> TCVP-2012 Created Workflow Service DisputantUpdateRequestConsumer

src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApi.v1_0.json, src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApiClient.g.cs, src/backend/TrafficCourts/Workflow.Service/Consumers/DisputantUpdateRequestConsumer.cs, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeController.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/DisputantUpdateRequestStatus.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeService.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeServiceH2Test.java
- Removed DisputantUpdateRequestStatus.HOLD status since we are no longer using this enum value.
- Removed endpoint and service call that uses this deprecated HOLD value.
- Removed tests that test the removed endpoint and service call.
- Regenerated OpenAPI spec
mvn verify
dotnet test
=> OracleApi - Removed DisputantUpdateRequestStatus.HOLD status

src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApi.v1_0.json, src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApiClient.g.cs, src/backend/TrafficCourts/Workflow.Service/Consumers/EmailVerificationReceivedConsumer.cs, src/backend/TrafficCourts/Workflow.Service/Services/IOracleDataApiService.cs, src/backend/TrafficCourts/Workflow.Service/Services/OracleDataApiService.cs, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeController.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/DisputantUpdateRequestRepository.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeService.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeServiceH2Test.java
TCVP-2009
- Added OracleAPI to fetch DisputantUpdateRequests by status
- Fixed TODO in EmailVerificationReceivedConsumer to send email iff there are update requests.
mvn verify
dotnet test
=> TCVP-2009 Added endpoint to fetch disputantUpdates by status

src/backend/TrafficCourts/Common/Features/Mail/Model/MailTemplateCollection.cs, src/backend/TrafficCourts/Common/Features/Mail/Templates/DisputantUpdateRequestAcceptedTemplate.cs, src/backend/TrafficCourts/Common/Features/Mail/Templates/DisputantUpdateRequestRejectedTemplate.cs, src/backend/TrafficCourts/Common/Features/Mail/Templates/EmailTemplateExtensions.cs, src/backend/TrafficCourts/Common/Features/Mail/Templates/IDisputantUpdateRequestAcceptedTemplate.cs, src/backend/TrafficCourts/Common/Features/Mail/Templates/IDisputantUpdateRequestRejectedTemplate.cs, src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApi.v1_0.json, src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApiClient.g.cs, src/backend/TrafficCourts/Test/Workflow.Service/Consumers/DisputantUpdateRequestAcceptedConsumerTest.cs, src/backend/TrafficCourts/Test/Workflow.Service/Consumers/DisputantUpdateRequestConsumerTest.cs, src/backend/TrafficCourts/Test/Workflow.Service/Consumers/DisputantUpdateRequestRejectedConsumerTest.cs, src/backend/TrafficCourts/Workflow.Service/Consumers/DisputantUpdateRequestAcceptedConsumer.cs, src/backend/TrafficCourts/Workflow.Service/Consumers/DisputantUpdateRequestConsumer.cs, src/backend/TrafficCourts/Workflow.Service/Consumers/DisputantUpdateRequestRejectedConsumer.cs, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/Dispute.java
TCVP-2012 
Updated DisputantUpdateRequestConsumer to:
- only save a DisputantUpdateRequest if there is a matching Dispute
- initiate an email saga if the request included an email change
- allowed updating an email to null (verified)
- send an email confirmation to user if the update was saved (received acknowledgement)
mvn verify
dotnet test
=> TCVP-2012 updated email logic

src/backend/TrafficCourts/Citizen.Service/Validators/FormRecognizerValidator.cs, src/backend/TrafficCourts/Common/Models/OcrViolationTicket.cs, src/backend/TrafficCourts/Test/Citizen.Service/Validators/Rules/CountActRegMustBeMVATest.cs
It can happen that text is too close to the shared border between two adjacent fields. The OCR may incorrectly think one field is blank and the other populate with the blank field's text.
In this example, the OCR thought the ACT/REGS was blank and the SECTION text read "MVA 67(b)".
This PR addresses this particular poor OCR scan result by moving the expected MVA text to the correct field.
dotnet test
=> Fixed merged act/reg - section text from a poor OCR scan

docker-compose.yml
- fixes boolean values in docker compose file that need to be quoted as per the [environment](https://docs.docker.com/compose/compose-file/compose-file-v3/#environment) documenation.
=> quote boolean values in docker compose

src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApi.v1_0.json, src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApiClient.g.cs, src/backend/TrafficCourts/Staff.Service/Authentication/Scopes.cs, src/backend/TrafficCourts/Staff.Service/Controllers/JJController.cs, src/backend/TrafficCourts/Staff.Service/Services/IJJDisputeService.cs, src/backend/TrafficCourts/Staff.Service/Services/JJDisputeService.cs, src/backend/TrafficCourts/TrafficCourts.Staff.Service.Test/Controllers/JJControllerTest.cs, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/JJDisputeController.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/JJDisputeService.java
- [TCVP-1978](https://justice.gov.bc.ca/jira/browse/TCVP-1978)
- This feature also requires functionality to update court appearance along with the status updates. Therefore, once the Oracle Data API endpoint will be ready (TCVP-1999) it should also be called as a part of these new endpoints in Staff API.
- Added new Staff API endpoints to update the status of a particular JJDispute record to REQUIRE_COURT_HEARING or CONFIRMED.
- Restricted endpoint authorization to JJDispute resource and UpdateCourtAppearance scope only.
- Updated OpenAPI Spec from Oracle Data API.
- Added XUnit tests for the new controllers.
Tested the new endpoints through Swagger UI and …
=> TCVP-1978 Update JJDispute status to require court appearance or confirm

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeController.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeService.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeControllerTest.java
TCVP-2036 
Added new endpoint to reset a Disputant's email address
- added junit test to confirm code coverage and functionality
=> TCVP-2036 added /email/reset endpoint to oracle-data-api

src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApi.v1_0.json, src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApiClient.g.cs, src/backend/TrafficCourts/Test/Workflow.Service/Consumers/DisputantUpdateRequestConsumerTest.cs, src/backend/TrafficCourts/Workflow.Service/Consumers/DisputantUpdateRequestConsumer.cs, src/backend/TrafficCourts/Workflow.Service/Consumers/DisputantUpdateRequestRejectedConsumer.cs, src/backend/TrafficCourts/Workflow.Service/Services/IOracleDataApiService.cs, src/backend/TrafficCourts/Workflow.Service/Services/OracleDataApiService.cs, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeController.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeService.java
TCVP-2037
- Updated the DisputantUpdateRequestConsumer to reset the emailAddress and emailVerificationFlag when the payload contains an email address change.
- Updated Oracle Data API /email/reset to return the updated Dispute record.
dotnet test
=> TCVP-2037 added reset email to DisputantUpdateRequestConsumer

src/backend/TrafficCourts/Workflow.Service/Consumers/DisputantUpdateRequestConsumer.cs
- Fixes a bug through setting `disputeId` to the message for requesting email verification when disputant email update requested.
=> Bugfix for nothing happens when email verification link is clicked for disputant update request

src/backend/TrafficCourts/TrafficCourts.Coms.Client.Test/IntegrationTest.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client.Test/ServiceTests/DeleteFileAsync.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client.Test/TrafficCourts.Coms.Client.Test.csproj, src/backend/TrafficCourts/TrafficCourts.Coms.Client/File.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/Models.g.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/ObjectManagementService.cs
- Changes the UpdatedBy in the COMS generated code to nullable. Relates to bug [#87](https://github.com/bcgov/common-object-management-service/issues/87) in the COMS project
- The ObjectManagementService now handles not found on delete and does not throw error
- Adds integration test to validate ObjectManagementService calls work correctly
=> TCVP-2087 Investigate COMS error when creating files

src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApi.v1_0.json, src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApiClient.g.cs, src/backend/TrafficCourts/Staff.Service/Services/JJDisputeService.cs, src/backend/TrafficCourts/Workflow.Service/Services/IOracleDataApiService.cs, src/backend/TrafficCourts/Workflow.Service/Services/OracleDataApiService.cs, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeController.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/JJDisputeController.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/JJDisputeRepository.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/h2/JJDisputeRepositoryImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/ords/JJDisputeRepositoryImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeService.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/JJDisputeService.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeControllerTest.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/JJDisputeControllerTest.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/util/RandomUtil.java
TCVP-1954
JJDisputes are now unique w.r.t to the TicketNumber. As such, queries that attempt to find a JJDispute by TicketNumber and Time can be simplified by removing the andTime logic.
mvn verify
dotnet test
=> TCVP-1954 removed andTime from JJDIspute queries

src/backend/TrafficCourts/TrafficCourts.Coms.Client.Test/ClientTests/SearchObjectsAsync.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client.Test/IntegrationTest.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client.Test/ServiceTests/CreateFileAsync.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client.Test/ServiceTests/FileSearchAsync.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client.Test/ServiceTests/GetFileAsync.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client.Test/ServiceTests/ObjectManagementServiceTest.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client.Test/ServiceTests/UpdateFileAsync.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/ComsJsonContext.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/Factory.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/File.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/IObjectManagementClient.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/MetadataValidator.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/Models.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/ObjectManagementClient.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/ObjectManagementClient.g.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/ObjectManagementService.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/RequestBuilder.cs
- Fetches document metadata from the undocumented `/object/metadata` endpoint.
- Added nullable Guid File.Id property
- When creating a file, the File.Id is set with the created file id.
=> TCVP-2097 fix bug related to fetching metadata

src/backend/TrafficCourts/Staff.Service/Controllers/ComsController.cs, src/backend/TrafficCourts/Staff.Service/Services/ComsService.cs, src/backend/TrafficCourts/Staff.Service/Services/IComsService.cs, src/backend/TrafficCourts/TrafficCourts.Staff.Service.Test/Controllers/ComsControllerTest.cs
- [TCVP-2054](https://justice.gov.bc.ca/jira/browse/TCVP-2054)
- Added functionality to remove a document for the given unique file ID and track file deletion in file history.
- Added XUnit tests.
Ran the services locally and uploaded a file using swagger ui and called the new endpoint to remove the file and confirmed that the file has been deleted successfully.
=> TCVP-2054 staff remove single document

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/Auditable.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/JJDispute.java
Fixed a bug where the JJDisputeHearingType enum was modified to use a shortCode but forgot to also register the enum in a TypeDef so Hibernate knows how to convert the enum to/from the database.
`curl -X 'GET' 'http://localhost:5010/api/v1.0/jj/disputes'` works again.
mvn verify
=> Fixed mapping of JJDisputeHearingType

src/backend/TrafficCourts/Common/Models/JJDispute.cs, src/backend/TrafficCourts/Staff.Service/Controllers/ComsController.cs, src/backend/TrafficCourts/Staff.Service/Controllers/JJController.cs, src/backend/TrafficCourts/Staff.Service/Services/ComsService.cs, src/backend/TrafficCourts/Staff.Service/Services/IComsService.cs, src/backend/TrafficCourts/Staff.Service/Services/JJDisputeService.cs, src/backend/TrafficCourts/TrafficCourts.Staff.Service.Test/Controllers/ComsControllerTest.cs, src/backend/TrafficCourts/TrafficCourts.Staff.Service.Test/Controllers/JJControllerTest.cs
- [TCVP-2000](https://justice.gov.bc.ca/jira/browse/TCVP-2000)
- Added functionality to return all the related file IDs in a dictionary as keys while filenames as values of the uploaded documents through COMS when returning a single JJDispute.
- Added XUnit tests for the controller endpoint.
- Fixed a small bug with authorization for the COMS file upload endpoint.
=> TCVP-2000 - Get Document IDs when Staff API Get JJDispute called

src/backend/TrafficCourts/TrafficCourts.Coms.Client.Test/ClientTests/ObjectManagementBase.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client.Test/IntegrationTest.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client.Test/TrafficCourts.Coms.Client.Test.csproj, src/backend/TrafficCourts/TrafficCourts.Coms.Client/ComsJsonContext.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/Factory.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/File.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/FileSearchParameters.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/FileSearchResult.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/Metadata.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/MetadataValidator.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/Models.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/ObjectManagementClient.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/ObjectManagementService.cs
- Returns the filename on file search.
- Filters out internal metadata from metadata returned
- Does not allow setting internal metadata via metadata dictionary
=> add fetching filename in file search

src/backend/TrafficCourts/Staff.Service/Services/ComsService.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client.Test/ServiceTests/FileSearchAsync.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/FileSearchParameters.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/IObjectManagementService.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/ObjectManagementService.cs
- does not try to fetch metadata if no files found
- switch to file search instead of get file when deleting file in staff portal
=> Fix exception thrown when no files found during search

docker-compose.yml, src/backend/TrafficCourts/Citizen.Service/Services/IComsService.cs, src/backend/TrafficCourts/Citizen.Service/Services/Impl/ComsService.cs, src/backend/TrafficCourts/Citizen.Service/Startup.cs, src/backend/TrafficCourts/Citizen.Service/TrafficCourts.Citizen.Service.csproj, src/backend/TrafficCourts/Citizen.Service/appsettings.Development.json, src/backend/TrafficCourts/Messaging/MessageContracts/DisputantUpdateRequest.cs, src/backend/TrafficCourts/Workflow.Service/Consumers/DisputantUpdateRequestConsumer.cs
- [TCVP-2048](https://justice.gov.bc.ca/jira/browse/TCVP-2048)
- Added COMS service to Citizen API to consume object management service client.
- Updated disputant update request consumer to send a DISPUTANT_DOCUMENT type request.
- Updated configuration and docker-compose file to add COMS service for Citizen API.
- Added functionality to update file history when a disputant uploads a document.
=> TCVP-2048 Add service for citizen api upload documents

src/backend/TrafficCourts/Citizen.Service/Services/IComsService.cs, src/backend/TrafficCourts/Citizen.Service/Services/Impl/ComsService.cs
- [TCVP-2089](https://justice.gov.bc.ca/jira/browse/TCVP-2089)
- Added COMS service method to remove a disputant uploaded document for the given unique file ID and track file deletion in file history.
=> TCVP-2089 Citizen API remove uploaded document

src/backend/TrafficCourts/Citizen.Service/Services/IComsService.cs, src/backend/TrafficCourts/Citizen.Service/Services/Impl/ComsService.cs
- [TCVP-2044](https://justice.gov.bc.ca/jira/browse/TCVP-2044)
- Added COMS service method in Citizen API to return all the related file IDs in a dictionary as keys while filenames as values of the uploaded documents based on search parameters (metadata) through COMS.
- TODO: A controller endpoint needs to be added to consume the service to return the list of documents after the BC Services Card authentication feature will be merged. Also the XUnit tests should be added for the endpoint.
=> TCVP-2044 Citizen API get uploaded documents list

.gitops/charts/traffic-court-dev-values.yaml
- changes dev to use in memory for H2
I ran `helm template traffic-court-online --values traffic-court-dev-values.yaml` from the `.gitops\charts` directory and observed the environment variable in the deployment,
=> Change dev environment to use in memory version of H2.

src/backend/TrafficCourts/TrafficCourts.Coms.Client.Test/ServiceTests/GetFileAsync.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/File.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/IObjectManagementService.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/ObjectManagementService.cs
- When create a `File` object, the data stream passed will be rewound to the beginning.
- Add unit test to ensure ReadObjectAsync returns a stream with position = 0
- Added XML docs to IObjectManagementService
- 
=> Reset stream position when creating File, add docs

src/backend/TrafficCourts/Citizen.Service/Services/IComsService.cs, src/backend/TrafficCourts/Citizen.Service/Services/Impl/ComsService.cs, src/backend/TrafficCourts/Common/Models/FileMetadata.cs, src/backend/TrafficCourts/Common/Models/JJDispute.cs, src/backend/TrafficCourts/Staff.Service/Controllers/ComsController.cs, src/backend/TrafficCourts/Staff.Service/Services/ComsService.cs, src/backend/TrafficCourts/Staff.Service/Services/IComsService.cs, src/backend/TrafficCourts/Workflow.Service/Consumers/VirusScanDocumentConsumer.cs, src/backend/TrafficCourts/Workflow.Service/Services/VirusScanService.cs
- [TCVP-2109](https://justice.gov.bc.ca/jira/browse/TCVP-2109)
- Added functionality to kick off a virus scan message to the workflow service on successful document upload. 
- Changed response type to be a list of file metadata object on document search instead of dictionary. 
- Fixed some minor issues.
=> TCVP-2109 publish message for virus scan

src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApi.v1_0.json, src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApiClient.g.cs, src/backend/TrafficCourts/Staff.Service/Services/JJDisputeService.cs, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/JJDisputeController.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/JJDisputeRepository.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/h2/JJDisputeRepositoryImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/ords/JJDisputeRepositoryImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/JJDisputeService.java, src/backend/oracle-data-api/src/main/resources/tco-openapi-spec.yaml, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/JJDisputeControllerTest.java
- [TCVP-2123](https://justice.gov.bc.ca/jira/browse/TCVP-2123)
- Added functionality to update a JJDispute's status through the ORDS endpoint.
- Added functionality to update a JJDispute's court appearances through the ORDS endpoint if the status is being updated into `ACCEPTED`.
- Updated Oracle Data APi OpenApi spec client and `AcceptJJDisputeAsync` method to match new optional parameters.
=> TCVP-2123 update TCO dispute status through ORDS

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/JJDisputeMapper.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/JJDispute.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/JJDisputeRemark.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/JJDisputeRemarkRepository.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/JJDisputeRepository.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/h2/JJDisputeRemarkRepositoryImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/h2/JJDisputeRepositoryImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/ords/JJDisputeRemarkRepositoryImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/ords/JJDisputeRepositoryImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/JJDisputeService.java, src/backend/oracle-data-api/src/main/resources/tco-openapi-spec.yaml, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/JJDisputeControllerTest.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeServiceOrdsOccamTest.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeServiceOrdsTcoTest.java
TCVP-2120
Implemented setStatus with remarks for JJDisputes TCO ORDS endpoint.
- added JJDisputeRemark mapper
- added JJDisputeRemarkRepository to save entities
- updated tco OpenApi spec to include remarks
- added junit tests
- 
mvn verify
Ran a test that commits a status change (with comments) to the actual TCO ORDS instance.
=> TCVP-2120 Implemented setStatus for JJDispute

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/BaseMapper.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/DisputeUpdateRequestMapper.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/JJDisputeMapper.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/JJDisputeRepository.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/ords/JJDisputeRepositoryImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/JJDisputeService.java, src/backend/oracle-data-api/src/main/resources/tco-openapi-spec.yaml, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/BaseTestSuite.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeControllerTest.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/JJDisputeControllerTest.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/JJDisputeMapperTest.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeServiceOrdsOccamTest.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeServiceOrdsTcoTest.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/JJDisputeServiceTest.java
TCVP-2120
- Updated TCO ORDS OpenApi spec to match the Postman Collection
- Implemented JJDisputeRepository.saveAndFlush to update a JJDispute to TCO ORDS.
- Added mapper to convert from Oracle Data API JJDispute model to ORDS
- Added JUnit test to confirm persist works in ORDS
mvn test
=> TCVP-2120 implemented JJDispute update mapping

src/backend/oracle-data-api/src/main/resources/tco-openapi-spec.yaml
Fixed mapping of a Date field due to a changed ORDS date-format serialization change.
Junit serialization test passes again.
=> Updated mapping per changed ORDS serialization

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/JJDisputeRepository.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/h2/JJDisputeRepositoryImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/ords/JJDisputeRepositoryImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/JJDisputeService.java, src/backend/oracle-data-api/src/main/resources/tco-openapi-spec.yaml, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/BaseTestSuite.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeServiceOrdsTcoTest.java
TCVP-2120
- exposed /v1/assignDisputeVtc in OpenAPI spec
- added junit test to confirm actual persistence in ORDs
- renamed `ResponseResult `to `DisputeResponseResult `to make room for the generic new `ResponseResult `
mvn verify
=> TCVP-2120 exposed ORDS TCO /v1/assignDisputeVtc

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/JJDisputeRepository.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/h2/JJDisputeRepositoryImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/ords/JJDisputeRepositoryImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/JJDisputeService.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/util/DateUtil.java, src/backend/oracle-data-api/src/main/resources/tco-openapi-spec.yaml, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeServiceOrdsTcoTest.java
TCVP-2120
- exposed /v1/unassignDisputeVtc in OpenAPI spec
- added junit test to confirm actual persistence in ORDs
- removed findByVtcAssignedTsBefore() as we are now using the endpoint directly to unassign rather than iterating over records.
mvn verify
=> TCVP-2120 exposed ORDS TCO /v1/unassignDisputeVtc

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/JJDisputeRepository.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/h2/JJDisputeRepositoryImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/ords/JJDisputeRepositoryImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/JJDisputeService.java, src/backend/oracle-data-api/src/main/resources/tco-openapi-spec.yaml, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeServiceOrdsTcoTest.java
TCVP-2120
- exposed /v1/assignDisputeJj in OpenAPI spec
- added jjAssignedTo parameter /v1/jjDisputeList to match Postman collection
- added junit test to confirm actual persistence in ORDs
mvn verify
=> TCVP-2120 exposed ORDS TCO /v1/assignDisputeJj

README.md, src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApi.v1_0.json, src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApiClient.g.cs, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/JJDisputeMapper.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/JJDispute.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/JJDisputedCount.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/JJDisputedCountRoP.java, src/backend/oracle-data-api/src/main/resources/application.yml
TCVP-2120 Enable TCO ORDS
Fixed bugs so the staff-portal can display data in TCO ORDS rather than H2.
docker-compose up -d 
=> TCVP-2120 Enable TCO ORDS

src/backend/TrafficCourts/Citizen.Service/Services/Impl/CitizenDocumentService.cs, src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApi.v1_0.json, src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApiClient.g.cs, src/backend/TrafficCourts/Messaging/MessageContracts/SaveFileHistory.cs, src/backend/TrafficCourts/Staff.Service/Mappers/Mapper.cs, src/backend/TrafficCourts/Staff.Service/Services/DisputeService.cs, src/backend/TrafficCourts/Staff.Service/Services/FileHistoryService.cs, src/backend/TrafficCourts/Staff.Service/Services/JJDisputeService.cs, src/backend/TrafficCourts/Staff.Service/Services/StaffDocumentService.cs, src/backend/TrafficCourts/TrafficCourts.Staff.Service.Test/Controllers/FileHistoryControllerTest.cs, src/backend/TrafficCourts/Workflow.Service/Consumers/DisputeUpdateRequestAcceptedConsumer.cs, src/backend/TrafficCourts/Workflow.Service/Consumers/DisputeUpdateRequestRejectedConsumer.cs, src/backend/TrafficCourts/Workflow.Service/Consumers/EmailVerificationReceivedConsumer.cs, src/backend/TrafficCourts/Workflow.Service/Consumers/SendUpdateRequestReceivedEmailConsumer.cs, src/backend/TrafficCourts/Workflow.Service/Services/FileHistoryService.cs, src/backend/TrafficCourts/Workflow.Service/Services/IOracleDataApiService.cs, src/backend/TrafficCourts/Workflow.Service/Services/OracleDataApiService.cs, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/JJDispute.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/JJDisputeMapperTest.java
- [TCVP-2077](https://justice.gov.bc.ca/jira/browse/TCVP-2077)
- Refactored SaveFileHistory message and consumer to fetch dispute and jj dispute based on different type of IDs.
- Utilized updated method to save file history with `FileHistoryAuditLogEntryType` enum for audit log descriptions.
- Updated file history service to call new insert file history method from oracle data api with updated params.
- Updated the type of `occamDisputeId` from string to long in JJDispute model.
Ran the apps and triggered some events that creates new file history records and confirmed those are successfully saved in Oracle database.
If Yes: Has Docker been updated …
=> TCVP-2077 Update .Net apps to use new save file history method

src/backend/TrafficCourts/Citizen.Service/Services/Impl/CitizenDocumentService.cs, src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApi.v1_0.json, src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApiClient.g.cs, src/backend/TrafficCourts/Messaging/MessageContracts/SaveFileHistory.cs, src/backend/TrafficCourts/Staff.Service/Mappers/Mapper.cs, src/backend/TrafficCourts/Staff.Service/Services/DisputeService.cs, src/backend/TrafficCourts/Staff.Service/Services/FileHistoryService.cs, src/backend/TrafficCourts/Staff.Service/Services/JJDisputeService.cs, src/backend/TrafficCourts/Staff.Service/Services/StaffDocumentService.cs, src/backend/TrafficCourts/TrafficCourts.Staff.Service.Test/Controllers/FileHistoryControllerTest.cs, src/backend/TrafficCourts/Workflow.Service/Consumers/DisputeUpdateRequestAcceptedConsumer.cs, src/backend/TrafficCourts/Workflow.Service/Consumers/DisputeUpdateRequestRejectedConsumer.cs, src/backend/TrafficCourts/Workflow.Service/Consumers/EmailVerificationReceivedConsumer.cs, src/backend/TrafficCourts/Workflow.Service/Consumers/SendUpdateRequestReceivedEmailConsumer.cs, src/backend/TrafficCourts/Workflow.Service/Services/FileHistoryService.cs, src/backend/TrafficCourts/Workflow.Service/Services/IOracleDataApiService.cs, src/backend/TrafficCourts/Workflow.Service/Services/OracleDataApiService.cs, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/config/OrdsOccamApiClientConfiguration.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/FileHistoryController.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/AuditLogEntryMapper.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/AuditLogEntryType.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/FileHistory.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/JJDispute.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/FileHistoryRepository.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/ords/FileHistoryRepositoryImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/FileHistoryService.java, src/backend/oracle-data-api/src/main/resources/occm-openapi-spec.yaml, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/FileHistoryControllerTest.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/JJDisputeMapperTest.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/util/RandomUtil.java
- [TCVP-2075](https://justice.gov.bc.ca/jira/browse/TCVP-2075)
- Added mappers and functionality to insert and get audit log entries (file history) through the ORDS endpoints.
- Added new `AuditLogEntryType` enum.
- Added repository for saving and getting list of audit log entries through ORDS endpoints.
- Refactored file history controller to receive only `fileHistory` in the body of the request for inserting file history record.
- Refactored unit tests.
- Updated JJDispute to make occamDisputeId to be not nullable and updated .net code accordingly.
Ran oracle data api locally, inserted and retrieved audit log entries successfully using Swagger UI.
If Yes: …
=> TCVP-2075 Audit log entries (file history) ords support

src/backend/TrafficCourts/Citizen.Service/Validators/Rules/OnlyMVAIsSelectedRule.cs, src/backend/TrafficCourts/Citizen.Service/Validators/ValidationMessages.cs, src/backend/TrafficCourts/Common/Models/OcrViolationTicket.cs, src/backend/TrafficCourts/Test/Citizen.Service/Validators/Rules/CheckboxIsValidRuleTest.cs, src/backend/TrafficCourts/Test/Citizen.Service/Validators/Rules/OnlyMVAIsSelectedRuleTest.cs
TCVP-2196 
Form Recognizer in Azure is returning different json than it did yesterday.
The PR is to update the citizen-api to match.
dotnet test
=> TCVP-2196 updated OCR to match changed Azure service

src/backend/TrafficCourts/Staff.Service/Services/JJDisputeService.cs, src/backend/TrafficCourts/TrafficCourts.Staff.Service.Test/Controllers/JJControllerTest.cs, src/backend/TrafficCourts/TrafficCourts.Staff.Service.Test/Services/JJDisputeServiceTest.cs
TCVP-2124
- Supplied partId from Keycloak when accepting a JJDispute
- Added xUnit tests
dotnet test
=> TCVP-2124 Use PartId from Keycloak

.gitops/charts/traffic-court-online/charts/arc-dispute-api/templates/deployment.yaml, .gitops/charts/traffic-court-online/charts/citizen-api/templates/deployment.yaml, .gitops/charts/traffic-court-online/charts/oracle-data-api/templates/deployment.yaml, .gitops/charts/traffic-court-online/charts/staff-api/templates/deployment.yaml, .gitops/charts/traffic-court-online/charts/workflow-service/templates/deployment.yaml, src/backend/TrafficCourts/entrypoint.sh, src/backend/oracle-data-api/entrypoint.sh
- Fixes TCVP-2208
- Removed unused `sleep` section in entry point scripts
- Add `vault.hashicorp.com/agent-pre-populate-only: 'true'` annotation that should prevent vault sidecar 
- Add injecting secrets for Oracle Data API to support the new ORDS credentials
=> Update Helm Charts / entrypoint.sh for Vault

src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApi.v1_0.json, src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApiClient.g.cs, src/backend/TrafficCourts/Staff.Service/Services/JJDisputeService.cs, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/JJDisputeController.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/JJDisputeService.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/BaseTestSuite.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/JJDisputeControllerTest.java
TCVP-1999
- removed courtAppearanceId from AcceptJJDispute endpoint since it was always null.
- added logic to retrieve the latest courtAppearance if courtAppearanceId not supplied (ie from AcceptJJDispute)
- updated tests
mvn test
dotnet test
=> TCVP-1999 Updated setStatus logic

.gitops/charts/traffic-court-online/charts/arc-dispute-api/templates/deployment.yaml, .gitops/charts/traffic-court-online/charts/citizen-api/templates/deployment.yaml, .gitops/charts/traffic-court-online/charts/oracle-data-api/templates/deployment.yaml, .gitops/charts/traffic-court-online/charts/staff-api/templates/deployment.yaml, .gitops/charts/traffic-court-online/charts/workflow-service/templates/deployment.yaml
- Vault token is required if the application wants to connect to vault. Our application only gets injected secrets and does not call vault. The vault token is not required to be injected.
=> Remove injecting vault token

src/backend/oracle-data-api/pom.xml, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeController.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/EmailHistoryController.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/FileHistoryController.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/JJDisputeController.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/ords/DisputeRepositoryImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/ords/DisputeUpdateRequestRepositoryImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/ords/EmailHistoryRepositoryImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/ords/FileHistoryRepositoryImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/ords/JJDisputeRepositoryImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeService.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/JJDisputeService.java, src/backend/oracle-data-api/src/main/resources/logback-spring.xml
- [TCVP-2304](https://justice.gov.bc.ca/jira/browse/TCVP-2304)
- Added required dependencies and configuration to publish structured logs to Splunk through logback in JSON format.
- Using [Logstash Logback Encoder](https://github.com/logfellow/logstash-logback-encoder) dependency to provide logback layouts to log in JSON.
- Updated all logs in controllers, services and repositories to use structured logging in order to pass structured parameters to Splunk for dashboard view.
Ran splunk and oracle data api locally, sent some request to the endpoints and confirmed the structured logs published to Splunk.
=> TCVP-2304 add structured logs for oracle data api

src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApi.v1_0.json, src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApiClient.g.cs, src/backend/TrafficCourts/Staff.Service/Controllers/DisputeController.cs, src/backend/TrafficCourts/Staff.Service/Services/DisputeService.cs, src/backend/TrafficCourts/Staff.Service/Services/IDisputeService.cs, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeController.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeService.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeControllerTest.java
- Fixed API side of the Staff can't cancel a dispute with invalid entries in fields issue: [TCVP-2229](https://justice.gov.bc.ca/jira/browse/TCVP-2229) 
- Updated dispute set status to cancelled endpoint to accept required 'cancelledReason' parameter to save the note that specifies the cancellation reason with validation.
- Updated JUnit tests.
- Updated OpenAPI Spec from Oracle Data API.
Ran apps locally through docker compose and cancelled an existing dispute with a cancellation reason specified and confirm that it has been saved successfully.
=> TCVP-2229 Add cancelled reason for cancelling a dispute

src/backend/oracle-data-api/src/main/resources/occm-openapi-spec.yaml
- [TCVP-2347](https://justice.gov.bc.ca/jira/browse/TCVP-2347)
- Updated `issuedTs` (issuedDt) field date/time format to save and retrieve the violation ticket date and time same as the provided ticket instead of UTC time.
- TODO: Once this will be deployed to dev environment, we must update the Oracle database packages to match the formatting.
Updated the issuedDt field formatting in the database temporarily and confirmed the issuedTs field retrieved by Oracle Data API was exactly same as the one written on the ticket.
=> TCVP-2347 violation ticket issued time fix

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeController.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeControllerTest.java
- TCVP-2352 inability to retrieve individual dispute update request
=> TCVP-2352 retrieve dispute update requests

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/JJDisputeService.java
- [TCVP-2390](https://justice.gov.bc.ca/jira/browse/TCVP-2390)
- Updated method to find a JJDisputeCourtAppearanceRoP to return the found court appearance if the target update status is 'ACCEPTED' instead of checking the current JJ Dispute status.
=> TCVP-2390 Fix JJ Dispute court appearance update

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/JJDisputeMapper.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/JJDisputeCourtAppearanceRoP.java, src/backend/oracle-data-api/src/main/resources/tco-openapi-spec.yaml, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/JJDisputeMapperTest.java
- [TCVP-2337](https://justice.gov.bc.ca/jira/browse/TCVP-2337)
- Added functionality to map hearing duration data from Justin into "JJDisputeCourtAppearanceRoP" model's 'duration' property in minutes when a JJDispute or list of JJDisputes returned from an ORDS endpoint.
- Added unit test for duration field mapping.
- NOTE: This fix also requires applying database changes in SVN revision: 162086 to the environment where this code will be deployed.
Created an appearance with estimated hearing duration in hours and minutes which is associated to an existing JJDispute in TCO. Confirmed that the duration field is returned in minutes successfully when the …
=> TCVP-2337 Get hearing duration from Justin

src/backend/TrafficCourts/Citizen.Service/Controllers/DisputesController.cs, src/backend/TrafficCourts/Citizen.Service/Features/Disputes/Create.cs
- Fixes issue where `response.Exception` was being passed to the `StatusCode` call.  Passing the exception results in the following error being logged. The `StatusCode` function is trying to serialize the entire exception which cannot be done and results in a NotSupportedException during Json serialization.
=> Remove passing exception to StatusCode result

tools/docker-compose.yml, tools/keycloak-user-initializer/README.md, tools/keycloak-user-initializer/src/main/java/ca/bc/gov/open/jag/tco/keycloakuserinitializer/config/IdirApiClientConfigProperties.java, tools/keycloak-user-initializer/src/main/java/ca/bc/gov/open/jag/tco/keycloakuserinitializer/model/TcoUser.java, tools/keycloak-user-initializer/src/main/java/ca/bc/gov/open/jag/tco/keycloakuserinitializer/service/KeycloakService.java, tools/keycloak-user-initializer/src/main/resources/application.yml
- [TCVP-2421](https://justice.gov.bc.ca/jira/browse/TCVP-2421)
- Added functionality to read partId of the users from the CSV file and add it to the attributes of the user who is initialized in Keycloak.
- Externalized the env variable to specify to call an IDIR API Client environment. Default is set to DEV.
- Updated the docker-compose file to add the new env variable.
=> TCVP-2421 assign part ids from csv file

src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApi.v1_0.json, src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApiClient.g.cs, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/DisputeStatus.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeService.java
- [TCVP-2425](https://justice.gov.bc.ca/jira/browse/TCVP-2425)
- Added 'Concluded' dispute status type to the existing DisputeStatus enum model to be able to set a dispute's status to `CONCLUDED` from Justin side only.
- Regenerated OpenAPI spec of OracleDataApi.v1_0.json
=> TCVP-2425 Add concluded dispute status

src/backend/TrafficCourts/TrafficCourts.Coms.Client/FileSearchResult.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/Models.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/Models.g.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/TimestampUserData.cs
- This is a fix for the issue that prevents submission of a dispute if COMS service is running locally.
- The main cause of the issue was communicated to the COMS developer team through this issue ticket opened on COMS GitHub repo by @pbolduc: https://github.com/bcgov/common-object-management-service/issues/165. Although this issue seem to be resolved on COMS' later version, we still need a workaround for this because we're using version 0.4.0.
- This fix is a workaround for COMS date serialization issue caused by `updatedAt` property which we don't ever need in TCO so this fix allows that property to be nullable.
Please describe the tests that you ran to …
=> Fix COMS updatedAt field issue

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/filters/PreAuthenticatedTokenFilter.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/JJDisputeService.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/BaseTestSuite.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeControllerTest.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/JJDisputeControllerTest.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/JJDisputeServiceTest.java
- The bug mentioned in [TCVP-2400](https://justice.gov.bc.ca/jira/browse/TCVP-2400) ticket can be reproduced if Oracle Data API receives empty partId from the request header so it was defaulting partId to a string value "System". However, it is actually a numeric value in Oracle database and the default "System" partId value (if no actual value is received from the request header) could not be converted into  a number value which results in character to number conversion error in the database.
- Removed assigning a default partId as 'System' and set it to null if no partId is provided.
- Added checks, logs and error handling for not updating the status of a JJ Dispute if the staff part ID is null despite there is a court appearance …
=> Feature/TCVP-2400 set default partId

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/ords/DisputeRepositoryImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/ords/DisputeUpdateRequestRepositoryImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/ords/JJDisputeRepositoryImpl.java, src/backend/oracle-data-api/src/main/resources/occm-openapi-spec.yaml, src/backend/oracle-data-api/src/main/resources/tco-openapi-spec.yaml, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/impl/ords/DisputeServiceImplTest.java
- Add empty body for POST or DELETE requests
=> Add empty body on POST or DELETE calls required by ORDS

.gitops/charts/traffic-court-online/values.yaml, src/backend/oracle-data-api/Dockerfile, src/backend/oracle-data-api/pom.xml, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/EmptyObject.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/ords/DisputeRepositoryImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/ords/DisputeUpdateRequestRepositoryImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/ords/JJDisputeRemarkRepositoryImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/ords/JJDisputeRepositoryImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/ords/TicketImageDataRepositoryImpl.java, src/backend/oracle-data-api/src/main/resources/application.yml, src/backend/oracle-data-api/src/main/resources/occm-openapi-spec.yaml, src/backend/oracle-data-api/src/main/resources/tco-openapi-spec.yaml, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/impl/ords/DisputeServiceImplTest.java
- changes how we send empty object
- changes the operation names instead of using generated name (may have missed 1 or 2)
- changes to use OpenTelemetry agent instead of spring slueth
=> Oracle data api opentelemetry & Empty Object

.gitops/charts/traffic-court-online/charts/citizen-web/templates/route.yaml, .gitops/charts/traffic-court-online/charts/staff-web/templates/route.yaml, infrastructure/openshift/dev/oidc-route.yaml, infrastructure/openshift/dev/ords-proxy.yaml, infrastructure/openshift/prod/citizen-web-for-jag-proxy-route.yaml, infrastructure/openshift/test/oidc-route.yaml
- disables cookies generated by OpenShift route (ingress) which are flagged in the App Scan.
=> Disable cookies on all OpenShift routes

.docker/docker-compose-ocr.yml, src/backend/TrafficCourts/Citizen.Service/Controllers/TicketsController.cs, src/backend/TrafficCourts/Citizen.Service/Features/Tickets/AnalyseHandler.cs, src/backend/TrafficCourts/Citizen.Service/Services/IFormRecognizerService.cs, src/backend/TrafficCourts/Citizen.Service/Services/Impl/FormRecognizerService_2022_06_30_preview.cs, src/backend/TrafficCourts/Citizen.Service/Services/Impl/FormRecognizerService_2_1.cs, src/backend/TrafficCourts/Citizen.Service/Validators/FormRecognizerValidator.cs, src/backend/TrafficCourts/Citizen.Service/Validators/IFormRecognizerValidator.cs, src/backend/TrafficCourts/Citizen.Service/Validators/Rules/LowConfidenceGlobalRule.cs, src/backend/TrafficCourts/Common/Models/OcrViolationTicket.cs, src/backend/TrafficCourts/Test/Citizen.Service/Controllers/TicketsControllerTests.cs
TCVP-2506 - enabled Citizen-API to be able to analyze VT2 ticket images
- updated the default form recognizer modelID to be the new composite model.
- separated the logic of sanitizing analyzed results from validation for easier testability.
- split FieldLabels into their respective versions (2022_04 and 2023_09)
- some field validations are no longer applicable for the new VT2 model.
- improved sanitization of certain fields for better results
Performed a docker-compose up and confirmed both VT1 and VT2 images can be scanned by citizen-portal:
New VT2 sample image:
Results in Citizen Portal:
=> TCVP-2506 Enabled Citizen-API to be able to analyze VT2 ticket images

src/backend/TrafficCourts/Citizen.Service/Validators/ValidationMessages.cs, src/backend/TrafficCourts/Common/Models/OcrViolationTicket.cs, src/backend/TrafficCourts/Test/Citizen.Service/Validators/Rules/CheckboxIsValidRuleTest.cs
The FormRecognizer outputs the strings "selected" and "unselected" for checkboxes.
Updated the parser and validator in Citizen API to properly recognize these hard-coded strings.
Updated tests
Deployed citizen-api to DEV to confirm parsing against FormRecognizer also running in DEV.
=> Fixed parsing of Checkboxes with the new Composite model

tools/ticket-generator/pom.xml, tools/ticket-generator/src/main/java/ca/bc/gov/court/traffic/ticket/controller/TicketGeneratorController.java, tools/ticket-generator/src/main/java/ca/bc/gov/court/traffic/ticket/model/BaseViolationTicket.java, tools/ticket-generator/src/main/java/ca/bc/gov/court/traffic/ticket/service/TicketGeneratorService.java
TCVP-2507
- TicketGenerator now has an endpoint to generate raw JSON that can later be modified or used to generate a VT1 or VT2 image.
- TicketGenerator now has an endpoint accepts an XLSX spreadsheet and provides a zip file of all the generated images from the spreadsheet.
=> TCVP-2507 Improved Ticket Generator to aid in testing Form Recognizer

src/frontend/staff-portal/src/app/services/violation-ticket.service.ts
Fixed NPE in Staff Portal
The Staff Portal would not load VT2 images due to a mismatch of properties, namely the `act_or_regulation_name_code` field is only on VT1 images, not VT2. There is no such property on VT2 images called `act_or_regulation_name_code` and so this field may be undefined.
Note: I noticed that the Staff Portal may try to use this field for determining if the Count sections are valid or not (presumbably to pull the "MVA" text for the act portion of the Act/Sect/Desc fields. Currently the portal thinks the counts are always invalid.
=> Fixed NPE in Staff Portal when loading VT2 images

src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.html, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.ts
TCVP-2461 bug fix.
The No App field should be conditionally disabled (and blank) if the AppCd is A or P, enabled otherwise.
=> TCVP-2461 Enable NoApp conditionally on AppCd value.

src/frontend/citizen-portal/src/app/components/dispute-ticket-summary/count-item-dispute-summary/count-item-dispute-summary.component.html
TCVP-2423
For a multi-count ticket, if one chooses to skip a count, the dispute reason shouldn't appear.
Before this PR, the "Plead guilty and request..." phrase was showing on all 3 counts, even though counts 1 and 3 were skipped in this example. 
=> TCVP-2423 Skipped counts shouldn't show dispute reasons

src/frontend/citizen-portal/src/app/services/dispute.service.ts, src/frontend/citizen-portal/src/app/shared/dialogs/dispute-status-dialog/dispute-status-dialog.component.ts
TCVP-2441 bug fix
When a staff rejects a dispute the status is set to REJECTED. This status was missing from the status/timeline widget on the Citizen Portal.
This is now what one sees on a REJECTED Dispute.
ie. 
http://localhost:8080/dispute/manage?ticketNumber=AK43849384&time=19:34
=> TCVP-2441 Added missing REJECTED status to timeline/status widget

src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApi.v1_0.json, src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApiClient.g.cs, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/JJDisputeMapper.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/JJDisputeCourtAppearanceRoP.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/JJDisputeService.java, src/backend/oracle-data-api/src/main/resources/tco-openapi-spec.yaml, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/JJDisputeMapperTest.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/JJDisputeServiceTest.java
- TCVP-2363
- Updated JJ court appearances model and mapping to return all type of court appearances fetched from both Justin and tco_court_appearances table.
- Updated service to allow updating only the court appearances records from tco_court_appearances table with an ID.
- Removed audit fields from 'JJDisputeCourtAppearanceRoP' model since it's not needed within the app and the returned data from database is composed of two different tables so "ent" and "upd" data would not have been consistent.
- Updated JUnit tests.
- Regenerated OpenAPI spec of Oracle Data API.
If Yes: Has Docker been …
=> TCVP-2545 Map and return all type of Justin court appearance data

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/AuditLogEntryType.java, src/backend/oracle-data-api/src/main/resources/occm-openapi-spec.yaml, src/backend/oracle-data-api/src/main/resources/tco-openapi-spec.yaml
- TCVP-1847
- Updated audit fields (createdTs and modifiedTs) returned date/time format to set it as PST since all audit fields are retuned from ORDS in database's system date/time zone which is in PST.
- When the createdTs and modifiedTs fields returned by the Oracle Data API, they are converted to proper UTC format automatically.
- Added missing audit log entry type enum.
- Note: this update should be coordinated with the Oracle database package updates in order not cause any data fetching issues.
Updated database packages in DEV and tested running oracle data api locally to make sure createdTS and modifiedTS fields from the pulled data returned in …
=> TCVP-1847 Fix DCF File History showing wrong time

docker-compose.yml, src/frontend/staff-portal/package.json
Due to the recent changing of ports in docker-compose, this PR addresses a couple of stragglers. 
- fake smtp-server wasn't actually working locally
- fixed the port to staff-api from staff-portal
Fake email server is now accessible with `docker-compose up`.
`ng api:download` works again from the staff-portal application
=> Fixed ports with docker-compose

src/backend/TrafficCourts/Citizen.Service/Validators/FormRecognizerValidator.cs, src/backend/TrafficCourts/Common/Models/OcrViolationTicket.cs, src/backend/TrafficCourts/Test/Citizen.Service/Validators/Rules/TimeRuleTest.cs
Small bug fix. VT2 images don't have count Act/Reg sections and so these fields are not available and should be exclude from application logic when dealing with VT2 images.
Currently, VT2 images throw an error if they only have 1 or 2 counts. This fixes that.
Also improved the Time santisation and parsing.
=> Bug fix for a single-count VT2 image

src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-digital-case-file/jj-dispute-digital-case-file.component.html, src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-digital-case-file/jj-dispute-digital-case-file.component.scss
TCVP-2492
Pre JIRA requirments, displayed the text "No results" on the DCF tab (only the DCF tab) when there are no records in the search results.
=> Displayed "No results" on DCF tab when no results

src/backend/TrafficCourts/Common/Models/JJDispute.cs, src/backend/TrafficCourts/Staff.Service/Controllers/DisputeLockController.cs, src/backend/TrafficCourts/Staff.Service/Controllers/JJController.cs, src/backend/TrafficCourts/Staff.Service/Models/Lock.cs, src/backend/TrafficCourts/Staff.Service/Services/DisputeLockService.cs, src/backend/TrafficCourts/Staff.Service/Services/IDisputeLockService.cs, src/backend/TrafficCourts/Staff.Service/Startup.cs, src/backend/TrafficCourts/TrafficCourts.Staff.Service.Test/Controllers/DisputeLockControllerTest.cs, src/backend/TrafficCourts/TrafficCourts.Staff.Service.Test/Controllers/JJControllerTest.cs, src/backend/TrafficCourts/TrafficCourts.Staff.Service.Test/Services/DisputeLockServiceTest.cs
- TCVP-2542
- Add a in memory Dictionary based locking functionality in Staff API for the JJ Dispute records to prevent more than one JJs from editing the same DCF at the same time.
- Allows the logged in user to acquire write lock for a JJ dispute on a get request by adding a Lock model that can be added to a dictionary through the new DisputeLockService.
- Added functionality to refresh the expire time of a lock and release a lock. 
- Added DisputeLockController for triggering lock operations. 
- Updated JJController PUT endpoints to apply lock in order to prevent more than one users to call the endpoints at the same to edit a particular JJ Dispute.
- Added XUnit tests for Dispute Lock Service and Dispute Lock Controller as well as …
=> TCVP-2542 Add Locking Functionality for JJ Disputes

src/backend/TrafficCourts/Citizen.Service/Validators/FormRecognizerValidator.cs, src/backend/TrafficCourts/Citizen.Service/Validators/Rules/VersionVT1DisallowedRule.cs, src/backend/TrafficCourts/Citizen.Service/Validators/ValidationMessages.cs, src/backend/TrafficCourts/Common/Models/OcrViolationTicket.cs, src/backend/TrafficCourts/Test/Citizen.Service/Validators/Rules/VersionVT1DisallowedRuleTest.cs
TCVP-2559 Violation Ticket images that were originally used 2022-04 (aka VT1) are no longer supported.
- Added new global validation rule
- Added XUnit tests
In the Citizen API when attempting to analyze a VT1 ticket, the API now returns:
=> TCVP-2559 VT1 are no longer supported by OCR

src/frontend/citizen-portal/src/app/services/violation-ticket.service.ts
TCVP-2559
When a VT1 image is uploaded as a new dispute, VT1 tickets now error out with the below error message (TBD by BA).
=> TCVP-2559 VT1 tickets are no longer supported

src/backend/TrafficCourts/Citizen.Service/Validators/FormRecognizerValidator.cs, src/backend/TrafficCourts/Test/Citizen.Service/Validators/Rules/DateOfServiceLT30RuleTest.cs
Form Recognizer appears to struggle with recognizing 1's or 11's on a VT2 image in a standalone field (ie. the Violation Date field). Maybe it thinks they are vertical lines??
However, when a 1 or 11 is in a string of characters, Form Recognizer does a much better job (ie. the Date of Service).
This means that for the month of November VT2 images will be difficult to read in general since the Violation Date will be almost always null. :(
In TCO, the Violation Date and Date of Service are usually (if not always) the same date. This small tweak will use DoS date if the VD is unrecognizable (ie. null) and vice versa. VT Staff can update the Dispute if the date is not correct.
if your change is a breaking change, please add `breaking change` …
=> OCR tweak to improve Violation Date parsing

src/backend/TrafficCourts/Citizen.Service/Controllers/TicketsController.cs, src/backend/TrafficCourts/Citizen.Service/Features/Tickets/Search.cs, src/backend/TrafficCourts/Citizen.Service/Services/Tickets/Search/TicketSearchService.cs, src/backend/TrafficCourts/Test/Citizen.Service/Features/Tickets/SearchHandlerTest.cs
- TCVP-2560
- Added functionality to prevent RSI look-up from searching and returning older version tickets (VT1) which have violation date before April 9, 2024.
- Returns 400 bad request if the searched ticket is invalid.
=> TCVP-2560 Block VT1 Tickets from RSI Lookup Search

infrastructure/keycloak/realm-export.json, infrastructure/keycloak/staff-api-authz-config.json
TCVP-1981 Created new update-admin permisison in Keycloak DEV and exported Authorization details.
1. Created Role **support-staff**
_Clients > staff-api > Roles_
2. Created Policy **has role support-staff**
_Clients > staff-api > Authorization > Policies_
3. Created Scope **update-admin**
_Clients > staff-api > Authorization > Scopes_
4. Updated Resource details to include update-admin scope
_Clients > staff-api > Authorization > Resources > jj-dispute_
5. Created Permission **can update-admin jj-dispute**
_Clients > staff-api > Authorization > Permissions_
If Yes: Has Docker been updated …
=> TCVP-1981 Added update-admin to jj-dispute resource in Keycloak.

src/backend/TrafficCourts/Messaging/MessageContracts/DisputantEmailVerification.cs, src/backend/TrafficCourts/Workflow.Service/Sagas/VerifyEmailAddressSagaStateMachine.cs
- Removes the second initial state for verify email which causes state conflicts and duplicate emails
=> TCVP-2380 remove extra saga initial state causing duplicate emails

src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApi.v1_0.json, src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApiClient.g.cs, src/backend/TrafficCourts/Messaging/MessageContracts/SaveFileHistory.cs, src/backend/TrafficCourts/Staff.Service/Authentication/Scopes.cs, src/backend/TrafficCourts/Staff.Service/Controllers/JJController.cs, src/backend/TrafficCourts/Staff.Service/Services/IJJDisputeService.cs, src/backend/TrafficCourts/Staff.Service/Services/JJDisputeService.cs
TCVP-24525
- Regenerated oracle-data-api OpenAPI spec
- Added new staff-api endpoint (that delegates to the oracle-data-api endpoint) that cascade updates a JJDispute
- New endpoint is guarded by the new update-admin permission against the JJDispute resource (user must be a member of the staff-support role)
- Added logic to add a File History record whenever a support staff cascade updates a JJDispute that shows up in the File History section on the DCF details screen.
=> TCVP-2525 Added endpoint to cascade update JJDispute

src/backend/TrafficCourts/Citizen.Service/Services/Tickets/Search/TicketSearchService.cs, src/backend/TrafficCourts/Test/Citizen.Service/Features/Tickets/SearchHandlerTest.cs
- TCVP-2560
- Fixed the search blocking logic for VT1 RSI looked-up tickets to block only ISC tickets that always start with the letter 'S'.
=> TCVP-2560 Block VT1 ISC Tickets

src/frontend/citizen-portal/src/app/components/find-ticket/find-ticket.component.scss, src/frontend/citizen-portal/src/app/shared/dialogs/image-ticket-not-found-dialog/image-ticket-not-found-dialog.component.html
TCVP-2559 Small text change per change of requirements.
Width of error popup dynamically adjusts to user's device.
Updated dialog width so the text fits better.
=> TCVP-2559 Text change per change of requirements

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/JJDisputeService.java, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.html, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.scss, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.ts, src/frontend/staff-portal/src/app/services/jj-dispute.service.ts, src/frontend/staff-portal/src/assets/i18n/en.json, src/frontend/staff-portal/src/assets/i18n/fr.json
- Added an Edit button to the Staff Workbench DCF tab. This button is visable only to users in the **support-staff** security group.
- Added abilty for a **support-staff** to edit the Surname and the 3 Given names of the Ticket Information details.
- Added field validation for Surname (following the oracle-data-api model specs, the three fields must not be over 30 characters long)
- Form and buttons follow the [BCGov standard theme](https://bcgov.github.io/bootstrap-theme/docs/reference/simple/#forms)
- Saving the form calls the new JJDispute endpoint that will cascade update the JJDispute (saving OCCAM Dispute data in this case). This endpoint is protected by the same **support-staff** guard.
if your change is a breaking change, please …
=> TCVP-2523 Added Edit button to DCF screen

src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApi.v1_0.json, src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApiClient.g.cs, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/JJDisputeMapper.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/JJDispute.java, src/backend/oracle-data-api/src/main/resources/tco-openapi-spec.yaml, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/JJDisputeMapperTest.java
- TCVP-2600
- Updated the tco openapi spec and JJDispute model to include accident and multiple officers flags as part of JJDispute object.
- Added mapper and updated junit tests for the 'accidentYn' and 'multipleOfficersYn' fields.
- Regenerated OpenAPI spec of OracleDataApi.v1_0.json and model.
- Note: this update should be coordinated with the Oracle database package updates in order not to cause any data fetching issues.
=> TCVP-2600 Retrieve Accident and Multiple Officers Flags

src/backend/TrafficCourts/Citizen.Service/appsettings.Development.json, src/backend/TrafficCourts/Citizen.Service/appsettings.json, src/backend/TrafficCourts/Staff.Service/appsettings.Development.json, src/backend/TrafficCourts/Staff.Service/appsettings.json, src/backend/TrafficCourts/Workflow.Service/appsettings.Development.json, src/backend/TrafficCourts/Workflow.Service/appsettings.json
The reduce the amount of unnecessary logs being written to splunk the log levels for EF and Polly changed to Warning.
- set the log level of EF and Polly to `Warning` in appsettings.json
- set the log level of EF and Polly to `Information` in appsettings.Development.json
Examples logs that will be filtered out,
Polly
```
Execution attempt. Source: '"CDOGS-standard"/""/"Standard-Retry"', Operation Key: 'null', Result: '200', Handled: 'False', Attempt: '0', Execution Time: '85.2706'
```
EF Core
```
Executed DbCommand ("25"ms) [Parameters=["@p0='?' (DbType = Guid), @p1='?', @p2='?' (DbType = Int64), @p3='?', @p4='?' (DbType = Boolean), @p5='?', @p6='?' (DbType = Guid), @p7='?' (DbType = Boolean), @p8='?' (DbType = DateTime)"], …
```
=> Change default log level for EF and Polly to Warning

src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.html, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.scss, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.ts, src/frontend/staff-portal/src/app/config/config.service.ts, src/frontend/staff-portal/src/app/services/lookups.service.ts
TCVP-2524
Several of the form fields on the Contact Information section of the DCF tab now display as editable.
- When the Contact Information section is editable, the Ticket Information section is not.
- Added a new LookupService.getProvinces() to deal with the Province select list.
Note: The ORDs backend does not actually persist the values in the database yet on the PUT JJDispute endpoint (coming...)
=> TCVP-2524 Made Contact Information fields editable

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/JJDisputeService.java, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.html, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.ts, src/frontend/staff-portal/src/assets/i18n/en.json, src/frontend/staff-portal/src/assets/i18n/fr.json
TCVP-2524
Made Court Options editble to admin staff with the "support-staff" permission.
Note: the Attendance Type does not yet persist due to a bug with the ORDS API endpoint.
=> TCVP-2524 Made Court Options editable

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/JJDisputeService.java, src/frontend/staff-portal/package.json, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.html, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.scss, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.ts, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.html, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.scss, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.ts, src/frontend/staff-portal/src/app/shared/modules/ngx-material/ngx-material.module.ts, src/frontend/staff-portal/src/assets/i18n/en.json, src/frontend/staff-portal/src/assets/i18n/fr.json, src/frontend/staff-portal/yarn.lock
TCVP-2524
This PR contains changes for the entire DCF tab. All requested fields should now be editable.
- added new `mat-datetimepicker` for the **noAppTs** field
- used i18n for touched fields
- moved Edit/Save/Cancel buttons to the header next to the Goto/Print/Print Options buttons.
=> TCVP-2524 Made DCF tab editable

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/JJDisputeController.java
Some of the debug logging statements in the JJDisputeController didn't match the endpoint being hit. This is to avoid confusion when viewing the logs and not knowing if the JJDisputeController or DisputeController endpoint was hit.
Note that the annotation on the JJController has a request mapping of /api/v1.0/jj, so all endpoints should start with jj in the logs. 
=> Fixed debug logging messages to match endpoints

src/backend/TrafficCourts/Citizen.Service/Controllers/TicketsController.cs, src/backend/TrafficCourts/Citizen.Service/Services/Tickets/Search/ITicketSearchService.cs, src/backend/TrafficCourts/Citizen.Service/Services/Tickets/Search/TicketSearchService.cs, src/backend/TrafficCourts/Test/Citizen.Service/Controllers/TicketsControllerTests.cs
- TCVP-2548
- Added functionality to check if a dispute has been submitted before for the looked-up or OCR violation ticket and blocks it from submitting multiple times by searching for the ticket number in OCCAM database.
- Returns 400 Bad Request if the dispute is submitted before when disputant searches for a violation ticket or uploads an image of the ticket.
- Added XUnit tests to verify dispute search responses.
Tested searching previously submitted tickets locally and ran XUnit tests.
=> TCVP-2548 Block Submitting Multiple Disputes for a Violation Ticket

src/frontend/staff-portal/src/app/components/staff-workbench/ticket-info/ticket-info.component.html, src/frontend/staff-portal/src/app/components/staff-workbench/ticket-info/ticket-info.component.scss, src/frontend/staff-portal/src/app/components/staff-workbench/ticket-info/ticket-info.component.ts
TCVP-2554
It used to be the case when viewing a previously validated dispute, the Ticket Information section was showing some fields as invalid. Since the fields were read-only there is no way to fix them.
- foreach field, hid error messages when form in read-only
- fixed statute lookup so that it matches the entire full section text instead of just the section code.
=> TCVP-2554 Fixed invalid statue validation error

src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.ts
TCVP-2540 Updated warning wording when all counts have been skipped.
=> TCVP-2540 Update warning wording when all skipped

src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.html, src/frontend/citizen-portal/src/app/shared/components/alert/alert.component.scss
TCVP-2586
- simple wording change
- css fix for warning icon was cut off (only half visible)
=> TCVP-2586 simple wording change on citizen-portal

src/frontend/citizen-portal/src/app/services/violation-ticket.service.ts, src/frontend/citizen-portal/src/app/shared/dialogs/image-ticket-not-found-dialog/image-ticket-not-found-dialog.component.html
TCVP-2629
Added new UI error popup if the user attempts to Dispute a dispute that is already in the system (tickets that start with E, S, or A).
=> TCVP-2629 Added new error message for duplicate disputes

src/frontend/citizen-portal/src/app/services/violation-ticket.service.ts
TCVP-2629
Fixed javascript bug where the error object was causing an issue. The problem is that the error object from the citizen-api is different for different types of errors. Sometimes it is just a string as an error message, sometimes an object with a collection of error messages, etc.
This particular fix is to make sure the err.error.includes() function exists before trying to call it (this function doesn't exist all the time, depends on the error object returned by the api).
=> TCVP-2629 UI javascript error

src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.ts, src/frontend/staff-portal/src/app/components/jj-workbench/jj-workbench-dashboard/jj-workbench-dashboard.component.html, src/frontend/staff-portal/src/app/components/staff-workbench/staff-workbench-dashboard/staff-workbench-dashboard.component.html
TCVP-2523
Per requirements, the new DCF editing feature for support-staff should only be available to the staff workbench, not the jj workbench, but the same component is used on both screens.
=> TCVP-2523 DCF editing should only be allowed on staff workbench

src/backend/oracle-data-api/src/main/resources/application.yml
Defaulted the Swagger UI to be the root URL.
i.e.
`http://localhost:5010/`
redirects to 
`http://localhost:5010/swagger-ui/index.html`
=> Oracle Data API added root url for easy redirect to swagger UI

src/backend/TrafficCourts/Citizen.Service/Services/Tickets/Search/Extensions.cs, src/backend/TrafficCourts/Citizen.Service/Services/Tickets/Search/Rsi/Authentication/RsiTokenRefreshService.cs, src/backend/TrafficCourts/Common/Authentication/KeycloakExtension.cs, src/backend/TrafficCourts/Common/Authentication/KeycloakTokenRefreshService.cs, src/backend/TrafficCourts/Test/Citizen.Service/Validators/Rules/DriversLicenceValidRuleTest.cs, src/backend/TrafficCourts/Test/Citizen.Service/Validators/Rules/TimeRuleTest.cs, src/backend/TrafficCourts/Test/Workflow.Service/Consumers/DisputeUpdateRequestConsumerTest.cs, src/backend/TrafficCourts/TrafficCourts.Cdogs.Client/Extensions.cs, src/backend/TrafficCourts/TrafficCourts.Core/Http/TokenRefreshService.cs
I am still confused why we are getting 401 unauthorized requests going to the keycloak api. In the logs I can see a cached token being found.  I am seeing a log of errors in the keycloak server logs such as 
```
2023-12-12 18:04:01,323 WARN [org.keycloak.events] (executor-thread-1816) type=REFRESH_TOKEN_ERROR, realmId=traffic-court, clientId=staff-portal, userId=null, ipAddress=<redacted>, error=invalid_token, grant_type=refresh_token, client_auth_method=client-secret
```
- Be sure to use ITokenCache for both setting and getting cached tokens
- Fixes xunit warnings
If Yes: Has Docker been …
=> TCVP-2642 Use Token Cache consistently

src/frontend/citizen-portal/src/app/components/dispute-stepper/dispute-stepper.component.html
TCVP-2594
Bug fix to disallow decimal values on number of witnesses.
=> TCVP-2594 disallow decimals numbers

src/backend/TrafficCourts/Citizen.Service/Program.cs, src/backend/TrafficCourts/Citizen.Service/Services/Tickets/Search/Extensions.cs, src/backend/TrafficCourts/Citizen.Service/Services/Tickets/Search/Mock/MockInvoiceCache.cs, src/backend/TrafficCourts/Citizen.Service/Services/Tickets/Search/Mock/MockTicketSearchService.cs, src/backend/TrafficCourts/Common/ClockExtensions.cs, src/backend/TrafficCourts/Test/Ticket.Search.Service/Features/Search/Mock/EmbeddedMockDataProviderTests.cs, src/backend/TrafficCourts/Test/TrafficCourts.Test.csproj
- add in memory cache of ticket invoices
- add endpoint if search type is mock to add invoice
=> Add in memory cache of mock ticket and endpoint to add invoice

docker-compose.yml, tools/port-forward-jaeger.bat
Up until now, .NET applications only showed Info level logging in docker, which is not useful during development. 
This allows one to set an override to Debug in the three .NET projects: **citizen-api**, **staff-api**, **workflow-service**
Verified that setting this env var, logging now works in the mentioned projects.
`SERILOG__MINIMUMLEVEL__DEFAULT=Debug`
=> DevOps - enable debug-level logging for .NET APIs

src/frontend/citizen-portal/src/app/components/ticket-landing/ticket-landing.component.html, src/frontend/citizen-portal/yarn.lock
- TCVP-2568
- Text under 'Check the format of your ticket' is adjusted to fit under the 'Traffic Ticket' button.
=> TCVP-2568 Update Check Format of Ticket Page Styling

gitops/charts/postgres/postgres-dev-values.yaml, gitops/charts/postgres/postgres-test-application-values.yaml
- fixes warning in dev where pvc size doesn't match the definition
- increases the backup volume in test since the storage was at 80% of volume size
=> Bump PVC size to match manually changed size in dev, increase app db backup size to 2GB

tools/ticket-generator/src/main/java/ca/bc/gov/court/traffic/ticket/controller/TicketGeneratorController.java
It can happen that if someone trys to upload a CSV file of specific Tickets Numbers to generate and the numbers happen to have duplicates, there will be a 500 error since the app is expecting the numbers to be unique.
Made the generator a little more robust by adding a (2), (3), etc. to the filename if the generated image name (based on the ticket number) is already used.
=> Made TicketGenerator more robust with filenames

docker-compose.yml, src/backend/oracle-data-api/Dockerfile, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/scheduled/StartupTasks.java
The healthcheck for oracle-data-api wasn't working. 
- Moved heathcheck to the Docker image instead of docker-compose
- Moved startup tasks to a background thread to speed up startup 
=> Improved startup of oracle-data-api

src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.scss, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.html, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.scss
TCVP-2649
Made all the select lists (drop-downs) look the same on the DCF tab on the staff-portal.
Bug fix: fixed the file upload select list ... it was really messed up.
I found out that ::ng-deep styling is actually global, not component specific. Added FIXME comments so that some day when the huge tech dept on this project is addressed, someone will move such styles to the main globally styling sheet.
=> TCVP-2649 updated CSS styles on DCF staff-portal

docker-compose.yml
Fixed docker-compose to lock down the version of the pulled fake smtp image from just using latest to a specific version). docker-compose should never pull latest as functionality could change in images over time. The version should be upgraded only during an intentional manual upgrade process.
=> Updated the fake smtp server version

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/JJDisputeService.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/JJDisputeServiceTest.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/util/RandomUtil.java, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.html, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.ts, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.ts, src/frontend/staff-portal/src/assets/i18n/en.json, src/frontend/staff-portal/src/assets/i18n/fr.json
TCVP-1981
Made JJDisputeCount.latestPlea an editable field for support-staff.
When updating this value, the corresponding latestPleaUpdatedTs is updated accordingly.
=> TCVP-1981 Made latestPlea editable

src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-count/jj-count.component.html
- TCVP-2480
- Removed 'Paid' and 'Cancelled' options from the findings dropdown list for JJ users.
=> TCVP-2480 Remove Last Two Items From Findings Dropdown

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/Dispute.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/DisputeListItem.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/DisputeResult.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/ords/DisputeRepositoryImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeService.java
TCVP-2686
On the Citizen Portal, the Change Dispute button was disabled if the citizen hasn't yet verified their email address. However, the button should not be disabled if the user opted out of email altogether.
This fix is an easy change on the oracle-data-api to pass TRUE _if there is no email address or_ if the email address has been successfully verified, FALSE otherwise.
=> TCVP-2686 Fixed DisputeResult on CitizenPortal screen

src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApi.v1_0.json, src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApiClient.g.cs, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/DisputeMapper.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/JJDisputeMapper.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/ViolationTicketMapper.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/Dispute.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/JJDispute.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/SignatoryType.java, src/backend/oracle-data-api/src/main/resources/occm-openapi-spec.yaml, src/backend/oracle-data-api/src/main/resources/tco-openapi-spec.yaml, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/util/RandomUtil.java
- TCVP-2692 and TCVP-2693
Based on the database changes and recent ORDS updates:
- Added signatory type enum and signatory name fields to the Dispute model in order to be saved as part of Dispute submission and retrieved as part of Dispute data.
- Updated occm-openapi-spec.yaml and mappers for ORDS endpoint requests.
- Added signatory type and name fields to JJDispute model and updated mappers and tco-openapi-spec in order to retrieve signatory fields as part of DCF data.
- Regenerated Oracle Data API OpenAPI Spec for .net APIs.
=> TCVP-2692 Update Models and Mapping to Save and Get Signatory Data

src/backend/TrafficCourts/Workflow.Service/Consumers/SendEmailToDisputantConsumer.cs
- Avoid calling Oracle Data API before sending email
- Handle errors better
- Adjust logging
=> Avoid failing to send email if there is an error with Oracle Data API

src/frontend/staff-portal/src/app/components/jj-workbench/jj-workbench-dashboard/jj-workbench-dashboard.component.html, src/frontend/staff-portal/src/app/components/jj-workbench/jj-workbench-dashboard/jj-workbench-dashboard.component.ts, src/frontend/staff-portal/src/app/services/auth.service.ts, src/frontend/staff-portal/src/app/shared/enums/user-group.enum.ts
TCVP-2639
Fixed the jj workbench permissions by only showing each individual tab if the user has permissions to view that tab - based on the permissions specified on the project wiki.
i.e. To view the Assignments tab, a user must have either: **admin-judicial-justice** or **support-staff** roles.
At the moment, if the user doesn't have permissions to any of the tabs, the screen is just blank. Colm is working to create a UI mockup in such a scenario to indicate something to the user they don't have permissions to see the screen.
Logged in with a user with only **vtc-staff** and confirmed they cannot see any of the tabs.
Logged in with a user with …
=> TCVP-2639 Fixed permissions on jj workbench

src/backend/TrafficCourts/Citizen.Service/Services/Impl/FormRecognizerService_2_1.cs
In an OCR scan, selectionMarks are special fields whose valueSelectionMark attribute must be either "selected" or "unselected". However, in very rare scenarios, the confidence value can be so low that there is no valueSelectionMark attribute, which causes an NPE.
=> Made OCR a little more robust

src/frontend/staff-portal/src/app/services/violation-ticket.service.ts
TCVP-2699
On the staff portal, if there are < 3 counts, MVR would show up as the statute lookup and invalidate the form.  This bug fix addresses this.
=> TCVP-2699 Bug fix for statute lookup on staff portal

src/backend/TrafficCourts/Citizen.Service/Features/Disputes/Create.cs, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.html, src/frontend/staff-portal/src/app/components/staff-workbench/dispute-decision-inbox/dispute-decision-inbox.component.html
- [TCVP-2700](https://justice.gov.bc.ca/jira/browse/TCVP-2700)
- Fixed a bug that was preventing date/time value of SubmittedTs to be set in UTC format.
- Fixed `No APP` date to show the timestamp in user's browser's time instead of UTC.
- Fixed the issue that was causing `ICBC Received Date` to be displayed one day off.
- Fixed `Decision Date` field on `Decision Validation` tab to show the date in user's browser time instead of UTC.
=> TCVP-2700 Fix Incorrect Timestamp Fields

src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.html, src/frontend/staff-portal/src/app/components/jj-dispute-info/jj-dispute/jj-dispute.component.scss, src/frontend/staff-portal/src/assets/i18n/en.json, src/frontend/staff-portal/src/assets/i18n/fr.json
- [TCVP-2473](https://justice.gov.bc.ca/jira/browse/TCVP-2473)
- Fixed spelling and styling of 'multiple officers' and 'accident' flags that are displayed on DCF.
=> Fix Multiple Officers and Accident Flags Styling

src/backend/TrafficCourts/Workflow.Service/Sagas/TagProvider.cs, src/backend/TrafficCourts/Workflow.Service/Sagas/VerifyEmailAddressCleanupHostedService.cs, src/backend/TrafficCourts/Workflow.Service/Sagas/VerifyEmailAddressSagaStateMachine.cs
- Removes an event from the Saga
- delays the processing of verified emails by 5 minutes to allow oracle data api to start
=> Delay processing of email verifications

src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApi.v1_0.json, src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApiClient.g.cs, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/controller/v1_0/DisputeController.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/model/DisputeResult.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/repository/impl/ords/DisputeRepositoryImpl.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeService.java, src/frontend/citizen-portal/src/app/components/disputant-form/disputant-form.component.ts, src/frontend/citizen-portal/src/app/components/update-dispute-contact/update-dispute-contact.component.html, src/frontend/citizen-portal/src/app/components/update-dispute-contact/update-dispute-contact.component.ts, src/frontend/citizen-portal/src/app/components/update-dispute-landing/update-dispute-landing.component.html, src/frontend/citizen-portal/src/app/components/update-dispute-landing/update-dispute-landing.component.ts, src/frontend/citizen-portal/src/app/services/dispute.service.ts
TCVP-2702
Change of requirements - On the Update Dispute Request screen, the opting out should be based on whether the user had previously opted out of email or not.
- modified DisputeResult.isEmailAddressVerified to be a tri-state variable (null for opted out, true for verified, false for not verfied)
- updated openapi client in .NET
- passed isEmailAddressVerified through to Update Dispute screen and defaulted the opted out based on that.
=> TCVP-2702 passed isEmailVerified through to Update Dispute form

src/frontend/citizen-portal/src/app/components/update-dispute-landing/update-dispute-landing.component.ts
TCVP-2712 This PR is a change request to hide the Change Contact and Change Dispute widgets on the citizen portal update requests screen if the Dispute is a hearing dispute and has a status of Accepted or Concluded.
=> TCVP-2712 hide update dispute options for specific court dispute types

src/frontend/citizen-portal/src/app/components/disputant-form/disputant-form.component.ts
TCVP-2702 Bug fix.
The disputant-form.component.ts file is a common component. When used on the initial stepper, don't default the email optOut to true.
=> TCVP-2702 only default to email optOut if preferEmail is specified.

src/backend/TrafficCourts/Citizen.Service/appsettings.json, src/backend/TrafficCourts/Staff.Service/appsettings.json, src/backend/TrafficCourts/Workflow.Service/appsettings.json
- Adjusts the default logging levels to avoid noise in the logs
- Prevents the warning ` No XML encryptor configured. Key {KeyId:B} may be persisted to storage in unencrypted form.` from `Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager`. We are not CSRF or token generation in our applications. See [[No XML encryptor configured warning](https://github.com/dotnet/aspnetcore/issues/3309#top)](https://github.com/dotnet/aspnetcore/issues/3309#issuecomment-404246838)
=> Adjust default logging levels

src/frontend/staff-portal/src/app/components/jj-workbench/jj-dispute-hearing-inbox/jj-dispute-hearing-inbox.component.html
- [TCVP-2720](https://justice.gov.bc.ca/jira/browse/TCVP-2720)
- Fixed the inconsistent time between list and detail view of hearing disputes for appearance date/time by not adjusting the date/time displayed on list view to browser's time since it should be displayed as it is from the response.
=> TCVP-2720 Fix Inconsistent Appearance Time

src/backend/TrafficCourts/Citizen.Service/Validators/FormRecognizerValidator.cs, src/backend/TrafficCourts/Common/Models/OcrViolationTicket.cs, src/backend/TrafficCourts/Test/Citizen.Service/Validators/FormRecognizerValidatorTest.cs, src/backend/TrafficCourts/Test/Citizen.Service/Validators/Rules/CountActRegMustBeMVATest.cs, src/backend/TrafficCourts/Test/Citizen.Service/Validators/Rules/DateOfServiceLT30RuleTest.cs
TCVP-2706
It appears that Form Recognizer (v2.1) does a poor job at recognizing checkboxes.
Instead of the detected values, use the counts to lookup statutes and if they are valid, replace MVA/MVAR Did Commit checkbox selections with identified Statute act codes.
Added new XUnit tests
=> TCVP-2706 Force MVA/R selection to Count Statute Act lookup

src/frontend/citizen-portal/src/app/components/disputant-form/disputant-form.component.ts
TCVP-2702 Fixed logic for preferred email.
Initially the email opt out should default to false (preferEmail is undefined)
Then, on the Update Dispute screen, depending on whether an email was initial provided, the preferEmail will be true or false as the opt out default.
=> TCVP-2702 Fixed logic for preferred email

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeService.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeServiceTest.java
- [TCVP-2748](https://justice.gov.bc.ca/jira/browse/TCVP-2748)
- Added functionality to replace null province values with NA if specific province IDs are null since db check constraints expect string values if IDs are null for provinces.
- Added JUnit tests for replace NA helper methods.
Ran the apps locally and tried updating a ticket with empty province values and confirmed that the values are saved successfully.
=> TCVP-2748 Replace empty province values with N/A

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/mapper/LookupMapper.java, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/impl/ords/LookupServiceImpl.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/LookupServiceTest.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/impl/csv/LookupServiceImpl.java
- [TCVP-2694](https://justice.gov.bc.ca/jira/browse/TCVP-2694)
- Added functionality to filter out the language 'Unknown' with code 'UNK' from the languages list from both ORDS and CSV file before saving into Redis.
=> TCVP-2694 Hide 'Unknown' from languages lookup

src/backend/TrafficCourts/Common/Models/Dispute.cs, src/backend/TrafficCourts/Staff.Service/Controllers/DisputeController.cs, src/backend/TrafficCourts/Staff.Service/Controllers/DocumentController.cs, src/backend/TrafficCourts/Staff.Service/Services/DisputeService.cs, src/backend/TrafficCourts/TrafficCourts.Staff.Service.Test/Controllers/DisputeControllerTest.cs
- [TCVP-2782](https://justice.gov.bc.ca/jira/browse/TCVP-2782)
- These changes are required for front-end to provide document upload and view uploaded documents feature for OCCAM disputes. (TCVP-2598)
- Added functionality to return uploaded document data as part of get dispute request for occam disputes.
- Made the `disputeId` parameter optional for POST document request to allow uploading documents only associated to `noticeOfDisputeId`.
- Added error response handling for COMS on GET dispute request and XUnit test for that.
=> TCVP-2782 Return file data for OCCAM disputes and update file upload request

src/backend/TrafficCourts/Citizen.Service/Services/Impl/FormRecognizerService_2022_08_31.cs, src/backend/TrafficCourts/Citizen.Service/Services/Impl/FormRecognizerService_2_1.cs, src/backend/TrafficCourts/Common/Models/OcrViolationTicket.cs
TCVP-2739 Small tweak to make the citizen-api a little more robust to better handle future Form Recognizer versions. This change will allow us to not have to make an application change every time we rollout a new model. 
Used StartsWith() instead of exact string comparison to find the version of the ViolationTicket (VT1 or VT2)
=> Updated API to be more robust with FR versions

src/backend/TrafficCourts/Messaging/MessageContracts/DisputeApproved.cs, src/backend/TrafficCourts/Staff.Service/Mappers/Mapper.cs, src/backend/TrafficCourts/TrafficCourts.Staff.Service.Test/Mappers/MapperTest.cs
- Hard codes the organization to POL when sending to ARC. See TCVP-2793 for justification.
- Removes obsolete field in a message contract. It has been obsolete for a long time.
There may be another change coming related to the organization location, but I have not been able to confirm it is an issue.
=> Hard code ARC organization to POL

gitops/charts/rabbitmq-values.yaml
- In openshift, we need to hard code the service account as it needs to be created ahead of time with the correct permissions. Not everyone with access to our namespaces can create role bindings required by this service account
=> Add service account name

src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeService.java, src/backend/oracle-data-api/src/test/java/ca/bc/gov/open/jag/tco/oracledataapi/service/DisputeServiceTest.java
- [TCVP-2748](https://justice.gov.bc.ca/jira/browse/TCVP-2748)
- Fixed the logic that prevented dispute update from being saved with null driver's licence province/country combo.
=> TCVP-2748 Fix invalid drivers licence prov country combo

src/backend/TrafficCourts/Common/Models/OcrViolationTicket.cs, src/frontend/citizen-portal/src/app/services/violation-ticket.service.ts, src/frontend/staff-portal/src/app/services/violation-ticket.service.ts
TCVP-2739 Form Recognizer 3.0 apparently changed the value of checkboxes from "selected"/"unselected" to ":selected:"/":unselected:"
Both the citizen and staff portals work again when parsing the ocr results.
=> TCVP-2739 Bug fix for new FR 3.0

src/backend/oracle-data-api/pom.xml, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/config/RetryAspect.java, src/backend/oracle-data-api/src/main/resources/application.yml
This PR adds a global retry attempt mechanism to oracle-data-api using AOP (aspect-oriented programming).
Uses `ORDS_API_RETRY_COUNT` and `ORDS_API_RETRY_DELAY_SEC`, defaults to 3 attempts, 5 seconds apart.
Currently, the AOP Pointcut matches any public method on any class in the ords impl repository package (DisputeRepositoryImpl, JJDisputeRepositoryImpl, etc.) as well as the ords LookupValuesApi (when retrieving cached lookup values for Redis).
```
16:10:23.215 [http-nio-5010-exec-2] DEBUG ca.bc.gov.open.jag.tco.oracledataapi.config.RetryAspect: Attempt 1 failed, retrying: DisputeRepositoryImpl.findByStatusNot(..)
16:10:28.216 [http-nio-5010-exec-2] DEBUG ca.bc.gov.open.jag.tco.oracledataapi.config.RetryAspect: Attempt 2 failed, …
```
=> Added retry to ORDS API calls in oracle-data-api

src/backend/TrafficCourts/Citizen.Service/Services/Impl/CitizenDocumentService.cs, src/backend/TrafficCourts/Staff.Service/Services/JJDisputeService.cs, src/backend/TrafficCourts/Staff.Service/Services/StaffDocumentService.cs
TCVP-2792 
JJs should not be able to see uploaded citizen document if staff haven't reviewed and approved them first.
- set the initial status of uploaded citizen document to PENDING
- added filter to StaffDocumentService to filter documents to only staff-uploaded or citizen documents that have been approved.
Note: there is a bug in COMS where if a staff that approves a citizen document, COMS is not updated.
=> TCVP-2792 Exclude unapproved citizen documents on jj workbench

src/backend/TrafficCourts/Messaging/MessageContracts/DisputeUpdateRequest.cs, src/backend/TrafficCourts/Workflow.Service/Consumers/DisputeUpdateRequestAcceptedConsumer.cs
- TCVP-2817
- Updated disputeUpdateRequest message and dispute accepted consumer to save changes to the signatory fields made by disputant. 
- Note: These changes requires ORDS packages to be updated as well so the release to DEV and TEST should be coordinated with ORDS updates and deployments as well.
=> TCVP-2817 Save signatory fields on update request

.gitattributes, src/backend/TrafficCourts/Messaging/BusConfiguratorExtensions.cs, src/backend/TrafficCourts/Messaging/Configuration/RabbitMqHostOptions.cs, src/backend/TrafficCourts/Messaging/Configuration/RetryOptions.cs
- adds a `UseQuorumQueues` configuration property that defaults to false.
- if `UseQuorumQueues` is true, MassTransit is configured to set the queues to be quorum queues required for clustered configuration.
- Queues must be declared as quorum queues when created
I cleared my rabbitmq storage in docker, restarted the workflow service and rabbitmq and observed the queues being created as quorum queues.
=> TCVP-2834 add configuration item to enable quorum queues

src/backend/TrafficCourts/Citizen.Service/Validators/FormRecognizerValidator.cs, src/backend/TrafficCourts/Test/Citizen.Service/Validators/FormRecognizerValidatorTest.cs
OCR needs a lot of help post processing. It can happen that the two adjacent fields DL Province and DL Licence are merged together into one of the fields. This post-processing task helps to split the fields apart before validation rules are applied.
=> TCVP-2831 Improved OCR post-processing

src/backend/TrafficCourts/Test/Arc.Dispute.Service/Models/DriversLicenceTest.cs, src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/Models/DriversLicence.cs
- [TCVP-2829](https://justice.gov.bc.ca/jira/browse/TCVP-2829)
- Fixed a bug that causes ':' character added at end of DL/Client Number in ARC File by calculating the check digit by taking the last digit of the modulus.
- The bug was caused by the modulo operation sum % 11 can return a value = 10. When the value is 10, adding '0' (which has the ASCII value 48) results in 58, which corresponds to the ASCII character `:`. 
=> TCVP-2829 Fix drivers licence check digit logic in ARC service

src/backend/TrafficCourts/Citizen.Service/Validators/FormRecognizerValidator.cs, src/backend/TrafficCourts/Test/Citizen.Service/Validators/FormRecognizerValidatorTest.cs
It often happens that the OCR will merge fields or pull in adjacent text. These post-processing rules help clean up the OCR results before being passed to the OCR validator. In this case, the description fields sometimes has the vertical Count 1,2,3 text on the ticket image when the description itselft was blank.
The following rules where implemented:
- If Count 1 description has text, but Count 1 section and amount fields are blank, clear out the count 1 description.
- If Count 2 description has text, but Count 2 section and amount fields are blank, clear out the count 2 description.
- If Count 3 description has text, but Count 3 section and amount fields are blank, clear out the count 3 description.
if your change is a breaking change, …
=> TCVP-2832 OCR cleanup counts post-processing rules

src/backend/TrafficCourts/TrafficCourts.OracleDataApi.Test/DomainModelMappingTestGenerator.cs, src/backend/TrafficCourts/TrafficCourts.OracleDataApi.Test/EnumMappingTests.cs, src/backend/TrafficCourts/TrafficCourts.OracleDataApi/Client/V1/OracleDomainModelMappingProfile.cs
This should fix the problem with the data mappings. Should address the issue where it could not create EnumTypeConverter 
- move EnumTypeConverter from nested class to top level internal class
- update unit test generator to automatically exclude properties that exist on domain but not oracle
- update unit test generator to create explicit enum mappings
- add explicit enum mapping unit test.
=> Update Oracle Data Api mapping

gitops/charts/form-recognizer-3.0/templates/cronjobs.yaml
Created helm chart to cleanup old FormRecognizer3.0 analyses.
- delete logs older than 30 days (run daily)
- delete analyses older than 60 minutes (run hourly)
Deployed to DEV and TEST and confirmed functionality
=> Created FormRecognizer cronjobs to cleanup old analyses

src/backend/TrafficCourts/Workflow.Service/Dockerfile
- fixes the local dockerfile for running in docker compose
- remove setting user to 1001 which breaks stuff cause the `/etc/passwd` does not have a matching entry
- this setting would cause remote debugging to fail
=> Remove setting user to 1001 in Workflow service Dockerfile

src/frontend/citizen-portal/src/app/services/violation-ticket.service.ts, src/frontend/citizen-portal/src/app/shared/dialogs/image-ticket-not-found-dialog/image-ticket-not-found-dialog.component.html
TCVP-2784 When the backend throws a 500 error, the citizen-portal now displays a generic Internal Server Error instead of the very misleading error "Your ticket could not be read".
Forced backend to throw 500 and confirmed error is displayed.
=> TCVP-2784 Added generic error message for 500 errors

src/backend/TrafficCourts/Staff.Service/Controllers/DisputeController.cs, src/backend/TrafficCourts/Staff.Service/Services/DisputeService.cs, src/backend/TrafficCourts/Staff.Service/Services/IDisputeService.cs, src/backend/TrafficCourts/TrafficCourts.Staff.Service.Test/Controllers/DisputeControllerTest.cs, src/frontend/staff-portal/src/app/api/api/dispute.service.ts, src/frontend/staff-portal/src/app/api/model/lock.model.ts, src/frontend/staff-portal/src/app/api/swagger.json, src/frontend/staff-portal/src/app/components/staff-workbench/ticket-info/ticket-info.component.html, src/frontend/staff-portal/src/app/components/staff-workbench/ticket-info/ticket-info.component.ts, src/frontend/staff-portal/src/app/services/dispute.service.ts
- [TCVP-2871](https://justice.gov.bc.ca/jira/browse/TCVP-2871)
- Updated dispute 'validate' controller endpoint and service to not only update dispute status but also save dispute and violation ticket object being passed in. Fixed merge conflicts.
- Updated ticket validation view for scanned tickets view to submit form on 'validation' button click for saving dispute/ticket details. 
- Regenerated the api models based on the updated swagger.json.
=> TCVP-2871 Save dispute on validate button clicked

src/backend/TrafficCourts/Citizen.Service/Controllers/DisputesController.cs, src/backend/TrafficCourts/Staff.Service/Services/JJDisputeService.cs
TCVP-2878. The UI was showing documents from COMS with missing filenames. 
For now, filter these files so they are not shown to the user or staff.
=> TCVP-2878 Filter corrupt files in COMS

src/backend/TrafficCourts/Citizen.Service/Instrumentation/MeterProviderBuilderExtensions.cs, src/backend/TrafficCourts/Citizen.Service/Instrumentation/TracerProviderBuilderExtensions.cs, src/backend/TrafficCourts/Citizen.Service/Startup.cs, src/backend/TrafficCourts/Common/Configuration/Extensions.cs, src/backend/TrafficCourts/Messaging/MeterProviderBuilderExtensions.cs, src/backend/TrafficCourts/Messaging/TracerProviderBuilderExtensions.cs, src/backend/TrafficCourts/Staff.Service/Startup.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/Monitoring/Diagnostics.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/Monitoring/MeterProviderBuilderExtensions.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/Monitoring/TracerProviderBuilderExtensions.cs, src/backend/TrafficCourts/TrafficCourts.Coms.Client/TrafficCourts.Coms.Client.csproj, src/backend/TrafficCourts/TrafficCourts.Core.Test/Logging/Enrichers/ActivityEnricherTest.cs, src/backend/TrafficCourts/TrafficCourts.Core.Test/TrafficCourts.Core.Test.csproj, src/backend/TrafficCourts/TrafficCourts.Core/Logging/Enrichers/ActivityEnricher.cs, src/backend/TrafficCourts/TrafficCourts.Core/Logging/Enrichers/ActivityEnricherOptions.cs, src/backend/TrafficCourts/TrafficCourts.OracleDataApi/MeterProviderBuilderExtensions.cs, src/backend/TrafficCourts/TrafficCourts.OracleDataApi/TracerProviderBuilderExtensions.cs, src/backend/TrafficCourts/Workflow.Service/Startup.cs
- Fixes TCVP-2888 - filter out "receive from backplane" traces
- Cleans up the setup of trace and metrics by providing extension methods
=> Clean up trace and metric registration. Exclude Fusion Cache backplane

gitops/charts/traffic-court-online/charts/oracle-data-api/templates/deployment.yaml
Updated liveliness/readiness probe timeouts for oracle-data-api.
Given the container's limited CPU utilization (0.25m), it takes 120 seconds to start up. If we the container had more CPU, this could drop to 25 seconds for 1 CPU or 12 seconds for 2 CPUs.
=> TCVP-2885 Updated liveliness/readiness probe timeouts for oracle-data-api

infrastructure/static-site/maintenance/index.html
TCVP-2825
Updated the static maintenance site to match the newly requested wording. 
Performed a docker-compose up to confirm the site comes up and displays correctly.
=> TCVP-2825 Updated maintenance-site per new requirements

src/backend/TrafficCourts/Staff.Service/Authentication/Scopes.cs
- TCVP-2889 fixes the scope name to be consistent
- Dev and Test Keycloak have been updated, duplicating the permission and scopes as a transitionary update
- Production Keycloak uses the new names
- Note: the `update_court_appearance`/`update-court-appearance` does not appear to be in use. No sure when/who added this.
=> TCVP-2889 Update scope name to have correct naming convention

gitops/openshift/tools/image-streams/cassandra.yaml, gitops/openshift/tools/image-streams/common-object-management-service.yaml, gitops/openshift/tools/image-streams/dotnet.yaml, gitops/openshift/tools/image-streams/eclipse-temurin.yaml, gitops/openshift/tools/image-streams/form-recognizer-layout-3.0.yaml, gitops/openshift/tools/image-streams/jaeger.yaml, gitops/openshift/tools/image-streams/jaegertracing-all-in-one.yaml, gitops/openshift/tools/image-streams/keycloak.yaml, gitops/openshift/tools/image-streams/maven.yaml, gitops/openshift/tools/image-streams/nginx-120.yaml, gitops/openshift/tools/image-streams/node.yaml, gitops/openshift/tools/image-streams/rabbitmq.yaml, gitops/openshift/tools/image-streams/redis-cluster.yaml, gitops/openshift/tools/image-streams/redis-exporter.yaml, gitops/openshift/tools/image-streams/redis.yaml
- Changes image streams to pull thru BC Gov Artifactory instead of various registries directly.
=> Switch image streams to pull from artifactory

src/backend/TrafficCourts/Citizen.Service/Controllers/TicketsController.cs, src/backend/TrafficCourts/Citizen.Service/Features/Tickets/Search/Handler.cs, src/backend/TrafficCourts/Citizen.Service/Services/Tickets/Search/TicketSearchService.cs, src/backend/TrafficCourts/Test/Citizen.Service/Features/Tickets/SearchHandlerTest.cs
- TCVP-2563 exclude all RSI search results that do not match "MV6000E (040924)" or "MV6000E(040924)"
- If ticket is invalid VT2, skips the check if the ticket already disputed.
Add new tests confirm the pattern matching
=> TCVP-2563 Filter RSI search results to a specific FormNumber

gitops/charts/traffic-court-online/charts/arc-dispute-api/templates/deployment.yaml, gitops/charts/traffic-court-online/charts/citizen-api/templates/deployment.yaml, gitops/charts/traffic-court-online/charts/citizen-web/templates/deployment.yaml, gitops/charts/traffic-court-online/charts/staff-api/templates/deployment.yaml, gitops/charts/traffic-court-online/charts/staff-web/templates/deployment.yaml, gitops/charts/traffic-court-online/charts/workflow-service/templates/deployment.yaml, gitops/charts/virus-scan/templates/deployment.yaml
- adds minReadySeconds to deployments as an interim step before health checks can be implemented
=> TCVP-2895 add minReadySeconds until we can add health checks

gitops/charts/jaeger/values-prod.yaml, gitops/charts/jaeger/values-test.yaml
- since setting up jaeger in test, the PVC has grown to 650 MB / 1GB. The default configuration should only keep 3 days worth of traces. Increased the PVC in test to 2GB and 5GB for prod.
=> Increase PVC storage for jaeger for test and prod

src/backend/TrafficCourts/Citizen.Service/Validators/FormRecognizerValidator.cs, src/backend/TrafficCourts/Test/Citizen.Service/Validators/FormRecognizerValidatorTest.cs
TCVP-2914 
Added DetachmentLocation and HearingLocation to the list of fields we sanitize (replace whitespace characters with spaces).
Added Xunit test
=> TCVP-2914 Sanitized whitespace characters on some OCR fields

gitops/openshift/prod/citizen-web-for-justice-proxy.yaml
- Changes the default 30 second request timeout to 60 seconds to resolve OCR slowness
=> Increase Prod Citizen Portal request timeout to 60 sec

gitops/charts/jaeger/jaeger-aio/templates/deployment.yaml
- Adds failure threshold parameters to avoid restarting pod if a probe fails
=> TCVP-2921 update readinessProbe allowing retry

gitops/openshift/tools/image-streams/arc-dispute-api-imagestream.yaml, gitops/openshift/tools/image-streams/citizen-api-imagestream.yaml, gitops/openshift/tools/image-streams/citizen-web-imagestream.yaml, gitops/openshift/tools/image-streams/oracle-data-api-imagestream.yaml, gitops/openshift/tools/image-streams/staff-api-imagestream.yaml, gitops/openshift/tools/image-streams/staff-web-imagestream.yaml, gitops/openshift/tools/image-streams/workflow-service-imagestream.yaml
- The image streams for traffic court online were stored in the gitops repo. When working on argocd for the pipelines, I uninstalled the app and recreated it. Because the pipelines were part of the argocd pipeline they got delete and thus our production tag 2.0.3. I recreated the release to ensure 2.0.3 tag was available in the image stream. This PR moves the image stream definitions to this repo to avoid them being deleted again.
=> Move traffic court online image streams from gitops repos

src/backend/TrafficCourts/Staff.Service/Controllers/DisputeController.cs, src/backend/TrafficCourts/Staff.Service/Services/IPrintDigitalCaseFileService.cs, src/backend/TrafficCourts/Staff.Service/Services/PrintDigitalCaseFileService.cs, src/backend/TrafficCourts/TrafficCourts.OracleDataApi/TrafficCourts.OracleDataApi.csproj, src/backend/TrafficCourts/TrafficCourts.Staff.Service.Test/Controllers/DisputeControllerTest.cs, src/backend/TrafficCourts/TrafficCourts.Staff.Service.Test/Services/PrintDigialCaseFile/PrintDigitalCaseFileIntegrationTest.cs, src/frontend/staff-portal/src/app/api/api/dispute.service.ts, src/frontend/staff-portal/src/app/api/swagger.json, src/frontend/staff-portal/src/app/components/staff-workbench/contact-info/contact-info.component.html, src/frontend/staff-portal/src/app/components/staff-workbench/contact-info/contact-info.component.ts, src/frontend/staff-portal/src/app/components/staff-workbench/ticket-info/ticket-info.component.html, src/frontend/staff-portal/src/app/components/staff-workbench/ticket-info/ticket-info.component.ts, src/frontend/staff-portal/src/app/services/dispute.service.ts
- [TCVP-2865](https://jag.gov.bc.ca/jira/browse/TCVP-2865)
- Added functionality to print occam version of dcf for ticket validation view by creating a new PrintDigitalCaseFileService method to process occam dispute fields to render them in existing dcf template, and a new controller endpoint to return generated document. 
- Fixed existing DisputeController unit tests. Re-enabled integration test for print dcf by fixing the dependencies and added a new Xunit integration test for print ticket validation view.
- Added a sticky tool bar to the top of ticket validation page with a 'Print' button to trigger downloading generated pdf through calling the new endpoint to print ticket validation page.
if your change is a breaking change, please …
=> TCVP-2865 Print ticket validation view

src/backend/TrafficCourts/Workflow.Service/Services/EmailTemplates/EmailTemplate.cs
- TCVP-2932 using `@tickets.gov.bc.ca` is probably causing messages to go to the spam folder. This PR changes the from email address to `donotreply_courts.tco@gov.bc.ca` as per the [email best practices](https://raw.githubusercontent.com/wiki/bcgov/common-hosted-email-service/assets/bulk_email_best_practices.pdf) document
=> TCVP-2932 Adjust from address to avoid spam delivery

src/backend/TrafficCourts/Common/Features/Lookups/AgencyLookupService.cs, src/backend/TrafficCourts/Common/Features/Lookups/IAgencyLookupService.cs, src/backend/TrafficCourts/Staff.Service/Services/PrintDigitalCaseFileService.cs
- TCVP-2812
-  Added a method to return a specific Agency from the Redis Cache based on the agency id provided in Staff Service.
- Updated print DCF service to lookup courthouse location through agency lookup service based on 'CourtAgenId' provided from the dispute in order to display its name on the printed version of DCF.
=> TCVP-2812 Display Courthouse Location on Print DCF

gitops/charts/traffic-court-online/charts/arc-dispute-api/templates/deployment.yaml, src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/Configuration/SftpConnectionOptions.cs, src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Service/Services/SftpService.cs
- Sets to use [Workstation GC instead of Server GC](https://learn.microsoft.com/en-us/dotnet/core/runtime-config/garbage-collector#workstation-vs-server)  `DOTNET_gcServer=0` in Helm chart
- Ensure MemoryStream is disposed after reading the private key from configuration
- Change Dispose method to implement dispose pattern [correctly](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1063#pseudo-code-example)
=> TCVP-2950 make adjustments to fix possible memory leak

.docker/docker-compose.jaeger.yml, .env.template, docker-compose.yml, src/backend/TrafficCourts/Staff.Service/Mappers/Mapper.cs, src/backend/TrafficCourts/Staff.Service/Services/DisputeService.cs, src/backend/TrafficCourts/TrafficCourts.OracleDataApi/OracleDataApiService.cs, src/backend/TrafficCourts/TrafficCourts.Staff.Service.Test/Mappers/MapperTest.cs
- [TCVP-2977](https://jag.gov.bc.ca/jira/browse/TCVP-2977)
- This fixes the issue mentioned in the ticket TCVP-2977 by pulling the disputant name from RSI ticket search before submitting to ARC and if it's not available through ticket search, it falls back to default disputant name from violation ticket data and disputant entered data respectively in the database.
- Updated mapper for submit dispute approved message to map icbc name if provided or the name on violation ticket for disputant name to submit to ARC.
- Updated XUnit test for the mapper.
- Updated docker compose file for jaeger to enable tracing for citizen-api, staff-api and oracle-data-api.
- Updated docker-compose.yml file to add necessary parameters to enable RSI ticket …
=> TCVP-2977: Populate ARC File with Violation Ticket Disputant Name from RSI Ticket Search

src/backend/TrafficCourts/Staff.Service/Services/PrintDigitalCaseFileService.cs
- [TCVP-3043](https://jag.gov.bc.ca/jira/browse/TCVP-3043)
- Fixed the issue that causes 'NullReferenceException' was thrown on print dcf request by adding null check for optional object of 'JjDisputedCountRoP'.
=> TCVP-3043: Fix Print DCF Null Reference Error

src/backend/oracle-data-api/pom.xml, src/backend/oracle-data-api/src/main/java/ca/bc/gov/open/jag/tco/oracledataapi/config/RedisConfig.java
- [TCVP-3037](https://jag.gov.bc.ca/jira/browse/TCVP-3037)
- Added functionality to enable adaptive topology refreshing for Redis through 'ClusterTopologyRefreshOptions' in Lettuce to configure topology refreshing based on certain triggers such as 'moved redirect' and 'cannot reconnect'.
=> TCVP-3037: Refresh Oracle Data Api Connection on Redis Restart
